
const
  cmDoc_Name   = 60001;
  cmOrg_Name   = 60002;
  cmDoc_Num    = 60003;
  cmDoc_NumEx  = 60004;
  cmDoc_Date   = 60005;
  cmDoc_From   = 60006;
  cmDoc_To     = 60007;
  cmDog_Num    = 60008;
  cmDog_NumEx  = 60009;
  cmDog_Date   = 60010;
  cmDog_From   = 60011;
  cmDog_To     = 60012;
  cmOwner_Num    = 60013;
  cmOwner_NumEx  = 60014;
  cmOwner_Date   = 60015;
  cmOwner_From   = 60016;
  cmOwner_To     = 60017;

 end;
