//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 5.80 - модуль "Управление бюджетом"
// Константы идентификаторов параметров типа "Список бюджетов"
//------------------------------------------------------------------------------

#ifndef __FpListParam_Inc__
#define __FpListParam_Inc__

Const
  Var_wListMode                 = 'wLsM';
  Var_wUserList                 = 'wULt';
  Var_wAutoList                 = 'wALt';

  Tbl_tblList                   = 'TLST';

  TblVar__tblList_NRec          = 'TLNR';
  TblVar__tblList_cRecCO        = 'TLCC';
  TblVar__tblList_cSlaveRecCO   = 'TLSC';
  TblVar__tblList_cRecPer       = 'TLCP';
  TblVar__tblList_cSlaveRecPer  = 'TLSP';
  TblVar__tblList_cRecVar       = 'TLCV';
  TblVar__tblList_cSlaveRecVar  = 'TLSV';
  TblVar__tblList_sStage        = 'TLSS';
  TblVar__tblList_sSlaveStage   = 'TLCS';
  TblVar__tblList_wBitReg       = 'TLBR';
  TblVar__tblList_wSlaveBitReg  = 'TLSR';
  TblVar__tblList_wDelMode      = 'TLDM';
  TblVar__tblList_fOrder        = 'TLFO';
end;

#endif//__FpListParam_Inc__
