//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 5.80 - модуль "Управление бюджетом"
// Константы идентификаторов параметров типа "Периоды и подпериоды"
//------------------------------------------------------------------------------

#ifndef __FpPerParam_Inc__
#define __FpPerParam_Inc__

Const
  Var_cCurPer                       = 'cCPr';

  Tbl_tblPerBud                     = 'TTPB';
  Tbl_LooptblSubPerBud              = 'TSPB';

  TblVar__tblPerBud_cRec            = 'PBcR';

  TblVar__LooptblSubPerBud_cMain    = 'SPcM';
  TblVar__LooptblSubPerBud_NRec     = 'SPNR';
  TblVar__LooptblSubPerBud_cNode    = 'SPNd';
  TblVar__LooptblSubPerBud_wDelMode = 'SPDM';
end;

#endif//__FpPerParam_Inc__
