//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 5.80 - модуль "Управление бюджетом"
// Константы идентификаторов параметров типа "Реквизиты копии"
//------------------------------------------------------------------------------

#ifndef __FpStageParam_Inc__
#define __FpStageParam_Inc__

Const
  VAR_cCurBudVariant     = 'CBVt';
  Var_sCurStage          = 'CuSt';
  Var_cCurArea           = 'CrAr';
  Var_sCurDescr          = 'Dscr';
end;

#endif//__FpStageParam_Inc__
