/*
 ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
 บ                     (c) 1994,97 ชฎเฏฎเ ๆจ๏ €€’€                      บ
 บ เฎฅชโ        : €€’€                                                 บ
 บ ‘จแโฅฌ        :  ข ซ์็ฅแชฎฅ แ๋เ์ฅ                                        บ
 บ ฅเแจ๏        : 5.20                                                      บ
 บ  งญ ็ฅญจฅ    : ฎจ ฌ ชเฎแ๋ คซ๏ ฎโซ คชจ                                   บ
 บ โขฅโแโขฅญญ๋ฉ : ฅข็ฅญชฎ €ญคเฅฉ €ซฅชแ ญคเฎขจ็(Andrew)                     บ
 บ  เ ฌฅโเ๋     : …’                                                       บ
 ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/


#ifndef _DEBUG_AND_MAC_
#define _DEBUG_AND_MAC_

#include Debug.Mac

#Declare DecWrStructWord(prStr_Dec, S_Word_Dec, prNameFunc_Dec)
{
 if (GlbFlagDeb)
     WriteInFileDebug_Proc(#prStr_Dec + '  w1 ='+string(#S_Word_Dec.w1)+ ' w2 ='+string(#S_Word_Dec.w2)+' w3 ='+string(#S_Word_Dec.w3)+' w4 ='+string(#S_Word_Dec.w4)+' w5 ='+string(#S_Word_Dec.w5), #prNameFunc_Dec)
}
#end

#end
