const

  // числа

  // Даты

  // ссылки

  // наименования
  reName    = 3000;
  reCode    = 3001;
  reTheme   = 3002;
  reFpCo    = 3003;
  rewNum    = 3004;
  reWorkDay = 3005;
  reSumZatr = 3006;
  rePrice   = 3007;
  reFixSum  = 3008;
  rePrib    = 3009;
  reSmeta   = 3010;
  reAbbr    = 3011;
  reSumFOT  = 3012;
  reLook    = 3013;

  // ограничения
  reBySmeta = 4001;

  // параметры
  repSmeta  = 5001;

end
