

#ifndef __LIMIT_INC__
#define __LIMIT_INC__

const
  cnt_OverLimKol = 1;
  cnt_OverLimSum = 2;
  cnt_LimKolZero = 4;
  cnt_NotMCInLim = 8;
end;

const
  cnt_ModeLimDO     = 0;
  cnt_ModeLimNkl    = 1;
end;

const
  cnt_FindSpOrder   = 1;
end;

/*
const
  cnt_ReadPrKol          = 1;
  cnt_ReadPrSum          = 2;
  cnt_ReadPriznak        = 4;
  cnt_NotReadZeroKol     = 8;
  cnt_NotReadZeroSelect  = 16;
  cnt_NotReadZerodKDoc   = 32;
  cnt_ReadIR             = 64;
  cnt_ForOtchetStLimit   = 128;
end;
*/

const
	cnt_StrDSK_FlagDeb = 'StrForDSK_FlagDeb_Andrew';
end;

#endif  // __LIMIT_INC__
