//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 5.80 - модуль "Управление бюджетом"
// Макросы
//------------------------------------------------------------------------------

#ifndef _FpAF_Mac_
#define _FpAF_Mac_

/////////////////////////////////////////////////////////////////////
#declare mAF_Tbl(_Tbl)
L#_Tbl
#end // mAF_Tbl

/////////////////////////////////////////////////////////////////////
#declare mAF_Fun_Modify(_Fld)
Function Modify#_Fld(_cRec : comp) : boolean;
{ Modify#_Fld := (AddFldState.#_Fld) and (AddFldState.cRec = _cRec);
}
#end // mAF_Fun_Modify

/////////////////////////////////////////////////////////////////////
#declare mAF_Fun_SetModify(_Fld)
Procedure SetModify#_Fld(_cRec : comp; _Modify : boolean);
{
  AddFldState.#_Fld := _Modify;
  AddFldState.cRec  := _cRec;
}
#end // mAF_Fun_SetModify

/////////////////////////////////////////////////////////////////////
#declare mAF_SetModify(_Fld, _Var)
    SetModify#_Fld(KatH.NRec, #_Var);
#end // mAF_ChkFld

/////////////////////////////////////////////////////////////////////
#declare mAF_IsModify(_Fld)
  (Modify#_Fld(_cRec))
#end // mAF_IsModify

/////////////////////////////////////////////////////////////////////
#declare mAF_ChkFld(_Fld)
  ##_Fld :
  {
    SetModify#_Fld(KatH.NRec, True);
  }
#end // mAF_ChkFld

/////////////////////////////////////////////////////////////////////
#declare mAF_LoadFld(_pObj,_Fld)
  Set #_Fld := #_pObj.Get#_Fld(_cRec);
#end // mAF_LoadFld

/////////////////////////////////////////////////////////////////////
#declare mAF_LoadTbl(_pObj,_Tbl)
  #_pObj.Get#_Tbl(_cRec);
  ReReadRecord(#L#_Tbl);
#end // mAF_LoadTbl

/////////////////////////////////////////////////////////////////////
#declare mAF_SaveFld(_pObj,_Fld)
  if (Modify#_Fld(_cRec))
    #_pObj.Set#_Fld(_cRec, #_Fld);
#end // mAF_SaveFld

/////////////////////////////////////////////////////////////////////
#declare mAF_SaveTbl(_pObj,_Tbl)
  if (Modify#_Tbl(_cRec))
    #_pObj.Set#_Tbl(_cRec);
#end // mAF_SaveTbl



#end  // _FpMAF_VPP_
