//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 5.80 - модуль "Управление бюджетом"
// Макросы
//------------------------------------------------------------------------------

//#ifndef _FpDECL_Mac_
//#define _FpDECL_Mac_

/////////////////////////////////////////////////////////////////////
#undef mDeclModifyFun
#declare mDeclModifyFun(_TBuff)
Function InsP(var _Buff : #_TBuff) : integer;
Function UpdP(var _Buff : #_TBuff) : integer;
Function DelP(    _Buff : #_TBuff) : integer;
#end// mDeclModifyFun

/////////////////////////////////////////////////////////////////////
#undef mDeclGetFun               
#declare mDeclGetFun(_Fun,_Type,_TBuff)
Function Buf#_Fun(_Buff : #_TBuff) : #_Type;
Function #_Fun(_cRec : comp) : #_Type;
#end// mDeclGetFun

/////////////////////////////////////////////////////////////////////
#undef mDeclSetFun
#declare mDeclSetFun(_Fun,_Type,_TBuff)
Function Buf#_Fun(var _Buff : #_TBuff; _Value : #_Type) : boolean;
Function #_Fun(var _cRec : comp; _Value : #_Type) : boolean;
#end // mDeclSetFun

//#endif//_FpDECL_Mac_

