const

  // числа
	reType      = 1501;
	reStatus    = 1502;
	reTable     = 1503;
	reTypeObj   = 1504;
	reTypePodr  = 1505;
	reTypeParty = 1506;
	reTypePos   = 1507;
	reTypeMol   = 1508;

  // даты
	reProbeDate = 2001;

	// времена
	reProbeTime = 2501;

  // ссылки
  recTsKachvo   = 3001;
  recKatSort    = 3002;
  recKatStats   = 3003;
  recObject     = 3004;
  recPodr       = 3005;
  recParty      = 3006;
  recPos        = 3007;
  recMol        = 3008;
  recPerson     = 3009;
  recOwner      = 3010;
  recStatus     = 3011;

  // наименования
	reDescr      = 4001;
	reDesGr      = 4002;
	reCode       = 4003;
	reName       = 4004;

	// ограничения и подцепки
  reNoBound          = 5000;
	reToType           = 5001;
	reToTypeMc         = 5002;
	reToTypeMcOrg      = 5003;
	reToTypeMcMnfZakaz = 5004;
	reToTypeMcPodr     = 5005;

	// быстрая навигация
	reByTypeCode       = 6001;


	// параметры
	reTypeParam         = 7101;
	reTableParam        = 7102;
	reTypeOrgParam      = 7103;
	reTypeMnfZakazParam = 7104;
	reTypePodrParam     = 7105;
	reMcUslParam        = 7106;
	reOrgParam          = 7107;
	reMnfZakazParam     = 7108;
	rePodrParam         = 7109;
	reCodeParam         = 7110;

end

