const
  // цифирики
  reBaseFinSumma  = 0001;
  reBaseFinSumVal = 0002;

  // дата одна у нас
  reBaseFindDoc   = 1001;

  // ссылки и признаки
  reBaseFincDogovor    = 2001;
  reBaseFincAppDogovor = 2002;
  reBaseFincCalPlan    = 2003;
  reBaseFincBaseDoc    = 2004;
  reBaseFinTiDkBase    = 2005;
  reBaseFinTipDoc      = 2006;
  reBaseFinTiDkGal     = 2007;
  reBaseFincSoprDoc    = 2008;
  reBaseFincPlPor      = 2009;
  reBaseFincVeksl      = 2010;
  reBaseFincVal        = 2011;
  reBaseFincOrg        = 2012;
  reBaseFincFilKor     = 2013;
  reBaseFincSoprHoz    = 2014;
  reBaseFincPlDgDist   = 2015;
  reBaseFincKatSopr    = 2016;
  reBaseFincPredoplDO  = 2017;


  // цэтыре строки
  reBaseFinNoDoc   = 3015;
  reBaseFinDescr   = 3016;
  reBaseFinDesGr   = 3017;
  reBaseFinNamePl  = 3018;

  // логика
  reBaseFinPrShtraf    = 4001;

  reNoBound     = 5000;
  reByBaseDoc   = 5001;
  reByOrg       = 5002;
  reByKatSopr   = 5003;

  reBaseDocParam   = 6001;
  reOrgParam       = 6002;
  reKatSoprParam   = 6003;

end

