const

  // числа
  reVolume    = 1001;
  reOW        = 1002;
  reVolOW     = 1003;
  rePriceGSM  = 1004;
  reOW1       = 1005;
  reVolOW1    = 1006;
  rePriceGSM1 = 1007;
  reOW2       = 1008;
  reVolOW2    = 1009;
  rePriceGSM2 = 1010;
  reSpeedExi  = 1011;
  reProbegAll = 1012;
  reProbegN   = 1013;
  reTimeAkk   = 1014;
  reProbegTo  = 1015;
  reProbegTo2 = 1016;
  reForceLS   = 1017;
  reForceKVT  = 1018;
  reProbegKap = 1019;
  reTarAvt    = 1020;
  reTarVd     = 1021;
  reTarGr     = 1022;
  reTarPr     = 1023;
  reTarifTkm  = 1024;
  reTarifTn   = 1025;
  reTarifLoad = 1026;
  reKofZakk   = 1027;
  reGruzPod   = 1028;
  reWeight    = 1029;
  rePrMaslo   = 1030;
  reProbegPok = 1031;
  reMotoPok   = 1032;
  reProbegPok1= 1033;
  reMotoPok1  = 1034;
  reDop1      = 1035;
  reDop2      = 1036;
  reDop3      = 1037;
  reDop4      = 1038;
  reDop5      = 1039;
  reDop6      = 1040;

  reTipTC     = 1501;
  reKolWheel  = 1502;
  reZapWheel  = 1503;
  reKolSmena  = 1504;
  reWDop1     = 1505;
  reWDop2     = 1506;
  reWDop3     = 1507;
  reWDop4     = 1508;
  reWDop5     = 1509;
  reProbegAkk = 1510;

  // даты
  reGodV      = 2001;
  reDatAkk    = 2002;
  reDatTO     = 2003;
  reDatTO2    = 2004;
  reDatKap    = 2005;
  reDatOk     = 2006;
  reDatPok    = 2007;
  reDatPok1   = 2008;

  // ссылки
  recMarka    = 3001;
  recTipTex   = 3002;
  recOrg      = 3003;
  rePostnRec  = 3004;
  recPodr     = 3005;
  recKatOs    = 3006;
  reIzgnRec   = 3007;
  recToplivo  = 3008;
  recToplivo1 = 3009;
  recToplivo2 = 3010;
  recPutLst   = 3011;
  recKatUsl   = 3012;
  recKatEdAvt = 3013;
  recKlVidOpl = 3014;

  // наименования
  reNomer     = 4001;
  reGarNom    = 4002;
  rePassport  = 4003;
  reTranNom   = 4004;
  rePostName  = 4005;
  reIzgName   = 4006;
  reZavNom    = 4007;

  // ограничения и подцепки
  reNoBound    = 5000;
	reToOrg      = 5001;
	reToTipTex   = 5002;

  // быстрая навигация
	reByKatOS    = 6001;

  // параметры
	reOrgParam    = 7101;
	reTipTexParam = 7201;
	reKatOSParam  = 7301;

end

