const

  // числа
  reMaxDolgRub  = 1001;
  reMaxDolgVal  = 1002;
  reSkid        = 1003;
  reCredit      = 1004;


  // строки
  reName        = 2001;
  reCode        = 2002;
  reTipOrg      = 2003;
  reAddr        = 2004;
  reOKPO        = 2005;
  reOKDP        = 2006;
  reOKONH       = 2007;
  reTEL         = 2008;
  reUNN         = 2009;
  reIndexK      = 2010;
  reKodPlatNDS  = 2011;

  // ссылки
  recState      = 3001;
  recCity       = 3002;
  reTipKnt      = 3003;
  reuseNalogs   = 3004;
  recGrafik     = 3005;
  recCalendar   = 3006;
	reUpolnPredst = 3007;

  // логика
  reCorpoIn     = 4001;
  reNeedCustom  = 4002;
  reisArch      = 4003;


  reNoBound        = 5000;

  // быстра навигация
  reByName        = 6001;
  reByCode        = 6002;

  // параметры

  reNameParam       = 7101;
  reCodeParam       = 7102;

end

