const

  reSumma_Indent       = 1;
  reDiscount_Indent    = 2;

  reField01_Indent    = 101;
  reField02_Indent    = 102;
  reField03_Indent    = 103;
  reField04_Indent    = 104;
  reField05_Indent    = 105;

  reStartDate_Indent = 1000;
  reEndDate_Indent   = 1001;
  reBookDate_Indent  = 1002;
  reOrdData_Indent   = 1003;
  reExeDate_Indent   = 1004;

  rePrior_Indent       = 2000;
  reStatus_Indent      = 2001;
  reResInfo_Indent     = 2003;
  reOrdDirect_Indent   = 2004;
  reExeDirect_Indent   = 2005;
  reOrd_Indent         = 2006;
  reExe_Indent         = 2007;
  reDirect_Indent      = 2008;
  recPreson_Indent     = 2009;
	reTax_Indent         = 2010;

  reRole1_Indent       = 2011;
  reRole2_Indent       = 2012;
  reRole3_Indent       = 2013;
  reRole4_Indent       = 2014;
  reRole5_Indent       = 2015;

  reFilialIndent       = 2016;

  reCode1_Indent       = 2021;
  reCode2_Indent       = 2022;
  reCode3_Indent       = 2023;
  reCode4_Indent       = 2024;
  reCode5_Indent       = 2025;

  reValue1_Indent = 2031;
  reValue2_Indent = 2032;
  reValue3_Indent = 2033;
  reValue4_Indent = 2034;
  reValue5_Indent = 2035;

  reName_Indent        = 3000;
  reNumDoc_Indent      = 3001;
  reOrdNum_Indent      = 3002;
  reExeNum_Indent      = 3003;
	reOrdFormOpl_Indent  = 3004;
	reExeFormOpl_Indent  = 3005;

  reNoBound_Indent     = 4000;
  reToResInfo_Indent   = 4001;
  reToPriority_Indent  = 4002;
  reToSFilters_Indent  = 4003;
	reToState_Indent		  = 4004;

  reResInfo__Indent    = 5000;
  rePrior__Indent      = 5001;
  reSFilters__Indent   = 5002;
	reState__Indent 	    = 5003;

  reSFiltersConst_Indent = 6001;

  reInfo_Indent        = 10000;
end
