const

  reObjAcctStartDate   = 1000;

  reObjAcctName        = 2000;
  reObjAcctComment     = 2001;

  reObjAcctTypeOwn       = 3000;
  reObjAcctcOwner        = 3001;
  reObjAcctcOwnerDop     = 3002;
  reObjAcctKindRec       = 3003;
  reObjAcctTypeObj       = 3004;
  reObjAcctcObject       = 3005;
  reObjAcctCondRec       = 3006;
  reObjAcctTypeHier      = 3007;
  reObjAcctcObjAcct      = 3008;
  reObjAcctVidSopr       = 3009;
  reObjAcctNumSort       = 3010;


  reObjAcctNoBound     = 4000;
  reObjAcctOwnObj1     = 4001;
  reObjAcctOwnObj2     = 4002;
  reObjAcctObjOwn1     = 4003;
  reObjAcctObjOwn2     = 4004;

  reObjAcctDelCur      = 4101;
  reObjAcctNew         = 4102;
  reObjAcctNewViaBuff  = 4103;

  reObjAcctSearch        = 4201;
  reObjAcctSearchViaBuff = 4202;

  reObjAcctTypeOwnParam    = 5001;
  reObjAcctDocOwnParam     = 5002;
  reObjAcctTypeObjParam    = 5003;
  reObjAcctDocObjParam     = 5004;

  reObjAcctOwnBuffParam    = 5011;
  reObjAcctObjBuffParam    = 5012;

  reObjAcctTypeForOwnObj   = 6001;
end

