const

  // числа
	reTip        = 1001;
	reTipMoney   = 1002;
  reVhodNal    = 1003;
  reVidForm    = 1004;
  reCalcCustom = 1005;
	reStatus     = 1006;
	reKolonka    = 1008;

	reCurs       = 1501;
	rePrSkl      = 1502;
	reRndR       = 1503;
	reRndV       = 1504;

  // даты
  redPrice     = 2001;
  redCurs      = 2002;
	redBeg       = 2003;
	redEnd       = 2004;

  // ссылки
  recVal       = 3001;
  recNalog     = 3002;
  recOrg       = 3003;
  recGrPrice   = 3004;
  recGrParty   = 3005;
  recPayment   = 3006;
	recNote      = 3007;

  // наименования
  reName       = 4001;
  reZag        = 4002;
	rePod        = 4003;
	reForma      = 4004;

	// ограничения и подцепки
  reNoBound         = 5000;
	reToTip           = 5001;
	reToTipPrice      = 5002;
	reTocVal          = 5003;
	reToTipName       = 5004;
	reToStatusPrice   = 5005;
	reToGrPriceStatus = 5006;
	reToOrgStatus     = 5007;

	// быстрая навигация
	reByTipName         = 6001;
	reByNamePrice       = 6002;
	reByStatusPriceName = 6003;

	// параметры
	reTipParam        = 7101;
	reNameParam       = 7201;
	rePriceParam      = 7202;
	reStatusParam     = 7203;
	reVhodNalParam    = 7204;
	reGrPriceParam    = 7205;
	reOrgParam        = 7206;
	reValParam				= 7207;

end

