const

  // числа
  reCenaZav        = 101;
  reSkidZav        = 102;
  reMAXON          = 103;
  reMAXRN          = 104;
  reMAXORN         = 105;
  reVHODON         = 106;


  // Даты
  redSertif        = 1001;
  redAnaliz        = 1002;
  redGodn          = 1003;
	redtGodn         = 1004;

  // Ссылки
  reKons           = 2001;
  recMC            = 2002;
  recValPar        = 2003;
  recOrgPar        = 2004;
  recGroupParty    = 2005;
  recResOtgr       = 2006;
  recSertific      = 2007;

  // вставка и удаление записи
  reDeleteCurrent = 2008;
  reInsertRecord  = 2009;


  // Строки
  reKOD            = 3001;
  reName           = 3002;
  reNSertif        = 3003;
  reWhoSertif      = 3004;
  reNAnaliz        = 3005;

  // Логика
  reinCountry      = 4001;


  // ограничеия и подцепки
  reNoBound       = 5000;
  reByKatMc       = 5001;
  reByKatOrg      = 5002;
  reByGroupParty  = 5003;


  // быстра навигация
  reByName        = 6001;
  reByCode        = 6002;

  // параметры
  reKatMcParam      = 7001;
  reKatOrgParam     = 7002;
  reGroupPartyParam = 7003;
  reTypeParam       = 7005;
  //

  reNameParam       = 7101;
  reCodeParam       = 7102;


  reKonsConst       = 10001;
end

