const
// comp
  recRec       = 1001;
  recRec_      = 1002;
  recAttrNam   = 1003;
  resAttrNam_  = 1004;
  revComp      = 1005;
  revComp_     = 1006;
 //Double
  revDouble    = 1007;
  revDouble_   = 1008;
// Word
  rewTable     = 1501;
  rewTable_    = 1502;
//строки
  revString    = 2000;
  revString_   = 2001;
  revlVar      = 2002;
//время
  revTime      = 2500;
  revTime_     = 2501;
//дата
  revDate      = 2502;
  revDate_     = 2503;
	reToDate     = 2504;
// ограничения
	reNoBound     = 4000;
	reToPar       = 4001;
	reToObj				= 4002;
  rebwTable     = 4003;
  rebcRec       = 4004;
  rebsAttrNam   = 4005;
	recAttrNam_   = 4006;
	rebvDate			= 4007;
// добавление/удаление записи
	reDeleteCurrent = 5000;
	reInsertRecord  = 5001;
end
