const

  // числа
  reNBrig   	= 0001;
	reTabN      = 0002;
	reKTY       = 0003;
	reProc      = 0004;
	rePriz      = 0005;

	//даты
	reIncluded	= 1001;
	reExcluded	= 1002;


  // ссылки
	reCex       = 2001;
	reCexOz     = 2002;
	recPodr     = 2003;
	recPodrOz   = 2004;
	recLsch			= 2005;
	reTPerson   = 2006;
	reOldSch    = 2007;

  // наименования
	reStrTabN		= 3001;


  reNoBound     = 4000;
  reByNBrig     = 4001;

  reNBrigParam	= 10001;
end

