const
  reStartDate     = 1000;
  reEndDate       = 1001;
  reRecomDate     = 1002;

  rePrior       = 2000;
  recSpMnPl     = 2001;
  recStatus     = 2002;
  reResComp01   = 2011;
  reResComp02   = 2012;
  reResComp03   = 2013;
  reResComp04   = 2014;
  reResComp05   = 2015;
  reResComp06   = 2016;
  reResComp07   = 2017;
  reResComp08   = 2018;
  reResComp09   = 2019;
  reResComp10   = 2020;

  reFldNum      = 3000;
  reCondRec     = 3001;
  reResWord01   = 3011;
  reResWord02   = 3012;
  reResWord03   = 3013;
  reResWord04   = 3014;
  reResWord05   = 3015;
  reResWord06   = 3016;
  reResWord07   = 3017;
  reResWord08   = 3018;
  reResWord09   = 3019;
  reResWord10   = 3020;

  reNoBound        = 4000;
  reToSpMnPl       = 4001;
  reToSpMnPlFldNum = 4002;

  reInsertRecord  = 4050;

  reSpMnPlParam   = 5000;
  reFldNumParam   = 5001;
end
