const
	reMinVol 			= 100;
	reEdNorm		  = 101;
	reTMCircle		= 102;
	reTMMaxVp			= 103;
	reTMMaxZp     = 104;
	reProcent			= 105;
	reActive      = 106;
	reStatus      = 107;
	retObject     = 108;
	reKind				= 109;
	rewPodr				= 110;
	redType       = 111;
	rewEdTime     = 112;
	reProduct     = 113;
  rewDocFunc    = 119;


	reStartDate   = 1000;
  reEndDate     = 1001;
	reCheckDate01 = 1002;
	reCheckDate02 = 1003;
	reCheckDate03 = 1004;
	reCheckDate04 = 1005;
	reCheckDate05 = 1006;


	reRole1       = 2011;
  reRole2       = 2012;
  reRole3       = 2013;
  reRole4       = 2014;
  reRole5       = 2015;

  reValue1_KatMarsh = 2021;
  reValue2_KatMarsh = 2022;
  reValue3_KatMarsh = 2023;
  reValue4_KatMarsh = 2024;
  reValue5_KatMarsh = 2025;

	reCheckers01  = 2027;
	reCheckers02  = 2028;
	reCheckers03  = 2029;
	reCheckers04  = 2030;
	reCheckers05  = 2031;
	reCheckers06  = 2032;
	reCheckers07  = 2033;
	reCheckers08  = 2034;
	reCheckers09  = 2035;

	reVariant     = 2036;
	reOwner       = 2037;
	recObject     = 2038;
	recPodr       = 2039;
	recEd         = 2040;
	reParGroup    = 2041;
	recNormGroup  = 2042;
	recHeader     = 2043;



	reDesign01    = 3000;
	reDesign02    = 3001;
	reDesign03    = 3002;
	reDesign04    = 3003;
	reDesign05    = 3004;
	reDesign06    = 3005;
	reShifr				= 3006;
	reName				= 3007;


	reNoBound     = 4000;
	reToObject    = 4001;
	reToStatus    = 4002;
	reToSFilters  = 4003;

	reToVariant_  = 5000;
	reToStatus_   = 5001;
	recObject_    = 5002;
	retObject_    = 5003;
	recPodr_      = 5004;
	rewPodr_      = 5005;
	reStatus_     = 5006;
	reInfo  			= 10000;
	end
