const



  // числа

  // Даты

  // ссылки
  recSaldTune  = 2000;
  recObj       = 2001;
  recKau1      = 2002;
  recKau2      = 2003;
  recKau3      = 2004;
  recKau4      = 2005;
  recKau5      = 2006;
  recKau6      = 2007;
  recKau7      = 2008;
  recKau8      = 2009;
  recKau9      = 2010;

  // наименования

  reNoBound    = 4000;
  reByFull     = 4001;
  reBySaldTune = 4002;
  reByObj      = 4003;
  reByKau1     = 4004;
  reByKau2     = 4005;
  reByKau3     = 4006;
  reByKau4     = 4007;
  reByKau5     = 4008;
  reByKau6     = 4009;
  reByKau7     = 4010;
  reByKau8     = 4011;
  reByKau9     = 4012;

  // вставка и удаление записи
  reDeleteCurrent = 6101;
  reInsertRecord  = 6102;

  // параметры
  recSaldTuneParam = 10001;
  recObjParam      = 10002;
  recKau1Param     = 10003;
  recKau2Param     = 10004;
  recKau3Param     = 10005;
  recKau4Param     = 10006;
  recKau5Param     = 10007;
  recKau6Param     = 10008;
  recKau7Param     = 10009;
  recKau8Param     = 10010;
  recKau9Param     = 10011;

end
