const

  // числа
	reQualityControl = 1501;
	reIntervalQC     = 1502;

  // даты

	// времена

  // ссылки
  recGroupMc   = 3001;
  recMc        = 3002;
  recOwner     = 3003;

  // наименования

	// ограничения и подцепки
  reNoBound          = 5000;
	reToGroupMc        = 5001;
	reToOwner          = 5002;

	// быстрая навигация
	reByMc             = 6001;

	// параметры
	reOwnerParam        = 7101;
	reGroupMcParam      = 7102;
	reMcParam           = 7103;

end

