const

  // числа (double)
  rePROC       = 1001;
  reSUMMA      = 1002;
  reSUMMARC    = 1003;
  reSUMMARCVal = 1004;
  reTARIF      = 1005;
  reCHASF      = 1006;
  reKOLDN      = 1007;
  reKOLDNGR    = 1008;
  reCHASGR     = 1009;
  reVolWrk     = 1010;
  reKoff       = 1011;
  reDdop7      = 1012;
  redDop8      = 1013;
  redDop9      = 1014;


  // числа (word)
  reMES    = 1501;
  reMESN   = 1502;
  reREJIM  = 1503;
  reSISOPL = 1504;
  reCODTAR = 1505;
  reRAZR   = 1506;
  rewdop4  = 1507;
	rewdop5  = 1508;
	rewdop6  = 1509;
	rewIst   = 1510;


  // времена
  reTimeN = 2001;
  reTimeK = 2002;

  // даты
  reDATAN = 2501;
  reDATOK = 2502;


  // ссылки
  recSave_drv = 3001;
  recVal      = 3002;
  recKatEdVod = 3003;
  recKatUsl   = 3004;
  recKatzak   = 3005;
  recPutLst   = 3006;
  recmaravt   = 3007;
  recDop1     = 3008;
  recDop2     = 3009;
  recDop3     = 3010;
  recKlalg    = 3011;
  recTarifn   = 3012;
  recIst      = 3013;

  // наименования
  reLastUser = 4001;
  reNPL      = 4002;

  // ограничения и подцепки
  reNoBound    = 5000;
	reToBounds01 = 5001;
	reToBounds02 = 5002;

  // быстрая навигация

  // параметры
	recSave_DrvParam  = 7101;
	recPutLstParam    = 7102;
	recKatZakParam    = 7103;

end

