const

  recoTable      =1;
	recSpec        =2;
	recSaldTune    =3;
	recObj         =4;
	recKau1        =5;
	recKau2        =6;
	recKau3        =7;
	recKau4        =8;
	recKau5        =9;
	recKau6        =10;
	recKau7        =11;
	recKau8        =12;
	recKau9        =13;

	reNoBound         =101;
	reToTable         =102;
	reToSpec          =103;
	reTableParam      =104;
	reSpecParam       =105;
	recSaldTuneParam  =106;
	rewTableParam     =107;
	recSpecRecrParam  =108;
	reInsertRecord    =109;
	rewDocConst       =110;
	reDeleteRec   		=111;
  recObjParam       =112;
	reInsertRecordExt =113;
	recKau1Param      =114;
	recKau2Param      =115;
	recKau3Param      =116;
	recKau4Param      =117;
	recKau5Param      =118;
	recKau6Param      =119;
	recKau7Param      =120;
	recKau8Param      =121;
	recKau9Param      =122;

	end
