const

  // числа
  reAttr      = 1001;
  recoTable   = 1002;
  reisLeaf    = 1003;
  reOfficeNum = 1004;

  // даты

	// времена

  // ссылки
  recMain     = 3001;
  recMean     = 3002;
  recNode     = 3003;
  recPersons  = 3004;
  recStd      = 3005;
  recVal      = 3006;
  recStand    = 3007;

  // наименования
  reCode      = 4001;
  reName      = 4002;
  reAbbr      = 4003;
  reLevelCode = 4004;

	// ограничения и подцепки
  reNoBound          = 5000;
  reByCode           = 5001;
  reByName           = 5001;

	// параметры
	reCodeParam        = 7001;
	reNameParam        = 7002;
	reMainParam        = 7003;

end
