const

  // числа
	reValueMain   = 1001;
	reValueMin    = 1002;
	reValueMax    = 1003;

	reKodGrKau    = 1501;
	reKodGrKauMin = 1502;
	reKodGrKauMax = 1503;

  // даты

	// времена

  // ссылки
  recKatKau     = 3001;
  recKau        = 3002;
  recKauMin     = 3003;
  recKauMax     = 3004;
  recEd         = 3005;
  recGrPokaz    = 3006;

  // наименования
	reCodePokaz   = 4001;
	reNamePokaz   = 4002;

	// ограничения и подцепки
  reNoBound          = 5000;

	// быстрая навигация
	reByCodePokaz      = 6001;
	reByNamePokaz      = 6002;

	// параметры
	reCodeParam        = 7101;
	reNameParam        = 7102;

end

