const


  // числа
  reSpeed       = 0001;
  redPunrDop    = 0002;
  redPunpDop    = 0003;
  reSumAvt      = 0004;

  // строки
  resPunrDop    = 1001;
  resPunpDop    = 1002;
  resPList      = 1003;

  // Даты
  redPunrBeg    = 2001;
  redPunrEnd    = 2002;
  redPunpBeg    = 2003;
  redPunpEnd    = 2004;

  // Время
  retPunrBeg    = 3001;
  retPunrEnd    = 3002;
  retPunrDop    = 3003;
  retPunpBeg    = 3004;
  retPunpEnd    = 3005;
  retPunpDop    = 3006;

  // ссылки
  rewTable      = 4001;
  reTiDk        = 4002;
  recDoc        = 4003;
  recDoc1       = 4004;
  recDoc2       = 4005;
  recOrgAvt     = 4006;
  recMarAvt     = 4007;
  recSpeed      = 4008;
  recTipOtg     = 4009;
  recShipment   = 4010;
  recPunktR     = 4011;
  recPunrOrg    = 4012;
  recPunrMet    = 4013;
  recPunktP     = 4014;
  recPunpOrg    = 4015;
  recPunpMet    = 4016;
  recValAvt     = 4017;
  recPList      = 4018;
  recDriver     = 4020;
  retransp      = 4021;
  recTransp     = 4022;
  recTransp1    = 4023;
  recTransp2    = 4024;
  recTransp3    = 4025;


  reNoBound     = 5000;

  reByDriver    = 5001;
  reByTransp    = 5002;
  reByTablDoc   = 5003;
  reByTablDoc1  = 5004;

/*#ifDef Gal9_1
  reByTablDocDescr = 5005;
  reByTablDocDesGr = 5006;
#end   */

  reGoTTNDoc    = 5101;


  reDriverParam = 10001;
  reTranspParam = 10002;
  reTiDKParam   = 10003;
  reWTABLEParam = 10004;
  recDocParam   = 10005;
  recDoc1Param  = 10006;

/*#ifDef Gal9_1
  reDescrParam  = 10007;
  reDesGrParam  = 10007;
#end     */

  reNew    = 5100;
  reDelCur = 5201;
end
