const
  // числа
  reKoef   =  1;
  reSkid   =  2;

  // Даты
  // reStartDate   = 1000;
  // reEndDate     = 1001;

  rePrMC     = 2000;
  recMCUsl   = 2001;
  reAkt      = 2002;
  rePr       = 2003;
  reDiskret  = 2004;
  recKatEd   = 2005;
  recf_Koef  = 2006;

  reNAME       = 3000;
  rebKOD       = 3001;
  reABBR       = 3002;

  reNoBound     = 4000;
  reByResource  = 4001;
	reByBarKod    = 4002;
	reByResourceAkt = 4003;

  reQuicklyAct  = 4011;
  reQuicklyPr   = 4012;


  reTyResParam  = 6001;
  reCoResParam  = 6002;
	reBarKodParam = 6003;
	reAktParam    = 6004;


  reResourceType = 10001;

end

