const

  redTo      = 1001;

  // строки
  reName     = 2001;
  reKod      = 2002;
  reTel      = 2003;

  // ссылки
  recPersons   = 3001;
  recSkl       = 3002;

  reisArch     = 4001;

  reNoBound        = 5000;
  reBySkl          = 5001;
  reByPersons      = 5002;

  // быстрая навигация
  reByName        = 6001;
  reByKod         = 6002;

  // вставка и удаление записи
  reDeleteCurrent = 6101;
  reInsertRecord  = 6102;

  // параметры
  reNameParam      = 7101;
  reKodParam       = 7102;
  recSklParam      = 7103;
  recPersonsParam  = 7104;

end
