const
  // числа
  reKol          = 01;
  rePrice        = 02;
  reSumNDS       = 04;
	reSumma        = 05;

  // строки
  reNpp          = 101;

	// целые
  reSpDocsTiDk   = 1001;

  // ссылки
  rePrMC         = 3001;
  recMCUSL       = 3002;
  recOtpED       = 3003;
  recVAL         = 3004;
  recPriceLs     = 3005;
  recDog         = 3006;

  reNoBound       	 	= 4000;
  reTieToDogovor  		= 4001;
	reTieToDogovorMcUsl = 4002;
  reIsValid 					= 4003;
	reDeleteSpDoc       = 4004;

  reDogovorParam  = 5001;
	rePrMcUslParam  = 5002;
	reMcUslParam 		= 5003;
	reTypeDocParam 	= 5004;
	reDeleteSpDocVisual = 5005;
	reDeleteSpDocNrec   = 5006;

end

