const
  reField01    = 01;
  reField02    = 02;
  reField03    = 03;
  reField04    = 04;
  reField05    = 05;
  reField06    = 06;
  reField07    = 07;
  reField08    = 08;
  reField09    = 09;
  reField10    = 10;
  reField11    = 11;
  reField12    = 12;
  reField13    = 13;
  reField14    = 14;

  reStartDate     = 1000;
  reEndDate       = 1001;
  reRecomDate     = 1002;
  reStartDateFact = 1003;
  reEndDateFact   = 1004;
	reStartDateTime = 1005;
  reEndDateTime   = 1006;
	reStartDateTimeFact = 1007;
  reEndDateTimeFact   = 1008;

  rePrior       = 2000;
  reStatus      = 2001;
  reTemplate    = 2002;
  reVidNum      = 2003;
  rePrMc        = 2004;
  reIzd         = 2005;
  reMnPlan      = 2006;
  rePayMent     = 2007;
  reRazr        = 2008;
  reCodTar      = 2009;
  reTypeIzd     = 2010;
  recOtpEd      = 2101; // выбились из порядка, а что делать...
  reSpMnPlan    = 2102;

  reRole1       = 2011;
  reRole2       = 2012;
  reRole3       = 2013;
	reRole8       = 2014;
  reRole9       = 2015;

  reCode1       = 2021;
  reCode2       = 2022;
  reCode3       = 2023;
	reCode8       = 2024;
  reCode9       = 2025;

  reValue1_SpMnPl = 2031;
  reValue2_SpMnPl = 2032;
  reValue3_SpMnPl = 2033;
	reValue8_SpMnPl = 2034;
  reValue9_SpMnPl = 2035;

  reRepRole1    = 2041;
  reRepRole2    = 2042;
  reRepRole3    = 2043;
  reRepRole4    = 2044;

  reRepCode1    = 2051;
  reRepCode2    = 2052;
  reRepCode3    = 2053;
  reRepCode4    = 2054;

  reRepValue1   = 2061;
  reRepValue2   = 2062;
  reRepValue3   = 2063;
  reRepValue4   = 2064;

  reSpMnPlNumber  = 3001;

  reReserv01 = 3010;
  reReserv02 = 3011;
  reReserv03 = 3012;
  reReserv04 = 3013;
  reReserv05 = 3014;
  reReserv06 = 3015;

	reMnAnal 	 = 3016;

  reNoBound       = 4000;
  reToPlan        = 4001;
  reToPlanAn      = 4002;
  reToSpMnPlan    = 4003;
  reToSpMnPlanAn  = 4004;
	reToWayAccouMC  = 4005;

  reToRepAn1     = 4011;
  reToRepAn12    = 4012;
  reToRepAn123   = 4013;
  reToRepAn1234  = 4014;

  reGoRepAn1     = 4021;
  reGoRepAn12    = 4022;
  reGoRepAn123   = 4023;
  reGoRepAn1234  = 4024;
	reGoTemplAn    = 4025;

  reGoModeNew    = 4051;

  reDeleteCurrent = 4052;
  reInsertRecord  = 4053;
	reIsValid				= 4054;
  reInsertRecordPeriod  = 4055;

  rePlanParam     = 5000;
  reSpMnPlanParam = 5001;
  reKolAnParam    = 5002;
	reWayAccouParam = 5003;
	reTypeObjParam  = 5004;
	reObjParam			= 5005;
	reTemplateParam = 5006;
	reNumAnParam    = 5007;
	reRepCodeParam  = 5008;
	reRepValParam   = 5009;

  reRepCode1Param  = 5011;
  reRepCode2Param  = 5012;
  reRepCode3Param  = 5013;
  reRepCode4Param  = 5014;
  reRepVal1Param   = 5016;
  reRepVal2Param   = 5017;
  reRepVal3Param   = 5018;
  reRepVal4Param   = 5019;
  reModeParam      = 5020;


  reStatusPlan = 6000;
  reStatusZakaz = 6001;
  reStatusNeedMt = 6002;
end
