const

	// ссылки
	recTarifN = 2000;
	recKlRec  = 2001;
	recKlRec1 = 2002;
	recKlRec2 = 2003;
	recOrg    = 2004;
	recTrGr01 = 2005;
	recTrGr02 = 2006;
	recTrGr03 = 2007;
	recTrGr04 = 2008;
	recTrGr07 = 2009;

	// числа
	reKlRec  = 3000;
	reTrGr01 = 3001;
	reTrGr02 = 3002;
	reTrGr03 = 3003;
	reTrGr04 = 3004;
	reTrGr05 = 3005;
	reTrGr11 = 3006;
	reTrGr12 = 3007;
	reTrGr13 = 3008;
	reTrGr14 = 3009;
	reTrGr15 = 3010;
	reTrGr16 = 3011;
	reTrGr17 = 3012;
	reTrGr18 = 3013;

	// строки
	resKlRec  = 4000;
	resKlRec1 = 4001;

	// даты
	reDatBeg  = 5000;
	reDatEnd  = 5001;

	// параметры
	recTarifNParam = 6000;
	recKlRecParam  = 6001;
	recKlRec1Param = 6002;
	recKlRec2Param = 6003;
	reDatBegParam  = 6004;
	reDatEndParam  = 6005;

	// ограничения
	reNoBound               = 7000;
	reByTarifN              = 7001;
	reByTarifNObject        = 7002;
	reByTarifNObjectS       = 7003;
	reByTarifNObjectSDatBeg = 7004;
	reByTarifNObjectSDatEnd = 7005;

end
