const
  reSize         = 0001;
  reSizeRab      = 0002;

  redBeg         = 1001;
  redEnd         = 1002;

  reAbbr         = 2001;
  reCode         = 2002;
  reLevelCode    = 2003;
  reName         = 2004;

  reAttr         = 3001;
  recMain        = 3002;
  recNode        = 3003;
  recPrev        = 3004;
  recTPer        = 3005;
  reFlags        = 3006;
  reisLeaf       = 3007;
	reTBeg         = 3008;
	reTEnd         = 3009;

  reNoBound      = 4000;
  reByTPer       = 4001;
  reByNode       = 4002;
  reByMain       = 4003;
	reByTypeBeg    = 4004;
	reByTypeBegEnd = 4005;

  reNextPeriod   = 4101;
  rePrevPeriod   = 4102;

  reTPerParam    = 5001;
  reNodeParam    = 5002;
  reMainParam    = 5003;


  reFpTPerConst  = 6001;
end

