const

  // даты
  redAlign         = 1001;
  redBeg           = 1002;

  // строки
  reLevelCode      = 2001;
  reCode           = 2002;
  reName           = 2003;

  // ссылки
  recNode          = 3001;
  reEdIzm          = 3002;
  reisLeaf         = 3003;
  reLenPer         = 3004;
  reParts          = 3005;
  reSysCode        = 3006;
  reTypeAlign      = 3007;
  reTypePer        = 3008;
  reWeekDay        = 3009;


  reNoBound        = 4000;

end

