const

	rewVidDoc       = 100;
	retMC_Old       = 101;
	retMC_New       = 102;

	redtEnd         = 200;
	redtBeg         = 201;
  retmZam         = 202;
	redtZam         = 203;
  redLastDate     = 204;
  retmLastTime    = 205;


	reKol_Old       = 300;
	reKol_New       = 301;

	recDocCode      = 400;
	recMC_Old       = 401;
	recParty_Old    = 402;
	recSpLineO      = 403;
	recEd_Old       = 404;
	recMC_New       = 405;
	recParty_New    = 406;
	recSpLineN      = 407;
	recEd_New       = 408;
	recNoteBene     = 409;
	rewTypeDoc_     = 410;


	reTypePC        = 2000;
  rePC            = 2001;

  reNoBound       = 3000;
  reByTypePC      = 3001;
  reByTypePCcPrEd = 3002;
	reTieToKatSopr  = 3003;
	reTieToNoteBene = 3004;
	reTieToDoc 			= 3005;

  reTypePCParam   = 4000;
  reTypePCParam1  = 4001;

	recNoteBene_    = 5000;
  recKatSopr_     = 5001;
  rewVidDoc_      = 5002;
	recDoc_					= 5003;

end

