const
  reStartDate     = 1000;
  reEndDate       = 1001;
  // reRecomDate     = 1002;
  reStartDateFact = 1003;
  reEndDateFact   = 1004;
	reStartDateTime = 1005;
  reEndDateTime   = 1006;
	reStartDateTimeFact = 1007;
  reEndDateTimeFact   = 1008;


  rePrior       = 2000;
  reStatus      = 2001;
  reTemplate    = 2002;
  rePrMc        = 2003;
  reIzd         = 2004;
  reMnPlan      = 2005;
  rePayMent     = 2006;
  reRazr        = 2007;
  reCodTar      = 2008;
  reTypeIzd     = 2009;
  recOtpEd      = 2010;

  reRole1       = 2011;
  reRole2       = 2012;
  reRole3       = 2013;
  reRole4       = 2014;
  reRole5       = 2015;

  reStateLine   = 2016;
  reAnNum       = 2017;
  rePosFilial   = 2018;

  reCode1       = 2021;
  reCode2       = 2022;
  reCode3       = 2023;
	reCode4       = 2024;
  reCode5       = 2025;

  reValue1_SpMnPlan = 2031;
  reValue2_SpMnPlan = 2032;
  reValue3_SpMnPlan = 2033;
	reValue4_SpMnPlan = 2034;
  reValue5_SpMnPlan = 2035;

	reSpMnPlan    = 2036;

  reDateStartBounds = 2037;
  reDateEndBounds   = 2038;

  reLineNum     = 3000;

  reNoBound       = 4000;
  reToPlan        = 4001;
  reToPlanIzd     = 4002;
  reDeleteCurrent = 4003;
  reInsertRecord  = 4004;
	reToSpPlan      = 4005;


  rePlanParam     = 5000;
  rePrMcParam     = 5001;
  reIzdParam      = 5002;
	reSpPlanParam   = 5003;

  reStatusPlan = 6000;
  reStatusZakaz = 6001;
  reStatusNeedMt = 6002;

  reAncMnPlan = 7000;
  reAnwKodGr1 = 7001;
  reAnwKodGr2 = 7002;
  reAnwKodGr3 = 7003;
  reAncAnVal1 = 7004;
  reAncAnVal2 = 7005;
  reAncAnVal3 = 7006;
  reByAn1     = 7007;
  reByAn2     = 7008;
  reByAn3     = 7009;
  reByObjAn1AndDates = 7010;
end
