const

  reStatus        = 101;
  reNum           = 102;
	reRazryad       = 103;

  reStartDateTime = 1000;
  reEndDateTime   = 1001;

	reDatePotr      = 1501;

  reRsvOper       = 2000;
  reSmena         = 2001;
  reWrk           = 2002;
  reOper          = 2003;

  reNoBound          = 3000;
  reByRsvOperNum     = 3001;
	reByRsvOperNumDate = 3002;
	reByRsvOperDateSm  = 3003;
	reByRsvOperDate    = 3004;
	reByDate           = 3005;
	reBySysOplDate     = 3006;

	recRsvOperParam = 4000;
	reNumParam      = 4001;
	reDateBegParam  = 4002;
	reDateEndParam  = 4003;
	recSysOplParam  = 4004;
	reSmenaParam    = 4005;

end

