const
	// числа
		// Double
  reParQT     = 1000;
  rePartyQT   = 1001;

	reParQTad1  = 1002;
	reParQTad2  = 1003;
	reParQTad3  = 1004;
	reParQTad4  = 1005;
	reParQTad5  = 1006;

		// Word
	reParQTaw1  = 1501;
	reParQTaw2  = 1502;
	reParQTaw3  = 1503;
	reParQTaw4  = 1504;
	reParQTaw5  = 1505;
	reParQTaw6  = 1506;
	reParQTaw7  = 1507;
	reParQTaw8  = 1508;
	reParQTaw9  = 1509;
	reParQTaw10 = 1510;

	// даты
	reDateStart  = 2000;

	reParQTadt1  = 2001;
	reParQTadt2  = 2002;
	reParQTadt3  = 2003;
	reParQTadt4  = 2004;
	reParQTadt5  = 2005;

	// ссылки
  recKPN_Hdr   = 3000;
  reCodePar    = 3001;
	recED        = 3002;

	reParQTac1   = 3003;
	reParQTac2   = 3004;
	reParQTac3   = 3005;
	reParQTac4   = 3006;
	reParQTac5   = 3007;
  reParQTac6   = 3008;
	reParQTac7   = 3009;
	reParQTac8   = 3010;
	reParQTac9   = 3011;
	reParQTac10  = 3012;

 // ограничения
	reNoBound     = 4000;
	reToNorm      = 4001;
	reToCodePar   = 4002;
	reDateStart_  = 4003;
	recKPN_Hdr_   = 4005;
  reCodePar_    = 4006;
	recED_				= 4007;
	reParQT_ 			= 4008;
	rePartyQT_		= 4009;

 // добавление/удаление записи
	reDeleteCurrent = 5000;
	reInsertRecord  = 5001;

	end
