const

  // числа (double)
  reDpPokaz1    = 1001;
  reDpPokaz2    = 1002;
  reDpPokaz3    = 1003;

  // числа (word)
  reWhatIs   = 1501;
  reState    = 1502;
	reTip_Make = 1503;
	reDpPokaz8 = 1504;
	reDpPokaz9 = 1505;
  // времена начинать с 2001

  // даты
  reActionBeg = 2501;
  reActionEnd = 2502;
	reOrgFrom   = 2503;
	reOrgTo     = 2504;
	reDriTo     = 2505;
	reDriFrom   = 2506;
	reLastDvi   = 2507;

  // ссылки
  recBack     = 3001;
  recPutList  = 3002;
  recDriver   = 3003;
  recPersons  = 3004;
  recVehicle  = 3005;
  recWayDoc   = 3006;
  recCountryP = 3007;
  recCountryB = 3008;
  recPunkt    = 3009;
  recOrg      = 3010;
  recOrg_From = 3011;
  reDpPokaz4  = 3012;
  reDpPokaz6  = 3013;
  reDpPokaz7  = 3014;
	recTrlMem   = 3015;

  // наименования
  renDoc     = 4001;
	renDoc_Rec = 4002;
	reNotes    = 4003;
	reTip_Doc  = 4004;
	reNom_Doc  = 4005;

  // ограничения и подцепки
  reNoBound    = 5000;
	reToBounds02 = 5001;
	reToBounds03 = 5002;
	reToBounds04 = 5003;
	reToBounds05 = 5004;
	reToBounds06 = 5005;
	reToBounds07 = 5006;
	reToBounds08 = 5007;
	reToBounds09 = 5008;
	reToBounds10 = 5009;
	reToBounds11 = 5010;
	reToBounds12 = 5011;

  // быстрая навигация

  // параметры
	renDocParam      = 7001;
	reNom_docParam   = 7002;
	renDoc_RecParam  = 7003;
	reTip_MakeParam  = 7004;
	reTip_docParam   = 7005;
	recBackParam     = 7006;
	recPutListParam  = 7007;
	recDriverParam   = 7008;
	recVehicleParam  = 7009;
	recPersonsParam  = 7010;
	recWayDocParam   = 7011;
	recPunktParam    = 7012;
	recOrg_FromParam = 7013;
	reWhatIsParam    = 7014;

end

