const

  refKol    = 0001;

  reDescr   = 1001;

  recSlit   = 2001;
  recPrih   = 2002;
  recRash   = 2003;

  rewFixed  = 3001;

  redPrih   = 4001;
  redRash   = 4002;

  reNoBound = 5000;
  reBySlit  = 5001;
  reByPrih  = 5002;
  reByRash  = 5003;

  reNew     = 5101;
  reDelCur  = 5102;

  reLookForLink = 5201;

  recSlitParam = 7001;
  recPrihParam = 7002;
  recRashParam = 7003;
  refKolParam  = 7004;
	refKolRashParam  = 7005;

end

