const
  // числа (double)
  reDop4 = 1001;
  reDop5 = 1002;
  reDop6 = 1003;
	reKUM  = 1004;

	// ссылки
	recOrg     = 2000;
	recPodr    = 2001;
	recPerson  = 2002;
	recLschet  = 2003;
	recTransp  = 2004;
	recPutLst  = 2005;
	reDop7     = 2006;
	reDop8     = 2007;
	reDop9     = 2008;
	recKvlUrAv = 2009;

  // даты
  reStagVd = 2501;
  reDatPl  = 2502;
	reDatBeg = 2503;
	reDatEnd = 2504;

	// числа (word)
	reTabn     = 3000;
	reKlassv   = 3001;
	reTipTC    = 3002;
	reNomKom   = 3003;
	reDop1     = 3004;
	reDop2     = 3005;
	reDop3     = 3006;
	reTypePers = 3007;

	// строки
	reName    = 4000;
	reNudov   = 4001;
	reKatgA   = 4002;
	reKatgB   = 4003;
	reKatgC   = 4004;
	reKatgD   = 4005;
	reKatgE   = 4006;
	reNpl     = 4007;
	reStrTabn = 4008;


	// параметры
	recOrgParam     = 6000;
	recPersonParam  = 6001;
	recPodrParam    = 6002;
	recLschetParam  = 6003;
	reNameParam     = 6004;
	reStrTabnParam  = 6005;
	reTypePersParam = 6006;
	reTipTCParam    = 6007;
	reTabNParam     = 6008;


	// ограничения
	reNoBound             			 = 7000;
	reByOrg                      = 7001;
	reByOrgTipTC                 = 7002;
	reByOrgTipTCTypeP            = 7003;
	reByOrgTipTCTypePName        = 7004;
	reByOrgTipTCTypePTabN        = 7005;
	reByOrgTipTCTypePTabNStr     = 7006;
	reByOrgTipTCPodr             = 7007;
	reByOrgTipTCPodrTypePTabNStr = 7008;
	reByOrgTipTCPodrTypePName    = 7009;
	reByLschet                   = 7010;
	reByPerson                   = 7011;
end
