const

  // числа
  reDistantion = 1001;
  reDistCity   = 1002;
  reDistWay1   = 1003;
  reDistWay2   = 1004;
  reDistWay3   = 1005;
  reDistMoun   = 1006;
  reSumUsl     = 1007;
  reSumUslVal  = 1008;
  reFkTimeStop = 1009;
  reNpTimeMove = 1010;
  reFkTimeMove = 1011;
  reNpTimePg   = 1012;
  reFkTimePg   = 1013;
  reNpTimeRz   = 1014;
  reFkTimeRz   = 1015;
  reProbegAll  = 1016;
  reProbegGr   = 1017;
  reNpGruzTn   = 1018;
  reFkGruzTn   = 1019;
  reNpVir      = 1020;
  reFkVir      = 1021;
  reNpVirVal   = 1022;
  reFkVirVal   = 1023;
  reProbegGrPri = 1024;
  reGruzTnPri   = 1025;
  reGruzTnKmPri = 1026;
  reGruzTnKm   = 1027;
  reSNalogs    = 1028;
  reDWork2     = 1029;
  reDWork3     = 1030;
  reDWork4     = 1031;
  reDWork5     = 1032;
  reTimeHoli   = 1033;
  reTimeWeek   = 1034;
  reTimeRep    = 1035;
  reTimeStVd   = 1036;
  reTimeStNoVd = 1037;
  reTimeDn     = 1038;
  reTimePri    = 1039;
  reTimeNoPri  = 1040;
  reTimeRepVd  = 1041;
  reTimeRepNoVd = 1042;
  reNar        = 1043;
  reNpTimeStop = 1044;
  rework11     = 1045;
  rework12     = 1046;
  rework13     = 1047;
  rework14     = 1048;
  rework15     = 1049;
  rework16     = 1050;
  rework17     = 1051;
  rework18     = 1052;
  rework19     = 1053;

  reKFormPl    = 1501;
  reNpDvi      = 1502;
  reNpKolEz    = 1503;
  reFkKolEz    = 1504;
  reStMain     = 1505;
  reTipTC      = 1506;

  // времена
  reExitCh     = 2001;
  reReturnCh   = 2002;
  reNpExitCh   = 2003;
  reNpReturnCh = 2004;
  reTimeFrom   = 2005;
  reTimeTo     = 2006;

  // даты
  reNpExitDn   = 2501;
  reNpReturnDn = 2502;
  reExitDn     = 2503;
  reReturnDn   = 2504;
  reDPrice     = 2505;
  reDOpr       = 2506;
  reDFrom      = 2507;
  reDTo        = 2508;

  // ссылки
  recKatSopr   = 3001;
  recPodrFrom  = 3002;
  recOrg       = 3003;
  recGruzFrom  = 3004;
  recGruzTO    = 3005;
  recOrgAvt    = 3006;
  recValut     = 3007;
  recKatUsl    = 3008;
  recMarAvt    = 3009;
  recPutLst    = 3010;
  recKatZak    = 3011;
  recPodr      = 3012;
  recPodrAvt   = 3013;
  recKnDriver  = 3014;
  recNote      = 3015;
	recTransp    = 3016;
	recPodrTo    = 3017;
	recVal       = 3018;
	repunkt      = 3019;
	repunktp     = 3020;
	recMarka     = 3021;
	recTTN       = 3022;
	recResHr     = 3023;
	recSpOtgOrd  = 3024;
	recKompLst   = 3025;
	recTipTC     = 3026;
	recTransp1   = 3027;
	recTransp2   = 3028;
	recTransp3   = 3029;
	recWork1     = 3030;
	recWork2     = 3031;
	recWork3     = 3032;
	recWork4     = 3033;
	recProff     = 3034;
	recDopAvt    = 3035;
	recTipWrk    = 3036;
	recTipPut    = 3037;

  // наименования
  reNomZak     = 4001;
  reNSopr      = 4002;
  reDescr      = 4003;
  reDesGr      = 4004;

  // ограничения и подцепки
  reNoBound    = 5000;
  reToPutLst   = 5001;
  reToTypeZak  = 5002;
	reToKatZak   = 5003;

  // быстрая навигация
  reByNomZak   = 6001;

	// создание и удаление
	reInsertRecord = 6100;
  reDuplRecord   = 6101;
  rePersonsParam = 6102;
  rePointFromParam = 6103;
  rePointToParam   = 6104;
  reDateFromParam  = 6105;
  reDateToParam    = 6106;
  rePLCreateParam   = 6107;

  // параметры
  rePutLstParam     = 7101;
  reTypeZakParam    = 7201;
  reNomZakParam     = 7301;
  reTranspParam			= 7401;
  reMarAvtParam			= 7501;
  reOrgParam				= 7601;
	reTipTCParam      = 7701;
	reKatZakParam     = 7801;


end
