const


  // числа
  rePickKol    = 0001;
	rePickKol1 	 = 0002;

  // Даты

  // ссылки
  recRec       = 2001;
  rewList      = 2002;
	recRec1      = 2003;

  // наименования

  reNoBound     = 4000;

  reBywList     = 4001;
	reBywListcRec = 4002;

  reNew         = 5001;
  reDelCur      = 5002;
  reDelwList    = 5003;

  reLookForcRec = 6001;
	reLookForcReccRec1 = 6002;

  rewListParam     = 10001;
  recRecParam      = 10002;
  rewPickKolParam  = 10003;
	rewPickKol1Param  = 10004;
	recRec1Param      = 10005;
end

