const

  // числа (double)
  reLinNrm    = 1001;
  reChsNrm    = 1002;
  reStoim     = 1003;
  reStoimVal  = 1004;
  reKoffNGsm2 = 1005;
  reKoffNgsm3 = 1006;
  reOneEz     = 1007;
  reSpObr     = 1008;
  reDopMas    = 1009;
  reSpWrk     = 1010;
  reUnload    = 1011;
  reWrkDrv    = 1012;
  reNlProbeg  = 1013;
  reLnmEzd    = 1014;
  reDop1      = 1015;
  reDop2      = 1016;
  reDop3      = 1017;


  // числа (word)
  reWhatIs = 1501;
  reAimGsm = 1502;


  // времена начинать с 2001


  // даты
  reDatBeg = 2501;
  reDatEnd = 2502;


  // ссылки
  rectipTex     = 3001;
  recMarka      = 3002;
  recToplivo    = 3003;
  recMarAvt     = 3004;
  recMarRel_Beg = 3005;
  recMarRel_End = 3006;
  recWayPath    = 3007;
  recWorkAvt    = 3008;
  recVal        = 3009;
  reKoffNGsm1   = 3010;
  recTransp     = 3011;
  recVidGsm     = 3012;
  recSpecOb     = 3013;
  recKatUsl     = 3014;


  // наименования
  reNm = 4001;


  // ограничения и подцепки
  reNoBound    = 5000;
	reToBounds08 = 5001;
	reToBounds09 = 5002;
	reToBounds10 = 5003;
	reToBounds11 = 5004;
	reToBounds12 = 5005;
	reToBounds13 = 5006;

  // быстрая навигация

  // параметры
	reWhatIsParam   = 7001;
	recMarAvtParam  = 7002;
	recTranspParam  = 7003;
	recVidGsmParam  = 7004;
	recSpecobParam  = 7005;
	recMarkaParam   = 7006;
	recToplivoParam = 7007;

end

