const

  // числа (double)
  reSpeedExi     = 1001;
  reSpeedRet     = 1002;
  reProbegAll    = 1003;
  reProbegTam    = 1004;
  reProbegV      = 1005;
  reProbegGr     = 1006;
  reProbegGrPri  = 1007;
  reProbegWrk    = 1008;
  reProbegNullSt = 1009;
  reProbegNullRc = 1010;
  reVolWrk       = 1011;
  reGruzTn       = 1012;
  reGruzTnPri    = 1013;
  reGruzTnKm     = 1014;
  reGruzTnKmPri  = 1015;
  reNpVirVal     = 1016;
  reFkVirVal     = 1017;
  reTimeAll      = 1018;
  reTimeMove     = 1019;
  reTimeStop     = 1020;
  reTimeRep      = 1021;
  rePrPrC        = 1022;
  reTimeEngine   = 1023;
  reTimeHeat     = 1024;
  reTimeSpec     = 1025;
  reTimeLoad     = 1026;
  reTimePg       = 1027;
  reTimeRz       = 1028;
  reTimeDef      = 1029;
  reKolEz        = 1030;
  reSumUsl       = 1031;
  refkVir        = 1032;
  reWeight0      = 1033;
  reGruzPod0     = 1034;
  reVolume0      = 1035;
  reVolume1      = 1036;
  reVolume2      = 1037;
  reProbeg2      = 1038;
  reKoffProbeg   = 1039;
  reTimeNorma    = 1040;
  reTimeKar      = 1041;
  reVolumeAll    = 1042;
  rePok1RB       = 1043;
  rePok2RB       = 1044;
  rePok3RB       = 1045;
  rePok4RB       = 1046;
  rePok5Ino      = 1047;
  rePok5RB       = 1048;
  rePok1CNG      = 1049;
  rePok2CNG      = 1050;
  rePok3CNG      = 1051;
  rePok1Ino      = 1052;
  rePok2Ino      = 1053;
  rePok3Ino      = 1054;
  reDpPokaz1     = 1055;
  reDpPokaz2     = 1056;
  reDpPokaz3     = 1057;
  reDpPokaz4     = 1058;
  reDpPokaz5     = 1059;
  reDpPokaz6     = 1060;
  reDpPokaz7     = 1061;
  reTimeHoli     = 1062;
  reTimeWeek     = 1063;
  reTimeStVd     = 1064;
  reTimeDn       = 1065;
  reTimePri      = 1066;
  reTimeNoPri    = 1067;
  reTimeSvUr     = 1068;
  reTimeRepVd    = 1069;
  reKolZa        = 1070;
  renpVir        = 1071;
  reKofN         = 1073;
  reWeight       = 1074;
  reGruzPod      = 1075;
  reGruzPodAll   = 1076;
  reVolume       = 1077;
  reWeight1      = 1078;
  reWeight2      = 1079;
  reProbeg1      = 1080;
  rePok4CNG      = 1081;
  rePok5CNG      = 1082;
  rePok4Ino      = 1083;
  reTimeStNoVd   = 1084;
  reTimeRepNovd  = 1085;
  reTimeSovm     = 1086;

  // числа (word)
  reKFormPl  = 1501;
  reTipLst   = 1502;
  reStatPl   = 1503;
  reTipUsl   = 1504;
  reNomSmena = 1505;
  reVidTC    = 1506;
  rePrSdan   = 1507;
	reGruzPod1  = 1508;
	reGruzPod2  = 1509;
	reDpPokaz11 = 1510;
	reDpPokaz12 = 1511;
	reDpPokaz13 = 1512;

  // времена
  reExitCh        = 2001;
  reReturnCh      = 2002;
  reReal_ExitCh   = 2003;
  reReal_ReturnCh = 2004;
  reSdanCh        = 2005;

  // даты
  reDatPl         = 2501;
  reDatObr        = 2502;
  reExitDn        = 2503;
  reReturnDn      = 2504;
  reReal_ExitDn   = 2505;
  reReal_ReturnDn = 2506;
  reSdanDn        = 2507;
	reDatRas        = 2508;

  // ссылки
  recTipPut      = 3001;
  recOrgAvt      = 3002;
  recPol         = 3003;
  recVal         = 3004;
  recTransp      = 3005;
  recMarAvt      = 3006;
  recReceive     = 3007;
  recSdal        = 3008;
  recGrafikTC    = 3009;
  recPutLst      = 3010;
  recResHr       = 3011;
  recTrlMem      = 3012;
  recStKompl     = 3013;
  recKompLst     = 3014;
  recOrgTC       = 3015;
  recNote        = 3016;
  recTransp_Main = 3017;
  recHozOper     = 3018;
  recWayItem     = 3019;
  recPaketPl     = 3020;
	recBack        = 3021;
	recBack1       = 3022;
	recBack2       = 3023;
	reDpPokaz8     = 3024;
	reDpPokaz9     = 3025;
	reDpPokaz10    = 3026;

  // наименования
  reNPL      = 4001;
  reNSeria   = 4002;
  reDescr    = 4003;
  reDesGr    = 4004;
	reNomer    = 4005;
	reGarNomer = 4006;
	reDescrPr  = 4007;
	reDesGrPr  = 4008;
	reDescrVd  = 4009;
	reDesGrVd  = 4010;
	reDescrTk  = 4011;
	reDesGrTk  = 4012;
	reSortName = 4013;

  // ограничения и подцепки
  reNoBound    = 5000;
  reToTransp   = 5001;
  reToKFormPl  = 5002;
  reToStatPl   = 5003;

  // быстрая навигация
  reByNPL      = 6001;

  // параметры
  reTranspParam     = 7101;
  reKFormPlParam    = 7201;
  reStatPlParam     = 7301;
  reNPLParam        = 7401;

end

