const

  // строки
  reName    = 2000;

  // ссылки
  reTip     = 3001;
  rewTable  = 3002;
  recRec    = 3003;

  // мемо
  reMem     = 4000;


  reNoBound       = 4000;

  reBywTablecRec  = 4001;
  reByTableRecTip = 4002;

  reBywTablecRecNaby  = 5001;
  reByTableRecTipNaby = 5002;

  reNew    = 5100;
  reNewCur = 5101;
  reDel    = 5200;
  reDelCur = 5201;

  rewTableParam  = 10001;
  recRecParam    = 10002;
  reTipParam     = 10003;

  reTableCodes   = 11000;
end

