const

 reTypeDoc       = 100;
 reNumber        = 101;
 reTypeZam       = 102;
 reState         = 103;

 redBeg          = 200;
 redEnd          = 201;
 redUtv          = 202;

 reName          = 300;
 reContent 			 = 301;

 reReason        = 400;

  reTypePC        = 2000;
  rePC            = 2001;

  reNoBound       = 3000;
  reByTypePC      = 3001;
	reByTypePCcPrEd = 3002;

	reTypePCParam   = 4000;
	reTypePCParam1  = 4001;

end

