const

  // числа (double)
  reKolMect     = 1001;
  reMassa       = 1002;
  reMassa_br    = 1003;
  reKoffGrZk1   = 1004;
  reKoffGrZk2   = 1005;
  reKoffGrZk3   = 1006;
  reKoffGrZk4   = 1007;
  reOilPlot     = 1008;
  reOilTemper   = 1009;
  rePrice       = 1010;
  reVPrice      = 1011;
  reProbeg      = 1012;
  reSpeedLoad   = 1013;
  reSpeedUnLoad = 1014;


  // числа (word)
  reTc_pri = 1501;


  // времена
  renpLoadTime   = 2001;
  renpUnLoadTime = 2002;
  reLoadTime     = 2003;
  reUnLoadTime   = 2004;


  // даты
  renpLoadDate   = 2501;
  renpUnLoadDate = 2502;
  reLoadDate     = 2503;
  reUnLoadDate   = 2504;


  // ссылки
  recKatZak        = 3001;
  recKatMc         = 3002;
  recOtpEd         = 3003;
  recSpSopr        = 3004;
  recPutLst        = 3005;
  recWayItem       = 3006;
  recVal           = 3007;
  recTransp        = 3008;
  recSpSklad       = 3009;
  recWaytemLoad    = 3010;
  recWayitemunLoad = 3011;


  // наименования от 4001

  // ограничения и подцепки
  reNoBound    = 5000;
  reToKatZak   = 5001;
	reToPutLst   = 5002;
	reToKatMC    = 5003;
	reToPLKZ     = 5006;
	reToTipTC    = 5007;

	// быстрая навигация

  // параметры 7101
	reKatZakParam     = 7101;
	rePutLstParam     = 7102;
	reKatMCParam      = 7103;
	reTC_PriParam     = 7104;
	recTranspParam    = 7105;

end

