

  // ***
const
  reKOLSKL =  0001;
  reSUMMA  =  0002;
  reReserv =  0003;
  reSumVal =  0004;
  reVlSkid =  0005;
  reNDS    =  0006;
  reKol    =  0007;
  reKolOpl =  0008;
  reOstKol =  0009;
  rePrice  =  0010;
  reProcUb =  0011;
	reKolOplEx = 0012;

  // Даты
  redDoc      = 1000;
  reSrokRes   = 1001;

  // А строк нет
  // reName  = 2000;
  // reNoDoc = 2001;

  // ссылки
  recBaseDoc = 3000;
  rePrMC     = 3001;
  recMCUSL   = 3002;
  recOtpED   = 3003;
  recParty   = 3004;
  recSpDocs  = 3005;
  recVal     = 3006;

  rePrSkid     = 4001;

  reNpp        = 5001;

  reNoBound     = 6000;

  reByBaseDoc   = 6001;
  reByBaseDocMc = 6002;
  reBySpDocs    = 6003;
	reByPrMcMc    = 6004;

  reBaseDocParam   = 7001;
  rePrMcParam      = 7002;
  recMcUslParam    = 7003;
  reSpDocsParam    = 7004;


  rePrMcConst      = 10001;

end
