const

  reSumma       = 1;
	reSummaVal    = 2;

  reDateSopr		= 1000;
  reDateOpr     = 1001;

  rePerson      = 2000;
  reStatus      = 2001;
  reVal     		= 2002;
  reSaldSrc     = 2003;
  reSrcAn1   		= 2004;
	reSrcAn2   		= 2005;
	reSrcAn3   		= 2006;
	reSrcAn4   		= 2007;
	reSrcAn5  		= 2008;
	reSrcAn6   		= 2009;
	reSrcAn7   		= 2010;
	reSrcAn8   		= 2011;
	reSrcAn9   		= 2012;
	reSrcAn10   	= 2013;
	reSaldTrg     = 2014;
  reTrgAn1   		= 2015;
	reTrgAn2   		= 2016;
	reTrgAn3   		= 2017;
	reTrgAn4   		= 2018;
	reTrgAn5  		= 2019;
	reTrgAn6   		= 2020;
	reTrgAn7   		= 2021;
	reTrgAn8   		= 2022;
	reTrgAn9   		= 2023;
	reTrgAn10   	= 2024;
  reSoprHoz	= 2025;

  reName        = 3000;
  reNumDoc      = 3001;

  reNoBound     = 4000;

  reInfo        = 10000;
end

