const
	//
	//
  reStartDate  = 2000;
  reEndDate    = 2001;
  redBegin     = 2002;
  redEnd       = 2003;
	//
  renRec       = 1;
  recObjParam  = 3001;
  reKindRec    = 3002;
  reCondRec    = 3003;
  reTypeHier   = 3004;
  reTypeNorm   = 3005;
  reTypeNorm1  = 3006;
  reTypePos    = 3007;
  recPos       = 3008;
  reTypeEd     = 3009;
  recOtpEd     = 3010;
  reTypeObj    = 3011;
  recObject    = 3012;
  recVal1      = 3013;
  rewVal1      = 3014;
  rewVal2      = 3015;
	recRoleAn1   = 3016;
	rewKodGr1    = 3017;
	recAnVal1    = 3018;
	recRoleAn2   = 3019;
	rewKodGr2    = 3020;
	recAnVal2    = 3021;
	recRoleAn3   = 3022;
	rewKodGr3    = 3023;
	recAnVal3    = 3024;
	recRoleAn4   = 3025;
	rewKodGr4    = 3026;
	recAnVal4    = 3027;
	recRoleAn5   = 3028;
	rewKodGr5    = 3029;
	recAnVal5    = 3030;
  recSpObjPar  = 3031;
	//
  reKolcPos    = 4001;
  reKolcFact   = 4002;
  redblVal1    = 4003;
  redblVal2    = 4004;
	//
  reNoBound    = 5000;
  reToObjParam = 5001;
	//
  reObjParamP1 = 6001;
end;

