const


  // числа
  // reDogovorSpeed       = 0001;
	reDogovorDirect      = 0001;
	reDogovorTiDk        = 0002;
	reMinDebtsAge        = 0003;
	reMaxDebtsAge				 = 0004;

  // строки
  reDogovorNoDoc       = 1001;
  reDogovorNoDoc_Ext   = 1002;

  // Даты
  reDogovordBeg    = 2001;
  reDogovordDoc    = 2002;
  reDogovordEnd    = 2003;

  // Время
  // reDogovortPunrBeg    = 3001;
  // reDogovortPunrEnd    = 3002;

  // ссылки
  reDogovorcDogovor    = 4001;
  reDogovorcMyOrg      = 4002;
  reDogovorcOrg        = 4003;
	reDogovorcGrPol      = 4004;
	reDogovorcGrOtp      = 4005;
	reUpdateDogovorNrec  = 4006;
	reUpdateDogovorType  = 4007;


  reDogovorNoBound     = 5000;

  reDogovorByDogovor  = 5001;
	reDogovorByKontr    = 5002;
	reDogovorByStatus   = 5003;
	reDogovorByDirect   = 5004;
	reUpdateDoc	        = 5005;

	reDogovorStatusConst = 9001;
  reDogovorDirectConst = 9002;

	reDogovorDogovorParam = 10001;
	reDogovorKontrParam   = 10002;
	reDogovorStatusParam  = 10003;
	reDogovorDirectParam  = 10004;
end

