const
  reMassa     =  1;
  remTara     =  2;
  reSizeX     =  3;
  reSizeY     =  4;
  reSizeZ     =  5;
  reVolume    =  6;
  reClassGr   =  7;
  reZapasMin  =  8;
  reZapasMax  =  9;
  reNormUb    = 10;
  rePercentN  = 11;
  rePricePU   = 12;
  reCenaMC    = 13;
  reMaxProcN  = 14;
  reNalProd   = 15;
  reMAXON     = 16;
  reMAXRN     = 17;
  reMAXORN    = 18;
	reNalNDS    = 19;


  // Даты
  // reStartDate   = 1000;
  // reEndDate     = 1001;

  recGroupMC     = 2000;
  recED          = 2001;
  recMasED       = 2002;
  recResHr       = 2003;
  recType        = 2004;
  recTech        = 2005;
  reBaseDSE      = 2006;
  recDep         = 2007;
  recMCmat       = 2008;
  reRet1         = 2009;
  reRet2         = 2010;
  recGrNal       = 2011;
  recOKP         = 2012;
  recStZatr      = 2013;
  recKaElem      = 2014;
  recMaskMC      = 2015;
  recHashAn      = 2016;
  recSloj        = 2017;
  recUsl         = 2018;
  recDopEd       = 2019;

  reNAME          = 3000;
  reObozn         = 3001;
  reBarKod        = 3002;
  reBarKod2       = 3003;
  reRemMC         = 3004;
  rekGroupMC      = 3005;
  reTNVED         = 3006;
  reMaskName      = 3007;
  reCategory      = 3008;

  reNoBound     = 4000;
  reByName      = 4001;
  reByCode      = 4002;
  reByConstr    = 4003;
  reByGroup     = 4004;
  reByTepmlate  = 4005;
  reByAnalitic  = 4006;

  reGroupParam     = 6001;
  reTemplateParam  = 6002;
  reAnaliticParam1 = 6003;
  reAnaliticParam2 = 6004;
  reAnaliticParam3 = 6005;
  reAnaliticParam4 = 6006;

  // вставка и удаление записи
  reDeleteCurrent = 6101;
  reInsertRecord  = 6102;

  reNameParam    = 7001;
  reCodeParam    = 7002;
  reConstrParam  = 7003;

  reGroup       = 10001;
  reTemplate    = 10002;


end
