const







  // числа
  reKIsp        = 1001;


  // строки
  reName         = 2001;
  reAbbrObjR     = 2002;
  reTexNum       = 2003;
  reNumber       = 2004;
  reInNum        = 2005;

  // строки по ссылке из других таблиц
  reTipObjKod   = 2101;
  reTipObjName  = 2102;
  reKatMarkKod  = 2103;
  reKatMarkName = 2104;
  reEqGroupCode = 2205;
  reEqGroupName = 2206;


  // ссылки
  recVidObj     = 3001;
  recTipObj     = 3002;
  recGrObj      = 3003;
  recKatMark    = 3004;
  recKatPodr    = 3005;
  recKatOS      = 3006;
  recGoods      = 3007;
  recKatOrg     = 3008;
  recPlace      = 3009;
  recGrafik     = 3010;
  recCalendar   = 3011;
  recEqGroup    = 3012;

  // Даты  
  reBirth  = 4001;
  reDateV  = 4002;

  // Мемо
  reMemoR          = 5001;


  reNoBound        = 6000;

  // быстра навигация
  reByName        = 7001;
  reByCode        = 7002;

  // параметры

  reNameParam       = 8101;
  reCodeParam       = 8102;

end

