const

  // строки
  reName     = 1001;
  reKod      = 1002;

  // ссылки
  recType      = 2001;
  recEd        = 2002;
  recStZatr    = 2003;
  recKaElem    = 2004;
  recOwner     = 2005;

  // флаги
  reLKod       = 3001;
  reKind       = 3002;
  rePrMat      = 3003;
  reMethod     = 3004;

  reFlagSum    = 3101;
  reFlagList   = 3501;

  // суммы
  reProcNac    = 4001;
  reMaxON      = 4002;
  reMaxRN      = 4003;
  reMaxORN     = 4004;

  reNoBound    = 5000;
  reByType     = 5001;
  reByOwner    = 5002;
  reByStZatr   = 5003;

  // быстрая навигация
  reByName     = 6001;
  reByKod      = 6002;

  // вставка и удаление записи
  reDeleteCurrent = 6101;
  reInsertRecord  = 6102;

  // параметры
  reNameParam     = 7101;
  reKodParam      = 7102;
  recTypeParam    = 7103;
  recOwnerParam   = 7104;
  recStZatrParam  = 7105;

end
