const

  // числа
  reTipObjRes = 1001;
  reStatus    = 1002;

  // даты
  redDoc     = 2001;
  redLast    = 2002;
  redGarant  = 2003;
  redSertEnd = 2004;

	// времена

  // ссылки
  recMc        = 3001;
  recPodr      = 3002;
  recMol       = 3003;
  recParty     = 3004;
  recObjRes    = 3005;
  recCardTrans = 3006;
  recCardRem   = 3007;
  recCardOS    = 3008;
  recPrForm    = 3009;
  recIzgotov   = 3010;

  // наименования
  reSerial   = 4001;
  reNSeries  = 4002;
  reNSertif  = 4003;
  reNSertOrg = 4004;

	// ограничения и подцепки
  reNoBound            = 5000;
  reBySerial           = 5001;
  reByMC               = 5002;
  reByStatusMC         = 5003;
  reByObjResMC         = 5004;
  reBySlit12           = 5005;
  reBySlit123          = 5006;
  reBySlit1234         = 5007;

  reNew                = 5101;

	// параметры
  recMcParam           = 6001;
  recPodrParam         = 6002;
  recMolParam          = 6003;
  recPartyParam        = 6004;
  recObjResParam       = 6005;

  reTipObjResParam     = 6101;
  reStatusParam        = 6102;

  reSerialParam        = 6201;

  redLastParam         = 6301;
end
