const

  // Hour       : Byte_x03      "Продолж-ть смен:часы",
  // Minut      : Byte_x03      "Продолж-ть смен:мин.",
  // cFunc      : Longint       "Код производственной функции",

  // числа
  revolume   = 1001;
  reSkPrior  = 1002;
  reSmen     = 1003;

  // строки
  reNAME     = 2001;
  reKOD      = 2002;
  reFIO      = 2003;
  recUser    = 2004;
  reAddr     = 2005;
  reTEL      = 2006;
  reFIO_GB   = 2007;

  // ссылки
  reSKLAD      = 3001;
  recResHr     = 3002;
  recGrPodr    = 3003;
  reUchPrc     = 3004;
  reTypeUch    = 3005;
  recPriceL    = 3006;
  recGrafik    = 3007;
  recCalendar  = 3008;
  recMnfStrc   = 3009;
  recOrg       = 3010;
  recRec       = 3011;
  reCode       = 3012;
  recPodr      = 3013;
  reisLeaf     = 3014;
  recMol       = 3015;

  reIntern     = 4001;
  reprSKLAD    = 4002;



  reNoBound        = 5000;
  reByPodr         = 5001;
  reByGrPodr       = 5002;
  reByOrg          = 5003;

  // быстра навигация
  reByName        = 6001;
  reByCode        = 6002;

  // вставка и удаление записи
  reDeleteCurrent = 6101;
  reInsertRecord  = 6102;

  // параметры

  reNameParam       = 7101;
  reCodeParam       = 7102;
  rePodrParam       = 7103;
  reGrPodrParam     = 7104;
  reOrgParam        = 7105;

end
