const

  // числа
	reTypeDoc    = 1001;
	reTypeSpDoc  = 1002;

  // даты

  // ссылки
  recKatSort   = 3001;
  recKatStats  = 3002;
  recDoc       = 3003;
  recSpDoc     = 3004;

  // наименования
  reName       = 4001;
  reCode       = 4002;
	reDescr      = 4003;
	reDesGr      = 4004;

	// ограничения и подцепки
  reNoBound    = 5000;
	reToMc       = 5001;

	// быстрая навигация
	reByCode     = 6001;

	// параметры
	reCodeParam       = 7101;
	rePrMcUslParam    = 7201;
	reMcUslParam      = 7202;

end

