const

  // ссылки
  recSoprDoc = 1001;
  recSpSopr  = 1002;
  recParty   = 1003;
  recPodr    = 1004;
  recMol     = 1005;
  recMc      = 1006;
  recOtpEd   = 1007;
  recVal     = 1008;
  recUKS     = 1009;

  // числа
  rePrice  = 2001;
  reKol    = 2002;
  reKolDop = 2003;
  reVPrice = 2004;

  // ограничения
  reNoBound   = 3000;

  reToSoprDoc = 3001;
  reToSpSopr  = 3002;
  reToMc      = 3003;
  reToPodr    = 3004;
  reToParty   = 3005;

  reInsertRecord = 3006;

  // параметры
  recSoprDocParam = 4001;
  recSpSoprParam  = 4002;
  recMcParam      = 4003;
  recPodrParam    = 4004;
  recPartyParam   = 4005;
  recMolParam     = 4006;
end
