const

  redTo      = 1001;

  // строки
  reName      = 2001;
  reKod       = 2002;
  reAppName   = 2003;

  // ссылки
  recStZatr   = 3001;

  reRezervPrz = 4001;
  reNum       = 4002;
  reIsLeaf    = 4003;

  reNoBound        = 5000;
  reByStZatr       = 5001;

  // быстрая навигация
  reByName        = 6001;
  reByKod         = 6002;

  // вставка и удаление записи
  reDeleteCurrent = 6101;
  reInsertRecord  = 6102;

  // параметры
  reNameParam      = 7101;
  reKodParam       = 7102;
  recStZatrParam   = 7103;

end
