const

	// ссылки
	recMc     = 2000;
	recOtpEd  = 2001;
  recVidGSM = 2002;

	// числа
	rePlot   = 3000;
	reKoff   = 3001;
  reTipRS  = 3002;

	// строки
	resKodVid = 4000;
	resKodGSM = 4001;
  resName   = 4002;
  resTipKG  = 4003;

	// даты
	reDatBeg  = 5000;
	reDatEnd  = 5001;

	// параметры
	recMcParam     = 6000;
	resNameParam   = 6001;
	resKodGSMParam = 6002;
	resKodVidParam = 6003;

	// ограничения
	reNoBound   = 7000;
	reByKatMc   = 7001;
	reByName    = 7002;
	reByKodGSM  = 7003;
	reByKodVid  = 7004;

end
