const

  // числа
	reValueMain   = 1001;
	reValueMin    = 1002;
	reValueMax    = 1003;
	reTable       = 1501;
	reKodGrKau    = 1502;
	reKodGrKauMin = 1503;
	reKodGrKauMax = 1504;

  // даты

	// времена

  // ссылки
  recOwner      = 3001;
  recKatPokaz   = 3002;
  recKatKau     = 3003;
  recKau        = 3004;
  recKauMin     = 3005;
  recKauMax     = 3006;
  recEd         = 3007;
  recGrPokaz    = 3008;

  // наименования
	reCodePokaz   = 4001;
	reNamePokaz   = 4002;

	// ограничения и подцепки
  reNoBound          = 5000;
	reToOwner          = 5001;

	// быстрая навигация
	reByOwnerPokaz     = 6001;
	reByOwnerKatKau    = 6002;

	// параметры
	reTableParam        = 7101;
	recOwnerParam       = 7102;
	recPokazParam       = 7103;
	recKatKauParam      = 7104;

end

