//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика ERP 9.1 - Заработная плата
// Константы статусов участия в расчете у постоянных доплат и удержаний
// Применимо к полям Shtraf.Pometka, Doplata.Pometka
//------------------------------------------------------------------------------

Const
  coActiveRP = '+'; // Shtraf.Pometka, Doplata.Pometka
  coInactiveRP = '-'; // Shtraf.Pometka, Doplata.Pometka
  coArchivedRP = 'AR'; // Shtraf.Pometka
  coFuturePeriodRP = '3';
  coReportPeriodRP = '2'; // Doplata.Pometka
End;

