{
 ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
 บ               ‘ซฎข เ์ : GALDICT " ซ ชโจช  ERP 9.1"                   บ
 บ     โ  แฎงค ญจ๏ 01/02/19                                             บ
 ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
}

{$ifdef __MTtabledef__}
{อออออออออออออ ’ กซจๆ  : Z_ZAR::KRRELSTORN "KRRELSTORN" ออออออออออออออ}
type
  pKRRELSTORN = ^tKRRELSTORN;
  tKRRELSTORN = record   { - KRRELSTORN }
    CKASSA         : Comp;            { CKASSA                                }
    CSPORDER       : Comp;            { CSPORDER                              }
    AVRPRICE       : Double;          { AVRPRICE                              }
  end;
const
  tiKRRELSTORN01         = 0;  { CKASSA(M)                               }

const
  mtKRRELSTORN = 'Z_ZAR::KRRELSTORN';
{$endif __MTtabledef__}
