{
 ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
 บ               ‘ซฎข เ์ : GALDICT " ซ ชโจช  ERP 9.1"                   บ
 บ     โ  แฎงค ญจ๏ 22/02/19                                             บ
 ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
}

{$ifdef __MTtabledef__}
{อออออออออออออ ’ กซจๆ  : Z_ZAR::SPVEDDEP "SPVEDDEP" ออออออออออออออ}
type
  pSPVEDDEP = ^tSPVEDDEP;
  tSPVEDDEP = record   { - SPVEDDEP }
    CLSCH          : Comp;            { CLSCH                                 }
    SUMUD          : Double;          { SUMUD                                 }
    DFORM          : Date;            { DFORM                                 }
  end;
const
  tiSPVEDDEP01           = 0;  { CLSCH(M)                                }

const
  mtSPVEDDEP = 'Z_ZAR::SPVEDDEP';
{$endif __MTtabledef__}
