/*
 ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
 บ                     (c) 04/16/2004 ชฎเฏฎเ ๆจ๏ €€’€                   บ
 บ เฎฅชโ        : €€’€                                                 บ
 บ ‘จแโฅฌ        : ฏฅเ โจขญ๋ฉ ชฎญโใเ                                        บ
 บ ฅเแจ๏        : 8.0                                                       บ
 บ  งญ ็ฅญจฅ    :  ชเฎฎฏเฅคฅซฅญจ๏ คซ๏ เ กฎโ๋ แ ชฎฌฏฎญฅญโฎฉ L_SF (ฏฅ็ โ์)   บ
 บ โขฅโแโขฅญญ๋ฉ : ฎซฅฆ ฉ €ซฅชแฅฉ ฅญญ ค์ฅขจ็                               บ
 ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/
#ifndef _SCHPRINT_INC
#define _SCHPRINT_INC
// parameters
#define PARAM_NDE_EQUAL 'PARAM_NDE_EQUAL'
#define PARAM_SORT_ORG 'PARAM_SORT_ORG'
#define PARAM_PRINT_ZERO 'PARAM_PRINT_ZERO'
#define RU_PISMO250804 'RU_PISMO250804'
#define PARAM_PRINT_NAZN 'PARAM_PRINT_NAZN'
#define PARAM_PRINT_DASH 'PARAM_PRINT_DASH'
// filters
#define FILTER_VAL 'FILTER_VAL'
#define FILTER_ORG 'FILTER_ORG'
#define FILTER_TYPE 'FILTER_TYPE'
#define FILTER_CENTER 'FILTER_CENTER'
#define FILTER_OBJECT 'FILTER_OBJECT'
#define FILTER_MEDIATOR 'FILTER_MEDIATOR'
#define FILTER_CODEOP 'FILTER_CODEOP'
// groupings
#define GROUP_VAL 'GROUP_VAL'
#define GROUP_TYPE 'GROUP_TYPE'
#define GROUP_CENTER 'GROUP_CENTER'
#define GROUP_OBJECT 'GROUP_OBJECT'
#define GROUP_GRDESCR 'GROUP_GRDESCR'
#define PRINT_OBJECT 'PRINT_OBJECT'
#define PRINT_EXCELALLSRC 'PRINT_EXCELALLSRC'
#define PRINT_FORMATEXCEL 'PRINT_FORMATEXCEL'
#define GROUP_KATORG 'GROUP_KATORG'
// fields
#define FIELD_NUM_PARAM 'FIELD_NUM_PARAM'
#define FIELD_FIRST_NUM 'FIELD_FIRST_NUM'
#define FIELD_NUM_PAGE_BK 'FIELD_NUM_PAGE_BK'
#define FIELD_NUM_PAGE_BK_DOP 'FIELD_NUM_PAGE_BK_DOP'
#define FIELD_VAL_REPORT 'FIELD_VAL_REPORT'
#define FIELD_REGDOC 'FIELD_REGDOC'
#define FIELD_DATEFROM 'FIELD_DATEFROM'
#define FIELD_DATETO 'FIELD_DATETO'
#define FIELD_DATEFROMDOP 'FIELD_DATEFROMDOP'
#define FIELD_DATETODOP 'FIELD_DATETODOP'
#define FIELD_OBJECT 'FIELD_OBJECT'
#define FIELD_DESCR 'FIELD_DESCR'
#define FIELD_DESGR 'FIELD_DESGR'
#define FIELD_DESCRTYPE 'FIELD_DESCRTYPE'
#define FIELD_DESCROWNER 'FILTER_DESCROWNER'
#define FIELD_SORTEDBK 'FIELD_SORTEDBK'
#define FIELD_TOC 'FIELD_TOC'
#define FIELD_FEESIGNER 'FIELD_FEESIGNER'
#define FIELD_OUTDIRXML 'FIELD_OUTDIRXML'
// markers
#define MARKER_KATORG 'MARKER_KATORG'
#define MARKER_KATPODR 'MARKER_KATPODR'
#define MARKER_USERSDOC 'MARKER_USERSDOC'
#define MARKER_USERFILTER 'MARKER_USERFILTER'
#define MARKER_DESCRFILTER 'MARKER_DESCRFILTER'
#define MARKER_MEDIATOR 'MARKER_MEDIATOR'
#define MARKER_CODEOP 'MARKER_CODEOP'
#end //_SCHPRINT_INC
