//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 8.10 - модуль "Платежный календарь (PR)"
// Интерфейс редактирвоания : "Реестры платежей"
//------------------------------------------------------------------------------
#ifndef __EditPayList_Inc__
#define __EditPayList_Inc__
Const
  lc_EditPayList_MarkerName = 'EditPayList_MarkerName';

  lc_TypeRepPayListProW = 0;
  lc_TypeRepPayListHozW = 1;
end;
#endif//__EditPayList_Inc__



