{$IFDEF __type__}
{อออออออออออออ ’ กซจๆ  : SNRESERV "SNRESERV" ออออออออออออออ}
type
  pSNRESERV = ^tSNRESERV;
  tSNRESERV = record   { - SNRESERV }
    D1             : Date;            { d1                                    }
  end;

type
    prSNRESERV = pSNRESERV;
{$ENDIF}
{$IFDEF __CONSTANTS__}
const
    TNPICK=0;
    FND1=0;
    tb4_MODIF_0=0;
{$ENDIF}
{$IFDEF __Type__}
type
   prSNRESERVSNRESERV = pSNRESERV;
{$endif}
