IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[S$EXECUTEEXTERNALQUERY]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[S$EXECUTEEXTERNALQUERY]
GO
CREATE PROCEDURE [dbo].[S$EXECUTEEXTERNALQUERY]( @QUERYID  INTEGER ) AS  
  DECLARE @Q NVARCHAR(MAX) SET @Q = ''
  DECLARE @S NVARCHAR(255)  
  DECLARE C CURSOR LOCAL FOR SELECT F$STR FROM T$EXTERNALQUERIES WHERE ( F$ID = @QUERYID ) ORDER BY F$ATL_NREC
  OPEN C 
  FETCH NEXT FROM C INTO @S
  WHILE @@FETCH_STATUS=0
  BEGIN
    SET @Q = @Q + ' ' + @S
    FETCH NEXT FROM C INTO @S
  END
  CLOSE C
  DEALLOCATE C
  EXECUTE sp_executesql @q
  DELETE T$EXTERNALQUERIES WHERE ( F$ID = @QUERYID )
