//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Управление бюджетом"
// Базовый объект : "Универсальное хранилище параметров операций"
//------------------------------------------------------------------------------

#undef GetFld
#undef SetFld
#undef GetTblFld
#undef SetTblFld
//------------------------------------------------------------------------------
//
//------------------------------------------------------------------------------
#declare GetFld(FldType,FldName,Fld)
  pObjITune.#(FldType)GetFld(_cTune,#FldName,#Fld);
#end// GetFld
#declare SetFld(FldType,FldName,Fld)
  pObjITune.#(FldType)SetFld(_cTune,#FldName,#Fld);
#end//SetFld
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
#declare GetTblFld(FldType,TblName,TblNRec,FldName,Fld)
  if (not pObjITune.#(FldType)GetTblFld(_cTune,#TblName,#TblNRec,#FldName,#Fld) )
  { /*Break;*/ }
#end// GetTblFld
//------------------------------------------------------------------------------
#declare SetTblFld(FldType,TblName,TblNRec,FldName,Fld)
  pObjITune.#(FldType)SetTblFld(_cTune,#TblName,#TblNRec,#FldName,#Fld);
#end// SetTblFld
//------------------------------------------------------------------------------

