//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Электронная отчетность РБ"
// Библиотека функций : "Настройки компонента"
//------------------------------------------------------------------------------

#ifndef __TRBComponentTune_Inc__
#define __TRBComponentTune_Inc__

const
  // ключи настроек
  lc_TuneKey_CurResVer      = 'TBYReport.CurResVer'     ;  // Текущая версия ресурса F_TBYReport
  lc_TuneKey_TaxOrg         = 'TBYReport.TaxOrg'        ;  // Текущий налогоплательщик
  lc_TuneKey_TaxTPer        = 'TBYReport.TaxTPer'       ;  // Тип периода налоговой отчетности
  lc_TuneKey_ViewRepYearBeg = 'TBYReport.ViewRepYearBeg';  // Отображать отчеты начиная с заданного года
end; // const

#endif//__TRBComponentTune_Inc__
