!-------------------------------------------------------------------------------
! Общая часть статус - строк для в-енджиновских иерархий
!-------------------------------------------------------------------------------
#declare VDE_Stat
          '',     cmInsLevel,          kbCtrlF7;
          '',     cmCallTunes,         kbAltN;
          '',     cmSwitch,            kbAltS;
          '',     cmExtendSwitch,      kbAltW;
          '',     cmMarkUnMark,        kbIns;
          '',     cmSelectAll,         kbGrayPlus;
          '',     cmUnSelectAll,       kbGrayMinus;
          '',     cmInvertAll,         kbGrayMul;
          '',     cmCallFilter,        kbAltB;
          '',     cmCallGroup,         kbAltG;
          '',     cmDebug,             kbCtrlD;
          '',     cmPickClass,         kbAltC;
          '',     cmPickAttr,          kbAltA;
          '',     cmLastHelp,          kbAltF1;
          '',     cmCalculator,        kbShiftF2;
          '',     cmBuhCalculator,     kbShiftF3;
          '',     cmPrintDoc,          kbCtrlP;
          '',     cmAttrib,            kbCtrlEnter;
          '',     cmResize,            kbCtrlF5;
          '',     cmNext,              kbF6;
          '',     cmPrev,              kbShiftF6;
          '',     cmSysMenu,           kbCtrlF10;
          '',     cmZoom,              kbF5;
          '',     cmEvaluateAndModify, kbCtrlF4;
          '',     cmMenu,              kbF10;
          '',     cmSaveDoc,           kbCtrlF2;
          '',     cmRestoreDoc,        kbCtrlF3;
          '',     cmManagerId,         kbAltM;
          '',     cmFilialNo,          kbAltN;
          '',     cmPlansNo,           kbAltP;
          '',     cmFilterSave,        kbAltB;
          '',     cmPass,              kbF4;
          '',     cmCompressLevel,     kbCtrlBack;
          '',     cmShowAll,           kbCtrlGrayPlus;
          '',     cmShowAll,           kbCtrlEqual;
          '',     cmHideAll,           kbCtrlGrayMinus;
          '',     cmNal,               kbAltF;
          '',     cmDocBas,            kbAltD;
          '',     cmHotKeys,           kbAltF10;
          '',     cmAltInsert,         kbAltF7;
#end
