//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Управление бюджетом"
// Константы идентификаторов параметров типа "Типовые формы"
//------------------------------------------------------------------------------

#ifndef __FpTFormParam_Inc__
#define __FpTFormParam_Inc__

Const
  Var_cCurTForm                 = 'CCTF';

  Tbl_tblTForm                  = 'TTTF';

  TblVar__tblTForm_cRec         = 'TFcR';
  TblVar__tblTForm_fOrder       = 'TFfO';
end;

#endif//__FpTFormParam_Inc__
