const

  //Выпадающие списки
  NODE_INVALID_TS = 0  ;

  // ОКЕИ
  NODE_OKEI_181 = 181; // 181 | Брутто-регистровая тонна (2,8316 м3) (БРТ)
  NODE_OKEI_251 = 251; // 251 | Лошадиная сила (л.с.)
  NODE_OKEI_796 = 796; // 796 | Штука (Шт)
  NODE_OKEI_999 = 999; // 999 | Килограмм силы (Кгс)

  // Формула расчета
  NODE_FORMRASCH_1 = 1; // Стр. 300 = стр. 190
  NODE_FORMRASCH_2 = 2; // Стр. 300 = стр. 190 - стр. 230
  NODE_FORMRASCH_3 = 3; // Стр. 300 = стр. 190 - стр. 250 - стр. 270
  NODE_FORMRASCH_4 = 4; // Стр. 300 = стр. 190 - стр. 290
  NODE_FORMRASCH_5 = 5; // Стр. 300 = стр. 190 - стр. 250 - стр. 270 - стр. 290

  // Экологический класс
  NODE_JEkologKl_Null = 9;  // -
  NODE_JEkologKl_0    = 0;  // 0
  NODE_JEkologKl_1    = 1;  // 1
  NODE_JEkologKl_2    = 2;  // 2
  NODE_JEkologKl_3    = 3;  // 3
  NODE_JEkologKl_4    = 4;  // 4
  NODE_JEkologKl_5    = 5;  // 5
  NODE_JEkologKl_6    = 6;  // 6

end;