const

  // Типы разделов
  _Income = 0;  // приход
  _Outlay = 1;  // расход

  // Виды входимости НДС
  _NDSIncluding = 1; // НДС в том числе
  _NDSAbove     = 2; // НДС кроме того

  // [S]umma[T]ype
  _stNal    =  0;  // Сумма нал
  _stBN     =  1;  // Сумма б/н
  _stIncome =  2;  // Сумма дохода
  _stNDS    =  3;  // Сумма НДС

  _stTotal  = 10;  // Нал + б/н

  // Номер первого раздела
  sFirstPart = '01';
end;
