! ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
! บ   งเ กฎโ ซ:  ฎญคเ ซ์ .€.                                             บ
! บ   งญ ็ฅญจฅ:  ‘็ฅโ , คฎฃฎข เ  ฏเฎค ฆ , ง ชใฏฎช, ชฎญแจฃญ ๆจจ             บ
! ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
.form 'DO_t55'
.hide
!.group 'เฎค ฆ '
.fields
  wCountry : word
  sdoc srub
  UnnName
  MFOBIK
  BaseDocNrec : comp
  mnd 
  RealSkidPercent:double
  FIOman

  MyOrg_N
  KatOrg_N
  pname kategor

  Bilet_No Bilet_Date Bilet_D Bilet_M Bilet_Y

  Lesoseka

  nomer 
  ddoc : Date 
  SpBrigad 
  KolBrig : integer
  TNomBr

  CP_dDoc CP_INDoc CP_ENDoc

  SpCP_N SpCP_PrMC SpCP_GroupName SpCP_GroupKOD SpCP_EdN SpCP_EDK SpCP_Kol SpCP_Price SpCP_Sum

  FIOSotr TNomPer Allchas Allden 
  SumSdel : Double
  SumRab  : Double
  SumAll  : Double
  Den1 Den2 Den3 Den4 Den5 Den6 Den7 Den8 Den9 Den10 Den11 Den12 Den13 Den14 Den15 Den16 Den17 
  Den18 Den19 Den20 Den21 Den22 Den23 Den24 Den25 Den26 Den27 Den28 Den29 Den30 Den31

  SpStep_Name1 SpStep_Kod1 SpStep_Ed1 SpStep_Kol1
  SpStep_Name2 SpStep_Kod2 SpStep_Ed2 SpStep_Kol2

.endfields

  wCountry ^
  sdoc  ^
  srub ^
  UnnName ^
  MFOBIK ^
  BaseDocNrec ^
  mnd  ^
  RealSkidPercent ^
  FIOman ^

  MyOrg_N ^
  KatOrg_N ^

  pname ^
  kategor ^

  Bilet_No ^
  Bilet_Date ^
  Bilet_D ^
  Bilet_M ^
  Bilet_Y ^

  Lesoseka ^

.{
   ^ ^ ^ ^ ^                  //nomer ddoc SpBrigad KolBrig TNomBr
.}


  CP_dDoc ^
  CP_INDoc ^
  CP_ENDoc ^

.{
   SpCP_N ^
   SpCP_PrMC ^
   SpCP_GroupName ^
   SpCP_GroupKOD ^
   SpCP_EdN ^
   SpCP_EDK ^
   SpCP_Kol ^
   SpCP_Price ^
   SpCP_Sum ^
.}

.{
  FIOSotr ^
  TNomPer ^
  Allchas ^
  Allden ^
  SumSdel ^
  SumRab ^
  SumAll ^
  Den1 ^
  Den2 ^
  Den3 ^
  Den4 ^
  Den5 ^
  Den6 ^
  Den7 ^
  Den8 ^
  Den9 ^
  Den10 ^
  Den11 ^
  Den12 ^
  Den13 ^
  Den14 ^
  Den15 ^
  Den16 ^
  Den17 ^
  Den18 ^
  Den19 ^
  Den20 ^
  Den21 ^
  Den22 ^
  Den23 ^
  Den24 ^
  Den25 ^
  Den26 ^
  Den27 ^
  Den28 ^
  Den29 ^
  Den30 ^
  Den31 ^
.}

.{
   SpStep_Name1 ^
   SpStep_Kod1 ^
   SpStep_Ed1 ^
   SpStep_Kol1 ^

   SpStep_Name2 ^
   SpStep_Kod2 ^
   SpStep_Ed2 ^
   SpStep_Kol2 ^
.}

.endform