//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика ERP 9.1 - Управление персоналом
// Константы для разделения сущностей таблицы SpAllStaff по полю SpAllStaff.wNoCon
//------------------------------------------------------------------------------

cgAllStaffProtocol = 1; // для протокола сообщений
cgRPD_55 = 2; // для РПД-55
cgAllStaffCandidatDX = 3;
cgAllStaffImportSAP = 4; // для протокола сообщений при импорте из SAP
cgAllStaffContract = 5;
cgAllStaffAddAgreement = 6;
cgAllStaffAgreementLink = 7;
cgHAppHRaiseCon         = 8; // связь истории назначения с историей доплаты
cgAppRaiseCon           = 9; // связь назначения с доплатой
