//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 5.80 - модуль "Управление бюджетом"
// Базовый объект : "Универсальный менеджер операций"
//------------------------------------------------------------------------------

#ifndef __FpRunFun_Inc__
#define __FpRunFun_Inc__

Const
  cgiFpBath_CulcFpOb                = 1;
  cgiFpBath_FpBudgetCopy            = 2;
  cgiFpBath_FpBudgetAggr            = 3;
  cgiFpBath_FpMRasp                 = 4;
  cgiFpBath_RecBud                  = 5;
  cgiFpBath_FpBudgetDecomp          = 6;
  cgiFpBath_FpImportXLSBudget       = 7;
  cgiFpBath_FpImportDBFBudget       = 8;
  cgiFpBath_FpExportDBFBudget       = 9;
  cgiFpBath_FpClearBudget           = 10;
  cgiFpBath_FpCreateBudget          = 11;
  cgiFpBath_FpImportXLSOborot       = 12;
  cgiFpBath_RunFpStatAlg            = 13;
  cgiFpBath_RunnerFpImport          = 14;
  cgiFpBath_RunFpPayment            = 15;
end;

Const
  MaxModelCount                     = 15;
end;

#endif // __FpRunFun_Inc__
