const

  // Строчки
  reSpOrderDescr     = 0001;  // "дескриптор к номеру документа",
  reSpOrderDesGr     = 0002;  // "код группы пользователей",

  // реальные числа
  reSpOrderKol       = 0051;
  reSpOrderSrPrice   = 0052;
  reSpOrderVPrice    = 0053;
	reSpOrderRsRPrice  = 0054;

  // признаки всякие
  reSpOrderSP        = 1101;  // Word  "склад/производство", 0-склад 1-производство
  reSpOrderVidOrder  = 1102;  // Word  "0 - приходный, 1 - расходный",
  reSpOrderTipOrd    = 1103;  // Word  "тип ордера", // 1 - внешние накладные 2 - производство 3 - внутреннее перемещение

  reSpOrderdOrd      = 1201;  // Date  "дата ордера",

  reSpOrderNpp      = 1251;  // Word  "год даты ордера",

  reSpOrdercSpSopr   = 1301;
  reSpOrdercSklOrder = 1302;
  reSpOrderccPodr    = 1303;
  reSpOrderccMol     = 1304;
  reSpOrdercMc       = 1305;
  reSpOrdercParty    = 1306;
  reSpOrdercBox      = 1307;
  reSpOrdercVal      = 1308;

  reSkSpOrderSP       = 1401;
  rePrSpOrderSP       = 1402;
  rePrSpOrderVidOrder = 1403;
  reRaSpOrderVidOrder = 1404;

  reNoBound           = 3000;

  reToSklOrder        = 3001;
  reToSklOrderMc      = 3002;
  reToSpSopr          = 3003;

  reAddSpMc           = 3101;
  reAddVidOrder       = 3102;
  reAddccPodr         = 3103;
  reAddccMol          = 3104;
  reAddcParty         = 3105;
  reAddDateInterval   = 3106;
  reSubSpMc           = 3201;
  reSubVidOrder       = 3202;
  reSubccPodr         = 3203;
  reSubccMol          = 3204;
  reSubcParty         = 3205;
  reSubDateInterval   = 3206;

  reSklOrderParam     = 4001;
  reKatMcParam        = 4002;
  reSpSoprParam       = 4003;
  rewSP               = 4004;
  reVidOrder          = 4005;
  reccPodr            = 4006;
  reccMol             = 4007;
  recParty            = 4008;
  redOrdBeg           = 4009;
  redOrdEnd           = 4010;





  reTipOrderConst     = 5001;


end

