const

  // числа

  reKol          = 01;
  reKolOpl       = 02;
  reOstKol       = 03;
  rePrice        = 04;
  reProcUb       = 05;
  reNpp          = 06;
  reSumAvt       = 07;
  reNetto        = 08;
  remTara        = 09;
  reKol2         = 10;
  reVPrice       = 11;
  reKolFact      = 12;
  reKolFact2     = 13;
  reKolNorma     = 14;
  reOilPlot      = 15;
  reOilTemper    = 16;
  reSumNDS       = 17;
  reSumVNDS      = 18;
  reRPrice       = 19;
  reRVPrice      = 20;
  reProcNac      = 21;
  repriceN       = 22;
  revPriceN      = 23;
  reKolGrM       = 24;
  reKolDop       = 25;
  reKolPov       = 26;
	reKolOplEx     = 27;

  // строки
  renVagon       = 1001;
  renKvit        = 1002;
  renSertif      = 1003;

  // даты
  redSopr          = 2001;
  redOprTTN        = 2002;


  // ссылки
  recSpSopr        = 3001;
  rePrMC           = 3002;
  recMCUSL         = 3003;
  recOtpED         = 3004;
  recAltEd         = 3005;
  recParty         = 3006;
  recVAL           = 3007;
  recPriceList     = 3008;
  recPersons       = 3009;
  reManualTax      = 3010;
  recGrNal         = 3011;
  recCellVal       = 3012;
  recTransp        = 3013;
  recValAvt        = 3014;
  recMasEd         = 3015;
  recMasVid        = 3016;
  recResOtgr       = 3017;
  recSpDocs        = 3018;
  recSopr          = 3019;
  reVidSopr        = 3020;
  recSpOrder       = 3021;
  recSpStep        = 3022;
  recSPNZAKAZ      = 3023;
  recSpSchF        = 3024;
  rewADocSp        = 3025;
  recADocSp        = 3026;
  recZakVol        = 3027;
  recOtpEdGrM      = 3028;
  recNMoveCell     = 3029;
  recOwner         = 3030;
  recGPSopr        = 3031;
  recUKS           = 3032;
  rewMcProp        = 3033;
  remanualNalUch   = 3034;
	reCO						 = 3035;

  reNoBound            = 4000;
  reTieToKatSopr       = 4001;
	reTieToGPSopr        = 4002;
	reTieToSpSopr        = 4003;
  reTieToSpStep        = 4004;
	reTieToSpNarZak      = 4005;
	reTieToKatSoprMcUsl  = 4006;
	reTieToNZakazMcUsl   = 4007;
	reTieToPeriodMCSpis  = 4008;
  reIsValid 			     = 4009;
	reTieToVidMC         = 4010;
	reTieToViddSoprMC    = 4011;
	reTieToViddSoprParty = 4012;
	reTieToVidParty      = 4013;
	reTieToViddOprParty  = 4014;
	reTieToVidMCParty    = 4015;

	reSpOrderSearch = 4201;

  reKatSoprParam       = 5001;
	reGPSoprParam        = 5002;
	reSpSoprParam        = 5003;
  reSpStepParam        = 5004;
	reSpNarZakParam      = 5005;
	rePrMcUslParam       = 5006;
	reMcUslParam 		     = 5007;
	reBeginParam   	     = 5008;
	reEndParam   		     = 5009;
	reSearchSpOrderParam = 5010;
	reTypeSoprParam      = 5011;
	reCOParam				     = 5012;
	reSpOrderParam       = 5013;
	redSoprParam         = 5014;
	rePartyParam         = 5015;
	redOprParam          = 5016;

	reNew    = 5100;
	reDelCur = 5201;
end

