const


  // числа
  rePickKol    = 0001;
  rePickNum    = 0002;

  // Даты

  // ссылки
  recRec       = 2001;
  rewList      = 2002;

  // наименования

  reNoBound     = 4000;

  reBywList     = 4001;

  reNew         = 5001;
  reDelCur      = 5002;
  reDelwList    = 5003;

  reLookForcRec = 6001;


  rewListParam     = 10001;
  recRecParam      = 10002;
  rewPickKolParam  = 10003;
  rewPickNumParam  = 10004;
end

