const

  // числа

  // даты
  redOrd    = 2001;

	// времена

  // ссылки
  recCardSN = 3001;
  recSpSopr = 3002;
  recSpOrd  = 3003;

  // наименования
  reNOrder  = 4001;

	// ограничения и подцепки
  reNoBound            = 5000;
  reByCardSN           = 5001;
  reBySpSopr           = 5002;
  reBySpOrd            = 5003;
  reBySpOrdSpSopr      = 5004;
  reByCardSNSpSopr     = 5005;
  reByCardSNSpOrd      = 5006;
  reNew                = 5101;

	// параметры
  recCardSNParam       = 6001;
  recSpSoprParam       = 6002;
  recSpOrdParam        = 6003;

end
