const

  // числа (double)
  reKol        = 1001;
  resumUsl     = 1002;
  reSumUslVal  = 1003;
  reValCurse1  = 1004;
  reSumUslReal = 1005;
  reValCurse2  = 1006;
  reValCurse12 = 1007;
  rePrice      = 1008;
  reVPrice     = 1009;
  reVPriceReal = 1010;
  renpTime     = 1011;
  reFkTime     = 1012;
  retimespec   = 1013;
  reTARIF      = 1014;
  reSumNDS     = 1015;
  reSumVNDS    = 1016;
  redWork1     = 1017;
  redWork2     = 1018;
  redWork3     = 1019;

  // числа (word)
  reTipForm   = 1501;
  reManualTax = 1502;
  rewWork1    = 1503;
  rewWork2    = 1504;
  rewWork3    = 1505;
  rewIst      = 1506;


  // времена


  // даты
  reDateR  = 2501;
  reDatBeg = 2502;
  reDatEnd = 2503;


  // ссылки
  recKatZak    = 3001;
  recSpSopr    = 3002;
  recKatUsl    = 3003;
  recMarAvt    = 3004;
  recOtpEd     = 3005;
  recVal       = 3006;
  recValReal   = 3007;
  recTarifn    = 3008;
  recRashDoc   = 3009;
  recPriceList = 3010;
  recAlg       = 3011;
  recWork1     = 3012;
  recWork2     = 3013;
  recWork3     = 3014;
  recIst       = 3015;


  // наименования

  // ограничения и подцепки
  reNoBound    = 5000;
	reToBounds01 = 5001;
	reToBounds02 = 5002;
	reToBounds03 = 5003;

  // быстрая навигация


  // параметры
	recKatZakParam  = 7001;
	recRashDocParam = 7002;
	reDatBegParam   = 7003;


end

