const

  // числа
  resNalogs     = 1;
  resvNalogs    = 2;
  reSumma       = 3;
  reSumVal      = 4;
  reKolKompl    = 5;
  reRndR        = 6;
  reRndV        = 7;
  reNetto       = 8;
  remTara       = 9;

  // строки
  reName         = 1001;
  reDescr        = 1002;
  reDesGr        = 1003;
  renDover       = 1004;
  renVagon       = 1005;
  renKvit        = 1006;
  renSertif      = 1007;
  reNSopr        = 1008;
  reUserField    = 1009;
  resDover       = 1010;

  // даты
  redPrice       = 2001;
  redDover       = 2002;
  redSopr        = 2003;
  redOpr         = 2004;

  // ссылки
  recOrg          = 3001;
  recVal          = 3002;
  reVhodNal       = 3003;
  recCompl        = 3004;
  recNazna        = 3005;
  recDogovor      = 3006;
  recAppDogovor   = 3007;
  recCalPlan      = 3008;
  recPerson       = 3009;
  recDover        = 3010;
  recDovFio       = 3011;
  reStatus        = 3012;
  recNote         = 3013;
  recPayment      = 3014;
  recTransp       = 3015;
  recMasEd        = 3016;
  recMasVid       = 3017;
  recBaseDoc      = 3018;
  reTipSopr       = 3019;
  reYearSopr      = 3020;
  reVidSopr       = 3021;
  recPodrFrom     = 3022;
  recPodrTo       = 3023;
  recMolFrom      = 3024;
  recMolTo        = 3025;
  recGruzFrom     = 3026;
  recGruzTO       = 3027;
  recOrgBase      = 3028;
  recHozOper      = 3029;
  reSoprHoz       = 3030;
  reReserved      = 3031;
  recKatSopr      = 3032;
  recValut        = 3033;
  recSchFact      = 3034;
  recGrSopr       = 3035;
  retransp        = 3036;
  recNZakaz       = 3037;
  recOtgOrder     = 3038;
  rewADoc         = 3039;
  recADoc         = 3040;
  recIzd          = 3041;
  rewcIzd         = 3042;
  recZakaz        = 3043;
  recPriceAlg     = 3044;
  reTypeDoc       = 3045;
  recCellVal      = 3046;
  recNMoveCell    = 3047;
  reTaraVoz       = 3048;
  recOrgPlat      = 3049;
  reTipOtvPodr    = 3050;
  recOtvPodr      = 3051;
  recUKS          = 3052;

  reNoBound                  = 4000;
  reTieToKatSopr             = 4001;
        reTieToBaseDoc             = 4002;
        reTieToNZakaz              = 4003;
        reTieToVidSopr             = 4004;
        reTieToVidSoprdSopr        = 4005;
        reTieToVidSoprdOpr         = 4006;
        reTieTodOprPodrFromVidSopr = 4007;
        reTieTodOprPodrToVidSopr   = 4008;
        reTieTocOrgdSopr           = 4009;
        reTieTocOrgdOpr            = 4010;
        reTieToDogovordSopr        = 4011;
        reTieToDogovorVidSopr      = 4012;
        reTieToVidSoprStatus       = 4013;
        reTieToVidSoprStatusdSopr  = 4014;
        reTieToCalPlandSopr        = 4015;
        reTieToCalPlanVidSopr      = 4016;

        reByVidSoprdSoprNSopr       = 4501;
        reByVidSoprdSoprStatusNSopr = 4502;

  reKatSoprParam  = 5001;
        reBaseDocParam  = 5002;
        reNZakazParam   = 5003;
        reVidSoprParam  = 5004;
        redSoprParam    = 5005;
        redOprParam     = 5006;
        rePodrFromParam = 5007;
        rePodrToParam   = 5008;
        reOrgParam      = 5009;
        reDogovorParam  = 5010;
        reStatusParam   = 5011;
        reNSoprParam    = 5012;
        reCalPlanParam  = 5013;
        reNew           = 5100;
        reDelCur        = 5200;

        reStatusNaklType1 = 6000;
        reStatusNaklType2 = 6001;
        reStatusNaklType3 = 6002;
        reStatusNaklType4 = 6003;
        reStatusNaklType5 = 6004;
        reStatusNaklType6 = 6005;
        reStatusNaklType7 = 6006;

end
