const

  // числа
	reTypeDoc   = 1501;
	reTypeSpDoc = 1502;
	reKindRec   = 1503;
	reKindOper  = 1504;
	reTypeOper  = 1505;
  reType      = 1506;
  rePrMc      = 1507;
  reTypeObj   = 1508;
  reTypeSpObj = 1509;
  reTypeStage = 1510;

  // даты
	reOperDate  = 2001;

  // ссылки
  recQPHead   = 3001;
	recDoc      = 3002;
  recSpDoc    = 3003;
  recMnSlit   = 3004;
  recKatSort  = 3005;
  recKatStats = 3006;
  recMcUsl    = 3007;
  recPodr     = 3008;
  recMol      = 3009;
  recParty    = 3010;
  recObject   = 3011;
  recSpObject = 3012;
  recStage    = 3013;

  // наименования
	reDescr      = 4001;
	reDesGr      = 4002;

	// ограничения и подцепки
  reNoBound          = 5000;
	reToDoc            = 5001;
	reToDocSpDoc       = 5002;
	reToMnSlit         = 5003;
	reToMnSlitKind     = 5004;
	reToMnSlitKindType = 5005;
  reToQPHead         = 5006;
  reToMc             = 5007;
  reToMcParty        = 5008;
  reToMcPodr         = 5009;
  reToMcMol          = 5010;

	// быстрая навигация

	// параметры
	reQPHeadParam     = 7101;
  reTypeDocParam    = 7102;
  reTypeSpDocParam  = 7103;
  reKindOperParam   = 7104;
  reTypeOperParam   = 7105;
  rePrMcParam       = 7106;
  reMnSlitParam     = 7108;
  reDocParam        = 7109;
  reSpDocParam      = 7110;
  reMcUslParam      = 7111;
  rePartyParam      = 7112;
  rePodrParam       = 7113;
  reMolParam        = 7114;

end

