const


  // числа
  refKol          =  0001;
  refEnsure       =  0002;
  refFact         =  0003;
  refTaked        =  0004;
  refPrih         =  0005;
  refRash         =  0006;
  refExcess       =  0007;
  refError        =  0008;
  refTestPrih     =  0009;
  refTestRash     =  0010;
  refTestExcs     =  0011;
  relPriority     =  0012;

  // Даты
  redMove         =  1001;
  redTerm         =  1002;

  // ссылки
  recOwner        = 2001;
  rewDoc          = 2002;
  recDoc          = 2003;
  recSlit         = 2004;
  rewDirect       = 2005;
  rewStatus       = 2006;

  // наименования
  reDescr         = 3001;

  // логика
  rewAllow        = 3501;
  reIsPrih        = 3502;
  reIsRast        = 3503;

  reNoBound     = 4000;
  reByOwner     = 4001;
  reBySlit      = 4002;
  reByDoc       = 4003;
	reByMCPeriodTypeDoc = 4004;
	reIsValid 		= 4005;

  reForTake     = 4010;

  refRest       = 4020;
  refTake       = 4021;

  rewDocConst   = 6001;

  reOwnerParam  = 10001;
  reSlitParam   = 10002;
  rewDocParam   = 10003;
  recDocParam   = 10004;
  // rewDirectParam = 10005;
	redBeginParam = 10006;
	redEndParam   = 10007;
	recIzdParam   = 10008;

  rePlanMoveObject = 10101;
end
