const
//real
  relNum     =  1;
  rewTWage     =  2;
  rewTCode     =  3;
  rewTClass     =  4;
  recoExec     =  5;
  rewEdTime    =  6;
  reActive   =  7;
  reStatus  =  8;
  reTipov     =  9;
/*
  reZapasMax  =  9;
  reNormUb    = 10;
  rePercentN  = 11;
  rePricePU   = 12;
  reCenaMC    = 13;
  reMaxProcN  = 14;
  reNalProd   = 15;
  reMAXON     = 16;
  reMAXRN     = 17;
  reMAXORN    = 18;
	reNalNDS    = 19;
*/

  // Даты
  reStartDate   = 1000;
  reEndDate     = 1001;
  
  // ссылки
  reRole1        = 2000;
  reCode1        = 2001;
  reRole2        = 2002;
  reCode2        = 2003;
  reRole3        = 2004;
  reCode3        = 2005;
  reRole4        = 2006;
  reCode4        = 2007;
  reRole5        = 2008;
  reCode5        = 2009;
  recEqGroup     = 2010;
  recWork        = 2011;
  recDep         = 2012;
  reParGroup     = 2013;
  recNormGroup   = 2014;
  recDocNastr    = 2015;
/*
  recHashAn      = 2016;
  recSloj        = 2017;
  recUsl         = 2018;
  recDopEd       = 2019;
*/

// строки 
  reNAME          = 3000;
  resNum         = 3001;
/*
  reBarKod        = 3002;
  reBarKod2       = 3003;
  reRemMC         = 3004;
  rekGroupMC      = 3005;
  reTNVED         = 3006;
  reMaskName      = 3007;
*/

// bounds
  reNoBound     = 4000;   
  reByName      = 4001;
  reBy_lNum     = 4002;
  reBy_sNum     = 4003;
  reBy_cDep     = 4004;
  reBy_Tip      = 4005;
//  reByAnalitic  = 4006;
  reBy_TipName  = 4007;
  reBy_TiplNum  = 4008;
  reBy_TipsNum  = 4009;

// числовые параметры
  rewTipParam   = 5001;
  relNumParam   = 5002;
 
//ссылочные параметры
  recDepParam     = 6001;
/*
  reTemplateParam  = 6002;
  reAnaliticParam1 = 6003;
  reAnaliticParam2 = 6004;
  reAnaliticParam3 = 6005;
  reAnaliticParam4 = 6006;
*/

//строковые параметры
  reNameParam    = 7001;
  resNumParam    = 7002;
/*
  reConstrParam  = 7003;

  reGroup       = 10001;
  reTemplate    = 10002;
*/

end
