const


  // ссылки
  recDoc        = 2001;
  recNewNote    = 2002;
  recOldNote    = 2003;
  reDocType     = 2004;
  reNewStatus   = 2005;
  reOldStatus   = 2006;

  // строки            
  reComment     = 3001;
  reDescr       = 3002;
  reDesGr       = 3003;


  // Даты
  redOper       = 4001;
  // Время
  reTimeOper    = 4501;



  reNoBound     = 5000;
  reTieByDoc    = 5001;

  reNewStatLog  = 5101;
  reDelCur      = 5102;

  reDocTypeParam = 6001;
  recDocParam    = 6002;

  reOldStatusParam    = 6003;
  reNewStatusParam    = 6004;
  reCommentParam = 6005;

  reVidDocConst  = 7001;


end

