const

  reWork        = 1;
  reType        = 2;

  reOwner      = 101;
  reMc         = 102;
  rePodr       = 103;
  reOper       = 104;
  reParty      = 105;
	reKauMc      = 106;

  reDBegT      = 1000;
  reDEndT      = 1001;

  reMarsh       = 2000;
  reVaria       = 2001;
  reAnValPos1   = 2003;
  reAnValPos2   = 2004;
  reAnValPos3   = 2005;
  reAnValPos4   = 2006;
  reAnValPos5   = 2007;

	reHigherMC    = 2010;
	reTopMC       = 2011;
	reHigherRsv   = 2012;
	reParent      = 2013;
	rePos         = 2014;
	reGroupPick   = 2015;

  rePlanZap     = 3000;
  rePlanZapDl   = 3001;
  rePlanVip     = 3002;
	rePlanVipDl   = 3003;
  reFactZap     = 3004;
  reFactZapDl   = 3005;
  reFactVip     = 3006;
	reFactVipDl   = 3007;
  reNZP         = 3008;
  reNZPDl       = 3009;
  reTekNal      = 3010;
  reTekNalDl    = 3011;
  reBrak        = 3012;
  reBrakDl      = 3013;
  reAccept      = 3014;
  reAcceptDl    = 3015;
  reUtvZap      = 3016;
  reUtvZapDl    = 3017;
  reUtvVip      = 3018;
  reUtvVipDl    = 3019;
  rePlanBrak    = 3020;
  rePlanBrakDl  = 3021;
  rePrepZap     = 3022;
  rePrepZapDl   = 3023;
  reAllPlan     = 3024;
  reAllPlanDl   = 3025;
  reMatur       = 3026;
  reMaturDl     = 3027;
  reTransfer    = 3028;
  reTransferDl  = 3029;
  rePlanZapEx   = 3030;
  rePlanZapExDl = 3031;
  rePlanVipEx   = 3032;
  rePlanVipExDl = 3033;
  reFactZapEx   = 3034;
  reFactZapExDl = 3035;
  reFactVipEx   = 3036;
  reFactVipExDl = 3037;



	reToResInfo        = 4001;
  reToPriority       = 4002;
  reToSFilters       = 4003;
	reToState		       = 4004;
	reDeleteCurrent    = 4005;
	reInsertRecord     = 4006;
	reDeleteAll        = 4007;
	reCalcForAllRazrez = 4008;
	reDelPick          = 4009;
	reInsertRecordPick = 4010;


	reNumParParam      = 4100;
  reNumParExtParam   = 4101;
  reNumRazrezParam   = 4102;
  reNumPickParParam  = 4103;
  reModeParam        = 4104;

	reList             = 4200;
  reRec              = 4201;
  reSpAnVal1         = 4202;
  reSpAnVal2         = 4203;
  reSpAnVal3         = 4204;
  reSpAnVal4         = 4205;
  reSpAnVal5         = 4206;
  reGroup            = 4207;
	rePickNRec         = 4208;
	reListParam        = 4300;
  reRecParam         = 4301;
  reSpAnVal1Param    = 4302;
  reSpAnVal2Param    = 4303;
  reSpAnVal3Param    = 4304;
  reSpAnVal4Param    = 4305;
  reSpAnVal5Param    = 4306;
  reGroupParam       = 4307;


//параметры на огрничение
  reDateBeginParam   = 5000;
  reDateEndParam     = 5001;

	reNoBound          = 5010;
	reToParty          = 5011;
  reToPodr           = 5012;
  reToDate           = 5013;
  reToOwner          = 5014;

	//константы для работы с таблицей LinkOstRsv
	reGetFirstPos         = 5100;
	reGetLastPos          = 5101;
	reGetNextPos          = 5102;
	reGetPrevPos          = 5103;

	reOwnerParam       = 5200;
  reMcParam          = 5201;
  rePodrParam        = 5202;
  rePartyParam       = 5203;
  reDBegTParam       = 5204;
  reDEndTParam       = 5205;
  reVariaParam       = 5206;
	reKauMcParam       = 5207;

	//константы для ограницения для таблицы LinkOstRsv
	reRazrezParam      = 5500;
	reNumRazParParam      = 5501;

	reNoBoundLink      = 5502;
	reToRazrez         = 5503;
	reToNumPar         = 5504;


	reNRec             = 5600;
  recRsvOper         = 5601;
  rewState           = 5602;
  rewPrEd            = 5603;
  reNumPar           = 5604;
  reKol              = 5605;
  reDlit             = 5606;
  rewFlag            = 5607;
  redoReserv         = 5608;
  redoRest           = 5609;
  recRazrez          = 5610;
  recRazrezVX        = 5611;
  recVaria           = 5612;

	reFillRestAndReserv      = 5700;
	rebSaveParam             = 5701;
	rebSaveReservInfoParam   = 5702;

 //	reResultRsv        = 5600;
	//reResultRsv1       = 5601;

	//reNavigation       = 5601;


	reSFiltersConst = 6001;



  reInfo        = 10000;
end
