const

  // числа
  reType      = 1501;
  rePrMc      = 1502;
  reTypeObj   = 1503;
  reTypeSpObj = 1504;
  reTypeStage = 1505;

  // даты

  // ссылки
  recMcUsl    = 3001;
  recPodr     = 3002;
  recMol      = 3003;
  recParty    = 3004;
  recObject   = 3005;
  recSpObject = 3006;
  recStage    = 3007;

  // наименования

	// ограничения и подцепки
  reNoBound          = 5000;
	reToSlitElem       = 5001;
  reToMc             = 5002;
  reToPodr           = 5003;
  reToMol            = 5004;
  reToParty          = 5005;

	// быстрая навигация

	// параметры
	reTypeParam       = 7101;
  rePrMcParam       = 7102;
  reMcUslParam      = 7103;
  rePartyParam      = 7104;
  rePodrParam       = 7105;
  reMolParam        = 7106;

end

