const
  reKolAkt   =  1;
  reRasCenka =  2;
  reNormTime =  3;
  reKlass    =  4;
  reKolDef   =  5;
	reNalProd   = 6;
	reNalNDS    = 7;

  // Даты
  // reStartDate   = 1000;
  // reEndDate     = 1001;

  recGroupUsl  = 2000;
  recGrNal     = 2001;
  recSHBUSL    = 2002;
  recStZatr    = 2003;
  recKaElem    = 2004;
  recMaskUsl   = 2005;
  recHashAn    = 2006;
  recSloj      = 2007;
  recED        = 2008;

  reNAME       = 3000;
  reKOD        = 3001;
  rekGroupUsl  = 3002;
  reOKDP       = 3003;
  reObozn      = 3004;
  reMaskName   = 3005;

  reNoBound     = 4000;
  reByName      = 4001;
  reByCode      = 4002;
  reByConstr    = 4003;
  reByGroup     = 4004;
  reByTepmlate  = 4005;
  reByAnalitic  = 4006;

  reGroupParam     = 6001;
  reTemplateParam  = 6002;
  reAnaliticParam1 = 6003;
  reAnaliticParam2 = 6004;
  reAnaliticParam3 = 6005;
  reAnaliticParam4 = 6006;

  reNameParam    = 7001;
  reCodeParam    = 7002;
  reConstrParam  = 7003;

  reGroup       = 10001;
  reTemplate    = 10002;


end
