const

  // числа
  reLKOD           = 101;

  // Ссылки

  recMC            = 2001;
  recVal           = 2002;
  recOrgPar        = 2003;

  // вставка и удаление записи
  reDeleteCurrent  = 2004;
  reInsertRecord   = 2005;


  // Строки
  reKOD            = 3001;
  reName           = 3002;

  // Логика
  reinCountry      = 4001;


  // ограничеия и подцепки
  reNoBound        = 5000;
  reByKOD          = 5001;
  reBycMC          = 5002;
  reByName         = 5003;

	// параметры
	reMcParam      = 7001;
  reKODParam     = 7002;
  reNameParam    = 7003;

  end

