const

  // числа
  reTypeOwn  = 1001;
  reIsLeaf   = 1002;
  reResWord1 = 1003;
  reResWord2 = 1004;
  reResWord3 = 1005;
  reResWord4 = 1006;
  reResWord5 = 1007;
  //
  reResDouble1 = 1501;
  reResDouble2 = 1502;
  reResDouble3 = 1503;
  reResDouble4 = 1504;
  reResDouble5 = 1505;

  // даты
  redDoc      = 2001;
  redRelease  = 2002;
  reResDate1  = 2003;
  reResDate2  = 2004;
  reResDate3  = 2005;

	// времена

  // ссылки
  recMc         = 3001;
  recCardSN     = 3002;
  recMnPlan     = 3003;
  recSpMnPl     = 3004;
  recPersonsOTK = 3005;
  recPodr       = 3006;
  recMol        = 3007;
  recOwner      = 3008;
  recMGCard     = 3009;
  reResComp1    = 3010;
  reResComp2    = 3011;
  reResComp3    = 3012;
  reResComp4    = 3013;
  reResComp5    = 3014;

  // наименования
  reDescr    = 4001;
  reDesGr    = 4002;
  renDoc     = 4003;
  reSerial   = 4004;
  reFIOOTK   = 4005;
  reStampOTK = 4006;
  reNumber   = 4007;

	// ограничения и подцепки
  reNoBound            = 5000;
  reBySerial           = 5001;
  reByMGCard           = 5002;
  reByCardSN           = 5003;
  reByMGCardMC         = 5004;
  reBynDoc             = 5005;
  reBydDoc             = 5006;

  reNew                = 5101;

	// параметры
  recMcParam           = 6001;
  recMGCardParam       = 6002;
  recCardSNParam       = 6003;

  reSerialParam        = 6101;
  renDocParam          = 6102;

  redDocParam          = 6201;

end
