const
  reKolOtp      = 1;
  rePriceOtp    = 2;
  reKolDoc      = 3;
  rePriceDoc    = 4;
  reSumma       = 5;
  reDiscount    = 6;

  rewPos        = 11;
	reliField01   = 12;
	reliField02   = 13;
	reliField03   = 14;
	reliField04   = 15;
	reliField05   = 16;

  reField01    = 101;
  reField02    = 102;
  reField03    = 103;
  reField04    = 104;
  reField05    = 105;
  reField06    = 106;
  reField07    = 107;
  reField08    = 108;
  reField09    = 109;
  reField10    = 110;

  reStartDate   = 1000;
  reEndDate     = 1001;
  reDtField01   = 1101;
  reDtField02   = 1102;
  reDtField03   = 1103;
  reDtField04   = 1104;
  reDtField05   = 1105;


  reStatus      = 2000;
  rePrMc        = 2001;
  reMcUsl       = 2002;
  reIndent      = 2003;
  reKatOtpEd    = 2004;
  reMcUslGr     = 2005;

  reRole1       = 2011;
  reRole2       = 2012;
  reRole3       = 2013;
  reRole4       = 2014;
  reRole5       = 2015;

  reCode1       = 2021;
  reCode2       = 2022;
  reCode3       = 2023;
  reCode4       = 2024;
  reCode5       = 2025;

  reValue1_Claim = 2031;
  reValue2_Claim = 2032;
  reValue3_Claim = 2033;
  reValue4_Claim = 2034;
  reValue5_Claim = 2035;

  reName        = 3000;

  reNoBound     = 4000;
  reToIndent    = 4001;
  reToIndentMc  = 4002;
  reToMc        = 4003;
  reToIndentFilter = 4004;
  reToFilter    = 4005;

	reDeleteCurrent = 4006;
  reInsertRecord  = 4007;
	reToResInfoMC   = 4008;
	reIsValid 			= 4009;

  reIndentParam  = 5000;
  rePrMcUslParam = 5001;
  reMcUslParam   = 5002;
  reSFiltersParam = 5003;
	reResInfoParam  = 5004;

  reSFiltersConst = 6001;

end

