const

  // числа
	rewTable   = 1001;
	rewTipKol  = 1002;
	reNpp      = 1003;

  // реал
	reKol      = 2001;
	rePrice    = 2002;

  // даты

	// времена

  // ссылки
  recRec     = 3001;
  recDopEd   = 3002;
  recMcDopEd = 3003;

  // наименования

	// ограничения и подцепки
  reNoBound          = 5000;
  reBySpDoc          = 5001;
  reBySpDocTipKol    = 5002;
  reByDopEd          = 5003;
  reByMCDopEd        = 5004;
  reBySpDocTipKolNpp = 5005;

	// параметры
	rewTableParam      = 7001;
  recRecParam        = 7002;
  rewTipKolParam     = 7003;
  recDopEdParam      = 7004;
  recMCDopEdParam    = 7005;
  rewNppParam        = 7006;

end
