const

  // числа
  reTip        = 1001;
  reDiskret    = 1002;
  rePrAvt      = 1003;
	reNpp        = 1004;

	rePrice      = 1501;
  reSumVal     = 1502;
  reGarant     = 1503;
  reSrPrice    = 1504;
  reSrVPrice   = 1505;
  reZPrice     = 1506;
  reZVPrice    = 1507;
	rePriceNum   = 1508;

  // даты
	redForm      = 2001;

	// логические
	reOnZavPrice = 2501;

  // ссылки
  recKlPrice   = 3001;
  recThing     = 3002;
  recVal       = 3003;
  recOtpEd     = 3004;
  recGroupMc   = 3005;
  recParty     = 3006;
  recGrUsl     = 3007;
	reKlPrParam  = 3008;
	reTypeParam  = 3009;
	reCodeVal    = 3010;
	reObjPar     = 3011;

  // наименования
  reName       = 4001;
  reBarKod     = 4002;
  reBarOtp     = 4003;
  reDopHar     = 4004;
  reNParty     = 4005;
  reKod        = 4006;

	// ограничения и подцепки
  reNoBound             = 5000;
  reToKlPrice           = 5001;
  reToKlPriceThing      = 5002;
  reToTipThing          = 5003;
	reToKlPricePartyThing = 5004;
	reToParty             = 5005;
	reToTipcGroupMC       = 5006;
	reToKlPricecGroupMC   = 5007;

	// быстрая навигация
	reByKlPriceNpp    = 6001;

	// параметры
  reTipParam        = 7101;
  reKlPriceParam    = 7102;
  reThingParam      = 7103;
	rePartyParam      = 7104;
	reGroupMCParam    = 7105;
	reNppParam        = 7106;
	// вставка и удаление записи
  reDeleteCurrent   = 7107;
  reInsertRecord    = 7108;

end
