const

  // числа
  refFact   = 0001;
  refTaked  = 0002;

  // Даты
  redFact     = 1001;
  redAccum    = 1002;
  redTake     = 1003;

  // ссылки
  recMC    = 2001;
  recPodr  = 2002;
  recMol   = 2003;
  recParty = 2004;
  recError = 2005;



  // наименования

  reNoBound     = 4000;
  reAddMc       = 4001;
  reSubMc       = 4002;
  reAddPodr     = 4003;
  reSubPodr     = 4004;
  reAddMOL      = 4005;
  reSubMOL      = 4006;
  reAddParty    = 4007;
  reSubParty    = 4008;

  reLookForSlit = 6001;

  recMCParam    = 12001;
  recPodrParam  = 12002;
  recMolParam   = 12003;
  recPartyParam = 12004;


end

