

const
  reBaseDocSumma    =  0001;
  reBaseDocSumVal   =  0002;
  reBaseDocKolKompl =  0003;
  reBaseDocSkidka   =  0004;
  reBaseDocNDS      =  0005;
  reBaseDocTOTAL    =  0006;
	reOtvPodr					=  0007;

  // Даты
  reBaseDocdPrice   = 1000;
  reBaseDocdForm    = 1001;
  reBaseDocdDoc     = 1002;
  reBaseDocdEnd     = 1003;
  reStepDocdIzvMax  = 1100;
  reStepDocdIzvFact = 1101;
  reStepDocdOplMax  = 1102;
  reStepDocdOplFact = 1103;
	reStepDocdOtgr    = 1104;
	reStepDocdZabor	  = 1105;

  reBaseDocName  = 2000;
  reBaseDocNoDoc = 2001;

  // ссылки
  reBaseDoccOrg        = 3000;
  reBaseDoccVal        = 3001;
  reBaseDoccCompl      = 3002;
  reBaseDoccDogovor    = 3003;
  reBaseDoccAppDogovor = 3004;
  reBaseDoccCalPlan    = 3005;
  reBaseDoccNote       = 3006;
  reBaseDoccPayment    = 3007;
  reBaseDocStatus      = 3008;
  reBaseDocVIDDOC      = 3009;
  reBaseDoccBank       = 3010;
  reBaseDoccDogAgr     = 3011;
  reBaseDoccMyBANK     = 3012;
  reBaseDoccGrPol      = 3013;
  reBaseDoccGrOtpr     = 3014;
  reBaseDocDirect      = 3015;
  reBaseDocTipMoney    = 3016;
	reBaseDoccNoteParam  = 3017;
	reBaseDocPodrTo      = 3018;
	reBaseDocSklad       = 3019;
	reBaseDocParty       = 3020;
  reBaseDoccNazna      = 3021;

  reBaseDocVhodNal     = 4001;
  reBaseDocShtraf      = 4002;
  reBaseDocVhSkid      = 4003;

  reBaseDocYearDoc     = 5001;
  reBaseDocKolDn       = 5002;

  reBaseDocNoBound     = 6000;
  reBaseDocVidDocAdd   = 6001;
  reBaseDocVidDocSub   = 6002;
  reBaseDocStatusAdd   = 6003;
  reBaseDocStatusSub   = 6004;
  reBaseDoccOrgAdd     = 6005;
  reBaseDoccOrgSub     = 6006;
  reBaseDocIntervalAdd = 6007;
  reBaseDocIntervalSub = 6008;
  reBaseDoccNoteAdd    = 6009;
  reBaseDoccNoteSub    = 6010;
  reBaseDoccPodrToAdd  = 6011;
  reBaseDoccPodrToSub  = 6012;
  reBaseDoccSkladAdd   = 6013;
  reBaseDoccSkladSub   = 6014;



  reBaseDocVidDocParam  = 7001;
  reBaseDocdBegParam    = 7002;
  reBaseDocdEndParam    = 7003;
  reBaseDocStatusParam  = 7004;
  reBaseDoccOrgParam    = 7005;
  reBaseDoccPodrToParam = 7006;
  reBaseDoccSkladParam  = 7007;

  reBaseDocVidDocConst = 9001;
  reBaseDocStatusConst = 9002;
  reBaseDoccNoteConst  = 9003;
end
