const

  // числа
	reType      = 1501;
	reTable     = 1502;
	reTypeObj   = 1503;
	reTypePodr  = 1504;
	reTypeParty = 1505;
	reTypePos   = 1506;
	reTypeMol   = 1507;

  // даты
	reBegDate   = 2001;
	reEndDate   = 2002;

  // ссылки
  recObject     = 3001;
  recPodr       = 3002;
  recParty      = 3003;
  recPos        = 3004;
  recMol        = 3005;
  recOwner      = 3006;

  // наименования
	reDescr      = 4001;
	reDesGr      = 4002;
	reCode       = 4003;
	reName       = 4004;

	// ограничения и подцепки
  reNoBound          = 5000;
	reToType           = 5001;
	reToTypeMc         = 5002;
	reToTypeMcOrg      = 5003;
	reToTypeMcMnfZakaz = 5004;
	reToTypeMcPodr     = 5005;

	// быстрая навигация
	reByTypeCode       = 6001;


	// параметры
	reTypeParam         = 7101;
	reTableParam        = 7102;
	reTypeOrgParam      = 7103;
	reTypeMnfZakazParam = 7104;
	reTypePodrParam     = 7105;
	reMcUslParam        = 7106;
	reOrgParam          = 7107;
	reMnfZakazParam     = 7108;
	rePodrParam         = 7109;
	reCodeParam         = 7110;

end

