const
  // числа (double)
  reSumOpl = 1001;
  reKYM    = 1002;
  redWord1 = 1003;
	redWord2 = 1004;
	redWord3 = 1005;

	// ссылки
	recTransp   = 2000;
	recPutLst   = 2001;
	recAppoint  = 2002;
	recPodr     = 2003;
	recperson   = 2004;
	recLschet   = 2005;
	recKnDriver = 2006;
	recAvans    = 2007;
	recVal      = 2008;
	recSpPrikaz = 2009;
	recWork1    = 2010;
	recWork2    = 2011;
	recWork3    = 2012;

  // даты
  reDatBeg = 2501;
  reDatEnd = 2502;

	// числа (word)
	reTypePers = 3000;
	reTABN     = 3001;
	rewWord1   = 3002;
	rewWord2   = 3003;
	rewWord3   = 3004;

	// строки
	reTEL     = 4000;
	reFIO     = 4001;
	reStrTabN = 4002;

	// параметры
	recTranspParam   = 6000;
	recPutLstParam   = 6001;
	recAppointParam  = 6002;
	recPersonParam   = 6003;
	recKnDriverParam = 6004;
	rewTypePersParam = 6005;

	// ограничения
	reNoBound             = 7000;
	reByTransp            = 7001;
	reByTranspTypeP       = 7002;
	reByTranspTypePApp    = 7003;
	reByTranspTypePAppPL  = 7004;
	reByTranspPL          = 7005;
	reByTranspPLTypeP     = 7006;
	reByTranspPLTypePPers = 7007;
	reByKnDriver          = 7008;
	reByPerson            = 7009;
	reByPutLst            = 7010;
end
