const

  // числа
  reKol   = 0001;
  reRes   = 0002;

  // Даты
  redGodn     = 1001;

  // ссылки
  recMC    = 2001;
  recPodr  = 2002;
  recMol   = 2003;
  recParty = 2004;

  // признаки всякие
  reSP             = 3001;  // Word  "склад/производство", 0-склад 1-производство

  // наименования

  reNoBound        = 4000;
  reAddMc          = 4001;
  reSubMc          = 4002;
  reAddPodr        = 4003;
  reSubPodr        = 4004;
  reAddMOL         = 4005;
  reSubMOL         = 4006;
  reAddParty       = 4007;
  reSubParty       = 4008;
  reAdd_SP         = 4009;
  reSub_SP         = 4010;

  reLookForSlit    = 6001;
  reLookForSlit_SP = 6002;

  recMCParam       = 12001;
  recPodrParam     = 12002;
  recMolParam      = 12003;
  recPartyParam    = 12004;
  reSPParam        = 12005;  // Word  "склад/производство", 0-склад 1-производство


end

