const

  reAdvField1     = 0101;
  reAdvField2     = 0102;
  reAdvField3     = 0103;
  reAdvField4     = 0104;
  reAdvField5     = 0105;
  reAdvField6     = 0106;
  reAdvField7     = 0107;

  reStartDate     = 1000;
  reEndDate       = 1001;
  reStatemDate    = 1002;
  reStartDateFact = 1003;
  reEndDateFact   = 1004;
  reUtvDate       = 1005;

  rePrior       = 2000;
  reStatus      = 2001;
  reTemplate    = 2002;
  rePlanType    = 2003;
	recvPlan      = 2004;
  reTemplate_   = 2005;

  reRole1       = 2011;
  reRole2       = 2012;
  reRole3       = 2013;
  reRole4       = 2014;
  reRole5       = 2015;

  reCode1       = 2021;
  reCode2       = 2022;
  reCode3       = 2023;
  reCode4       = 2024;
  reCode5       = 2025;

  reValue1_MnPlan = 2031;
  reValue2_MnPlan = 2032;
  reValue3_MnPlan = 2033;
  reValue4_MnPlan = 2034;
  reValue5_MnPlan = 2035;

	reKatPodr     = 2036;
	reSloj        = 2037;

  rewKodGr1Bound = 2038;
  rewKodGr2Bound = 2039;
  rewKodGr3Bound = 2040;
  rewKodGr4Bound = 2041;
  rewKodGr5Bound = 2042;

  recAnVal1Bound = 2043;
  recAnVal2Bound = 2044;
  recAnVal3Bound = 2045;
  recAnVal4Bound = 2046;
  recAnVal5Bound = 2047;

  reDocNum     = 3000;
  reName       = 3001;

  reNoBound     = 4000;
  reByType      = 4001;
  reByTypePrior = 4002;
  reByTypeStatus= 4003;
  reByTepmlate  = 4004;
  reByTypeNumber= 4005;
  reNewRecord   = 4006;

  reByAnalitic1AndTemplate = 4010;
  reByAnalitic12AndTemplate = 4011;
  reByAnalitic123AndTemplate = 4012;
  reByAnalitic1234AndTemplate = 4013;
  reByAnalitic12345AndTemplate = 4014;

  reTypeParam      = 5001;
  reTemplateParam  = 5002;
  rePriorParam     = 5003;
  reStatusParam    = 5004;
  reNumberParam    = 5005;


  reStatusPlan = 6000;
  reStatusZakaz = 6001;
  reStatusNeedMt = 6002;

  reTemplateCo  = 6003;
  rePlanTypeCo  = 6004;
  recvPlanConst = 6005;
end
