const


  // ссылки
  reVidDoc    = 2001;
  reStatus    = 2002;
  reIsLeaf    = 2003;
  recOwner    = 2004;
  reControl   = 2005;

  // строки
  reCode      = 3001;
  reName      = 3002;
  resName     = 3003;

  reNoBound     = 5000;

  reByVidDoc        = 5001;
  reByVidDocStatus  = 5002;
  reByVidDocOwner   = 5003;

  reVidDocParam     = 6001;
  reStatusParam     = 6002;
  reOwnerParam      = 6003;

  reVidDocConst     = 7001;

end

