const
  reSpObjAccKolcPos     = 0001;
  reSpObjAccKolcFact    = 0002;
  reSpObjAccKolcPos_     = 0101;
  reSpObjAccKolcFact_    = 0102;

  reSpObjAccStartDate   = 1000;
  reSpObjAccEndDate     = 1001;
  reSpObjAccdOpr        = 1002;
  reSpObjAccStartDate_   = 1100;
  reSpObjAccEndDate_     = 1101;
  reSpObjAccdOpr_        = 1102;

  reSpObjAcccObjAcct     = 2000;
  reSpObjAccKindRec      = 2001;
  reSpObjAccTypeNorm     = 2002;
  reSpObjAccTypePos      = 2003;
  reSpObjAcccPos         = 2004;
  reSpObjAccTypeEd       = 2005;
  reSpObjAcccOtpEd       = 2006;
  reSpObjAccCondRec      = 2007;
  reSpObjAccTypeObj      = 2008;
  reSpObjAcccObject      = 2009;
  reSpObjAccTypeHier     = 2010;
  reSpObjAcccSpObjAcc    = 2011;
  reSpObjAccVidSopr      = 2012;
  reSpObjAccNumSort      = 2013;
  reSpObjAcccBaseDoc     = 2014;
  reSpObjAcccKatSopr     = 2015;

	reRole1       = 2016;
  reRole2       = 2017;
  reRole3       = 2018;
  reRole4       = 2019;
  reRole5       = 2020;
  reCode1       = 2021;
  reCode2       = 2022;
  reCode3       = 2023;
	reCode4       = 2024;
  reCode5       = 2025;
  reValue1      = 2031;
  reValue2      = 2032;
  reValue3      = 2033;
	reValue4      = 2034;
  reValue5      = 2035;

  reSpObjAcccObjAcct_     = 2100;
  reSpObjAccKindRec_      = 2101;
  reSpObjAccTypeNorm_     = 2102;
  reSpObjAccTypePos_      = 2103;
  reSpObjAcccPos_         = 2104;
  reSpObjAccTypeEd_       = 2105;
  reSpObjAcccOtpEd_       = 2106;
  reSpObjAccCondRec_      = 2107;
  reSpObjAccTypeObj_      = 2108;
  reSpObjAcccObject_      = 2109;
  reSpObjAccTypeHier_     = 2110;
  reSpObjAcccSpObjAcc_    = 2111;
  reSpObjAccVidSopr_      = 2112;
  reSpObjAccNumSort_      = 2113;
  reSpObjAcccBaseDoc_     = 2114;
  reSpObjAcccKatSopr_     = 2115;

	reRole1_       = 2116;
  reRole2_       = 2117;
  reRole3_       = 2118;
  reRole4_       = 2119;
  reRole5_       = 2120;
  reCode1_       = 2121;
  reCode2_       = 2122;
  reCode3_       = 2123;
	reCode4_       = 2124;
  reCode5_       = 2125;
  reValue1_      = 2131;
  reValue2_      = 2132;
  reValue3_      = 2133;
	reValue4_      = 2134;
  reValue5_      = 2135;

  // reSpObjAccName        = 3000;

  reSpObjAccNoBound     = 4000;
  reSpObjAccObjAcct     = 4001;
  reSpObjAccObjPos1     = 4002;
  reSpObjAccObjPos2     = 4003;
  reSpObjAccPosObj1     = 4004;
  reSpObjAccPosObj2     = 4005;
  reSpObjAccObjAcct2    = 4006;
  reSpObjAccSpObjAcc    = 4007;

  reSpObjAccDelCur      = 4101;

  reSpObjAccNew         = 4102;
  reSpObjAccNewViaBuff  = 4103;
  reSpObjAccNewWithHead = 4104;
  reSpObjAccNewBlank    = 4105;
	reSpObjAccNewWithOut  = 4106;

  reSpObjAccDelNew      = 4107;


  reSpObjAccSearch        = 4201;
  reSpObjAccSearchViaBuff = 4202;
  reSpObjAccSearchWithHead= 4203;

  reSpObjAccDocObjAcct      = 5001;
  reSpObjAccTypePosParam    = 5002;
  reSpObjAccDocPosParam     = 5003;
  reSpObjAccTypeObjParam    = 5004;
  reSpObjAccDocObjParam     = 5005;
  reSpObjAccSpObjAccParam   = 5006;

  reSpObjAccObjAcctBuffParam   = 5010;
  reSpObjAccPosBuffParam    = 5011;
  reSpObjAccObjBuffParam    = 5012;

  reSpObjAccTypeForObjPos   = 6001;
end
