const

  // числа (double)
  reOW           = 1001;
  reVidT         = 1002;
  reSdanT        = 1003;
  reNormT        = 1004;
  reFaktT        = 1005;
  reOWV          = 1006;
  reSpeedZap     = 1007;
  reKolForRas    = 1008;
  rePriceGsm     = 1009;
  rePriceGsmVal  = 1010;
  rePriceGsmReal = 1011;
  rePriceTop     = 1012;
  rePriceTopVal  = 1013;
  rePriceTopReal = 1014;
  reValCurse1    = 1015;
  reValCurse2    = 1016;
  reValCurse12   = 1017;
  reCorPrc       = 1018;
  reKofN         = 1019;
  retimeAll      = 1020;
  retimemove     = 1021;
  retimestop     = 1022;
  retimerep      = 1023;
  retimeheat     = 1024;
  retimespec     = 1025;
  retimeload     = 1026;
  retimePg       = 1027;
  retimeRz       = 1028;
  retimedef      = 1029;
  retimeEngine   = 1030;
  reKolEz        = 1031;
  reprobegall    = 1032;
  reprobegTam    = 1033;
  reprobegV      = 1034;
  reProbeggr     = 1035;
  reProbegGrPri  = 1036;
  reProbegWrk    = 1037;
  reVolWrk       = 1038;
	reGruzTn       = 1039;
	reGruzTnPri    = 1040;
	reGruzTnkm     = 1041;
	reGruzTnkmPri  = 1042;
	reInterWay     = 1043;
	reHourKm       = 1044;
	reWeight       = 1045;
	reGruzPod      = 1046;
	reWeight0      = 1047;
	reGruzPod0     = 1048;
	reWeight1      = 1049;
	reGruzPod1     = 1050;
	reWeight2      = 1051;
	reGruzPod2     = 1052;
	reprobeg1      = 1053;
	reprobeg2      = 1054;
	rePriceZapr    = 1055;
	rePriceOW      = 1056;
	rePriceTopZapr = 1057;
	rePriceTopOW   = 1058;
	reNlProbeg     = 1059;
	retemper       = 1060;
	repok1RB       = 1061;
	repok2RB       = 1062;
	repok3RB       = 1063;
	repok4RB       = 1064;
	repok5RB       = 1065;
	repok1CNG      = 1066;
	repok2CNG      = 1067;
	repok3CNG      = 1068;
	repok4CNG      = 1069;
	repok5CNG      = 1070;
	repok1Ino      = 1071;
	repok2Ino      = 1072;
	repok3Ino      = 1073;
	repok4Ino      = 1074;
	repok5Ino      = 1075;
	reDpPokaz1     = 1076;
	reDpPokaz2     = 1077;
	reDpPokaz3     = 1078;
	reDpPokaz4     = 1079;
	reDpPokaz5     = 1080;
	reBegDensity   = 1081;
	reEndDensity   = 1082;
	reDensity      = 1083;


  // числа (word)
  reTipGsm   = 1501;
  reNalCheck = 1502;
  reEdinRas  = 1503;
  reTipInfo  = 1504;
  reWhereGSm = 1505;
  reDpPokaz8 = 1506;
  reDpPokaz9 = 1507;
	reNpp      = 1508;


  // времена
  reLastTime = 2001;
  reZaprCh   = 2002;


  // даты
  reLastDate = 2501;
  reDateR 	 = 2502;
  reZaprDn 	 = 2503;

  // ссылки
  reFilialNo    = 3001;
  recPutlst     = 3002;
  recKatZak     = 3003;
  recSpZakaz    = 3004;
  recSoprDop    = 3005;
  recToplivo    = 3006;
  recOrg        = 3007;
  recVal        = 3008;
  recVal2       = 3009;
  reCardRec     = 3010;
  recOtpEd      = 3011;
  recWayItemBeg = 3012;
  recStateBeg   = 3013;
  recCityBeg    = 3014;
  recWayItemEnd = 3015;
  recStateEnd   = 3016;
  recCityEnd    = 3017;
  recMaravt     = 3018;
  recWayItem    = 3019;
	recWayPath    = 3020;
	recState      = 3021;
	recCity       = 3022;
	recRashDoc    = 3023;
	recGsmAlg     = 3024;
	recOrg_Zapr   = 3025;
	recSave_Drv   = 3026;
	recWayWps     = 3027;
	recAgregat    = 3028;
	recKredCard   = 3029;
	reDpPokaz6    = 3030;
	reDpPokaz7    = 3031;
	reDpPokaz10   = 3032;
	reDpPokaz11   = 3033;
	reDpPokaz12   = 3034;
	recSpSklad    = 3035;
	recParty      = 3036;
	rectransp     = 3037;


  // наименования
  reLastUser = 4001;
  reCardNum  = 4002;

  // ограничения и подцепки
  reNoBound    = 5000;
	reToBounds02 = 5001;
	reToBounds03 = 5002;
	reToBounds05 = 5003;
	reToBounds06 = 5004;
	reToBounds08 = 5005;
	reToBounds09 = 5006;
	reToBounds10 = 5007;
	reToBounds11 = 5008;
	reToBounds12 = 5009;
	reToBounds13 = 5010;
	reToBounds14 = 5011;
	reToBounds15 = 5012;
	reToBounds16 = 5013;
	reToBounds17 = 5014;
	reToBounds18 = 5015;
	reToBounds19 = 5016;
	reToBounds20 = 5017;
	reToBounds21 = 5018;
	reToBounds22 = 5019;

	// быстрая навигация

	// параметры
	reTipInfoParam   = 7001;
	reTipGsmParam    = 7002;
	reNppParam       = 7003;
	recPutlstParam   = 7004;
	recToplivoParam  = 7005;
	recOrgParam      = 7006;
	recSoprDopParam  = 7007;
	recAgregatParam  = 7008;
	recWayWpsParam   = 7009;
	recOtpEdParam    = 7010;
	recOrg_ZaprParam = 7011;
	recSpZakazParam  = 7012;
	recSpSkladParam  = 7013;
	reCardRecParam   = 7014;
	recPartyParam    = 7015;
	rectranspParam   = 7016;
	reZaprDnParam    = 7017;
	reZaprChParam    = 7018;

end

