const
	reType1        = 100;
	reType2        = 101;
	reType3        = 102;
	reNum          = 103;
	retDep         = 104;
	rewOpe         = 105;
	reEdNorm       = 106;
	reRazr         = 107;
	reIspo         = 108;
	reActive       = 109;
	reStatus       = 110;

	reValue1_KatMarshSp = 2001;
  reValue2_KatMarshSp = 2002;
  reValue3_KatMarshSp = 2003;

	reRole1        = 2004;
	reRole2        = 2005;
	reRole3        = 2006;

	recMarsh       = 2007;
	recDep         = 2008;
	reNope         = 2009;
	recEd          = 2010;
	reCasupMem     = 2011;

	reDtBeg        = 3000;
	reDtEnd        = 3001;

	resNumEx       = 4000;

	recMarsh_      = 5000;
	reNum_         = 5001;
	retDep_				 = 5002;
	recDep_        = 5003;
	reNope_				 = 5004;
	reWope_				 = 5005;
	resNumEx_      = 5006;

	reToMarsh      = 6000;
	reTotDep       = 6001;
	reToNope       = 6002;
	reToWope       = 6003;
	reToNumEx      = 6004;
	reNoBound      = 6005;
end
