const

  // числа
	reN24H   = 1001;
	reID     = 1002;
	reVid    = 1003;
  rewTable = 1004;

  // даты

	// времена

  // ссылки
  recDoc        = 3001;
  recShbUsl     = 3002;
  recTipUsl     = 3003;
  recKatUsl     = 3004;

  // наименования
	reKatParID   = 4001;
	reLValue      = 4002;

	// ограничения и подцепки
  reNoBound            = 5000;
  reByTableDoc         = 5001;
  reByTableDocId       = 5002;
  reByKatParIDTableDoc = 5003;

	// параметры
	rewTableParam        = 6001;
	recDocParam          = 6002;
  reIDParam            = 6003;
  resKatParIDParam     = 6004;

end
