const

  // числа
	reType      = 1501;
	reStatus    = 1502;
	reTable     = 1503;

  // даты
	reDocDate   = 2001;

	// времена
	reDocTime   = 2501;

  // ссылки
  recPrKachvo   = 3001;
  recTsKachvo   = 3002;
  recOwner      = 3003;
  recStatus     = 3004;

  // наименования
	reDescr      = 4001;
	reDesGr      = 4002;
	reCode       = 4003;

	// ограничения и подцепки
  reNoBound    = 5000;
	reToType     = 5001;
	reToTypeMc   = 5002;
	reToPrKachvo = 5003;
	reToTsKachvo = 5004;

	// быстрая навигация

	// параметры
	reTypeParam     = 7101;
	reTableParam    = 7102;
	reMcUslParam    = 7103;
	rePrKachvoParam = 7104;
	reTsKachvoParam = 7105;

end

