const

  // числа
	reKodGrKau   = 1001;
	reValue      = 1501;

  // даты

  // ссылки
  recQPHead    = 3001;
  recKatPokaz  = 3002;
  recKatKau    = 3003;
  recKau       = 3004;

  // наименования
	reDescr      = 4001;
	reDesGr      = 4002;
	reNumber     = 4003;

	// ограничения и подцепки
  reNoBound    = 5000;
	reToQPHead   = 5001;

	// быстрая навигация
	reByQPHeadPokaz   = 6001;

	// параметры
	reQPHeadParam     = 7101;
	rePokazParam      = 7102;

end

