const
  rewKodGr1    = 1001;
  rewKodGr2    = 1002;
  rewKodGr3    = 1003;
  rewKodGr4    = 1004;
  rewKodGr5    = 1005;
  relNum       = 1006;
  rePLPosition = 1007;
  rewDet       = 1008;
  retDoc       = 1009;
  retDocAdd    = 1010;
  rewPodr      = 1011;
  reZamEn      = 1012;
  rePRODUCT    = 1013;
  rewProd      = 1014;
  reIspoln     = 1015;
  reActive     = 1016;
  rewPS_Lines  = 1017;
  rewSrcText   = 1018;
  rewSrcMode   = 1019;
  reZapPost    = 1020;
  reTimePostEd = 1021;
  rewScale     = 1022;
  rewToCost    = 1023;
  rewFixNQnt   = 1024;
  rewRoundUp   = 1025;
  rewResLevel  = 1026;
  reDZona      = 1027;
  reStatus     = 1028;

  reKol       = 2001;
  reProcent   = 2002;
  reKoef      = 2003;
  reProcEx    = 2004;
  reTimePost  = 2005;
  redPlanProc = 2006;
  redMinNQnt  = 2007;
  redMaxNQnt  = 2008;

  reDescr   = 3001;
  reDesGr   = 3002;
  reDFormat = 3003;
  reFormula = 3004;
  rePCode   = 3005;
  resVNom   = 3006;

  recRoleAn1   = 4001;
  recRoleAn2   = 4002;
  recRoleAn3   = 4003;
  recRoleAn4   = 4004;
  recRoleAn5   = 4005;
  recAnVal1    = 4006;
  recAnVal2    = 4007;
  recAnVal3    = 4008;
  recAnVal4    = 4009;
  recAnVal5    = 4010;
  recHDR       = 4011;
  recPart      = 4012;
  recDet       = 4013;
  recDoc       = 4014;
  recDocAdd    = 4015;
  recEd        = 4016;
  recPodr      = 4017;
  recSklad     = 4018;
  rePLMemo     = 4019;
  recRoot      = 4020;
  recNotice    = 4021;
  recState     = 4022;
  recPS_Lines  = 4023;
  recSrcText   = 4024;
  recVariant   = 4025;
  recUpResNorm = 4026;

  redtBeg = 5001;
  redtEnd = 5002;

  reNoScheme = 6001;
  rebSelect  = 6002;
  rebAlter   = 6003;

	reNoBound  = 7000;
	reToHDR    = 7001;
	reToHDRDet = 7002;
  reToDet    = 7003;

  recMarsh_ = 7101;
  recDet_   = 7102;
  recHDR_   = 7103;
  rewDet_   = 7104;
end
