const
  reKolDoc      	= 1;
  rePrice    			= 2;
  reTrimPrice   	= 3;
  rePriceVal    	= 4;
	reTrimPriceVal	= 5;

  reDateSopr	  = 1000;
  reDateOpr     = 1001;

  reKatEd       = 2000;
  reMc        	= 2001;
  reSklad       = 2002;
  reMOL         = 2003;
  reParty    		= 2004;
	reMtrAct      = 2005;

  reNPP         = 3000;

  reNoBound     = 4000;
  reToMtrAct    = 4001;
	reIsValid  	 	= 4002;

  reMtrActParam  = 5000;
end

