Const

  // cтроки
  reName    = 1001;
  reNazCode = 1002;

  // ссылки
  recOwner  = 2001;
  recStZatr = 2002;
  recSmet   = 2003;

  // числа
  relNazCode = 3001;
  reVidNazn  = 3002;
  reVidRasx  = 3003;

  // ограничения
  reNoBound = 4001;
  reByOwner = 4002;

  // быстрая навигация
  reByName    = 4501;
  reByNazCode = 4502;

  // параметры
  reNameParam    = 5001;
  reNazCodeParam = 5002;
  recOwnerParam  = 5101;

end
