const

	// ссылки
	reKodTar    = 2000;
	recKlVidOpl = 2001;
	recKatUsl   = 2002;

	// числа
	recKodGr01 = 3000;
	recKodGr02 = 3001;
	recKodGr03 = 3002;
	recKodGr04 = 3003;

	// строки
	resShortName = 4000;
	resName      = 4001;
	resNmGr01    = 4002;
	resNmGr02    = 4003;

	// параметры
	reKodTarMinParam = 6000;
	reKodTarMaxParam = 6001;
	recKatUslParam   = 6002;
	recKlVidOplParam = 6003;

	// ограничения
	reNoBound       = 7000;
	reByKatUsl      = 7001;
	reByKlVidOpl    = 7002;
	reByKodTarRange = 7003;
end
