const

  // числа
	reValueMain   = 1001;
	reTable       = 1501;
	reKodGrKau    = 1502;
	reConfirm     = 1503;
	rePassport    = 1504;

  // даты

	// времена

  // ссылки
  recRezKontr   = 3001;
  recKatPokaz   = 3002;
  recKatKau     = 3003;
  recKau        = 3004;
  recOwner      = 3005;

  // наименования
	reCodePokaz   = 4001;
	reNamePokaz   = 4002;

	// ограничения и подцепки
  reNoBound          = 5000;
	reToRezKontr       = 5001;

	// быстрая навигация
	reByRezKontrPokaz  = 6001;
	reByRezKontrKatKau = 6002;

	// параметры
	recRezKontrParam   = 7101;
	recPokazParam      = 7102;
	recKatKauParam     = 7103;

end
