const

  reKol           = 1;
  reDlit1         = 2;
	reDlit2         = 3;
	reDlit3         = 4;

  reStatus        = 101;
  reNumFldSpDoc   = 102;
	reState         = 103;

	reComment       = 500;

  reStartDateTime = 1000;
  reEndDateTime   = 1001;
	reStartDate     = 1101;
  reEndDate       = 1102;
	rePlanStartDateTime = 1103;
	rePlanEndDateTime  = 1104;

  reTypeDoc       = 2000;
  reDoc           = 2001;
  reSpDoc         = 2002;
  reOtpEd         = 2003;
  reTypeIzd       = 2004;
  reIzd           = 2005;
  reOperate       = 2006;
	rePC            = 2007;
	reParty         = 2008;
	reRegState      = 2009;
	reHiRsv         = 2010;
	reVariaPl       = 2011;
	rePartyRsv      = 2012;

  reNoBound       = 3000;
  reByTypeDoc     = 3001;
	reByWrkFnd      = 3002;
	reByTypeDocPos  = 3003;
	reByHiRsv       = 3004;
	reByPartyRsv    = 3005;

	reTypeDocParam  = 4000;
	reWrkFndParam   = 4001;
	rePosDocParam   = 4002;
	reHiRsvParam    = 4003;
	reByPartyRsvParam  = 4004;

end

