const
	//
  reName      = 1000;
  reComment   = 1001;
	//
  reStartDate = 2000;
	//
  renRec      = 1;
  reKindRec   = 3000;
	reCondRec   = 3001;
  reTypeHier  = 3002;
  reTypeOwn   = 3003;
	recOwner    = 3004;
  recOwnerDop = 3005;
  reTypeObj   = 3006;
  recObject   = 3007;
	recRoleAn1  = 3008;
	rewKodGr1   = 3009;
	recAnVal1   = 3010;
	recRoleAn2  = 3011;
	rewKodGr2   = 3012;
	recAnVal2   = 3013;
	recRoleAn3  = 3014;
	rewKodGr3   = 3015;
	recAnVal3   = 3016;
	recRoleAn4  = 3017;
	rewKodGr4   = 3018;
	recAnVal4   = 3019;
	recRoleAn5  = 3020;
	rewKodGr5   = 3021;
	recAnVal5   = 3022;
  recObjParam = 3023;

  reNoBound   = 4000;
  reToPlan    = 4001;
  reToPlanObj = 4002;

  rePlanP1    = 5001;
  rePlanObjP1 = 5002;
  rePlanObjP2 = 5003;
  rePlanObjP3 = 5004;

end;

