const

	reOfsByOut  = 1;     // double
	reTimeRq    = 2;
	reTotalTime = 3;
	reNormCount = 4;

	reType      = 101;   //integer
	reTypeOwn   = 102;
	reTypeNorm  = 103;

	reRefBor    = 2000;   // getprimereference
	reRefRes    = 2001;
	reRefBor_P  = 2002;
	reRefOwn    = 2003;
	reRefOper   = 2004;
	reRefMsrUnit  = 2005;
	reRefBorP_Own = 2006;


	reNoBound     =  3000;   //bounds
	reByType      =  3001;
	reByTemplate1 =  3002;
	reByTemplate2 =  3003;
	reByTemplate3 =  3004;
	reByTemplate4 =  3005;
	reByTemplate5 =  3006;
	reByTemplate6 =  3007;

	reRefBorParam   = 4000;  //setprimereference
	reRefResParam   = 4001;
	reRefBorP_Param = 4002;
	reRefOwnParam   = 4003;
	reRefOperparam  = 4004;
	reTypeOwnParam  = 4005;
	reTypeParam     = 4006;


end

