const

  // числа (double)
  reSpeedExi    = 1001;
  reSpeedRet    = 1002;
  reTimeall     = 1003;
  rePrprc       = 1004;
  retimemove    = 1005;
  retimestop    = 1006;
  retimerep     = 1007;
  retimeheat    = 1008;
  retimespec    = 1009;
  retimeload    = 1010;
  retimePg      = 1011;
  retimeRz      = 1012;
  retimedef     = 1013;
  reKolEz       = 1014;
  reKolza       = 1015;
  reprobegall   = 1016;
  reprobegV     = 1017;
  reProbeggr    = 1018;
  reProbegGrPri = 1019;
  reGruzTn      = 1020;
  reGruzTnPri   = 1021;
  reGruzTnkm    = 1022;
  reGruzTnkmPri = 1023;
  reSumUsl      = 1024;
  reSUMOPL1     = 1025;
  reSUMOPL2     = 1026;
  reSumUslVal   = 1027;
  reSumOpl1Val  = 1028;
  reSumOpl2Val  = 1029;
  renpVir       = 1030;
  refkVir       = 1031;
  renpVirVal    = 1032;
  refkVirVal    = 1033;
  reTimeRaz     = 1034;
  reTimeR1      = 1035;
  reTimeR2      = 1036;
  reTimeNorma   = 1037;
  reTimeKar     = 1038;
	repok1RB      = 1039;
	repok2RB      = 1040;
	repok3RB      = 1041;
	repok4RB      = 1042;
	repok5RB      = 1043;
	repok1CNG     = 1044;
	repok2CNG     = 1045;
	repok3CNG     = 1046;
	repok4CNG     = 1047;
	repok5CNG     = 1048;
	repok1Ino     = 1049;
	repok2Ino     = 1050;
	repok3Ino     = 1051;
	repok4Ino     = 1052;
	repok5Ino     = 1053;
	reDpPokaz1    = 1054;
	reDpPokaz2    = 1055;
	reDpPokaz3    = 1056;
	reDpPokaz4    = 1057;
	reDpPokaz5    = 1058;
	reTimeHoli    = 1059;
	reTimeSovm    = 1060;
	reTimeWeek    = 1061;
	reTimeStVd    = 1062;
	reTimeStNoVd  = 1063;
	reTimeDn      = 1064;
	reTimePri     = 1065;
	reTimeNoPri   = 1066;
	reTimeSvur    = 1067;
	rePrSovm      = 1068;
	reTimeRepVD   = 1069;
	reTimeRepNoVd = 1070;

  // числа (word)
  reKformpl  = 1501;
  reStatPl   = 1502;
  reTipUsl   = 1503;
  reAvDn     = 1504;
  reMesObr   = 1505;
  reDpPokaz8 = 1506;
  reDpPokaz9 = 1507;

  // времена
  reExitCh   = 2001;
  reReturnCh = 2002;

  // даты
  reDatPl    = 2501;
  reDatObr   = 2502;
  reDatRas   = 2503;
	reExitDn   = 2504;
  reReturnDn = 2505;

  // ссылки
  reCEX1     = 3001;
  recPodr1   = 3002;
  reCEX2     = 3003;
  recPodr2   = 3004;
  recperson1 = 3005;
  recKarVod1 = 3006;
  recperson2 = 3007;
  recKarVod2 = 3008;
  recMarka   = 3009;
  recTiptex  = 3010;
  recPol     = 3011;
  recVal     = 3012;
  recAvtoSt  = 3013;
  recTransp1 = 3014;
  recTransp2 = 3015;
  recTrlMem  = 3016;
  reDpPokaz6 = 3017;
  reDpPokaz7 = 3018;

  // наименования
  reNPL      = 4001;
  reNseria   = 4002;
	reGNom     = 4003;
  reStrTabn1 = 4004;
	reStrTabn2 = 4005;


  // ограничения и подцепки
  reNoBound    = 5000;
	reToBounds01 = 5001;
  // быстрая навигация


  // параметры
	recAvtoStParam = 7001;
	recMarkaParam  = 7002;
end

