//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Электронная отчетность ГОЗ"
// Библиотека функций : "Проверка XML по XSD"
//------------------------------------------------------------------------------

#ifndef __gzrFuncXSDCheck_Inc__
#define __gzrFuncXSDCheck_Inc__

const
  // targetNamespace
  lc_TargetNameSpace = 'http://mil.ru/discreteAccounting';
end; // const

#endif//__gzrFuncXSDCheck_Inc__
