//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 5.80 - модуль "Платежный календарь"
// Фильтры для интерфейса выбора
//------------------------------------------------------------------------------

Const
  cgFlViewPos_Descr     =  0; // дескриптор
  cgFlViewPos_DesGr     =  1; // группа
  cgFlViewPos_Date      =  2; // дата создания
  cgFlViewPos_DatePay   =  3; // планируемая дата погашения
  cgFlViewPos_Summa     =  4; // сумма по финобязательству
  cgFlViewPos_Direct    =  5; // направление
  cgFlViewPos_Status    =  6; // статус
  cgFlViewPos_Prior     =  7; // приоритет
  cgFlViewPos_KatOrg    =  8; // контрагент
  cgFlViewPos_FpCO      =  9; // центр ответственности
  cgFlViewPos_Dogovor   = 10; // договор
  cgFlViewPos_BaseDoc   = 11; // документ-основание
  cgFlViewPos_Persons   = 12; // куратор
  cgFlViewPos_GroupOfp  = 13; // группа  ФОБ
  cgFlViewPos_AktSum    = 14; // сводное ФОБ
  cgFlViewPos_FactSym   = 15; // признак исполнения
  cgFlViewPos_FpStBud   = 16; // статья бюджета
  cgFlViewPos_Valuta    = 17; // валюта операции
  cgFlViewPos_MeanType  = 18; // тип платежного средства
End;
