//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Электронная отчетность РБ"
// Интерфейс редактирования : "Алгоритм расчета"
//------------------------------------------------------------------------------

#ifndef __TRBEditAlgorithmRec_Inc__
#define __TRBEditAlgorithmRec_Inc__

const
  lc_PATMemoEditorID = 'PATMemoEditorID';

  cmJumpToPosAlgCode : word = 6001;
end; // const

#endif//__TRBEditAlgorithmRec_Inc__
