//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Электронная отчетность РБ"
// Persistent Object Manager : "Алгоритмы расчета"
//------------------------------------------------------------------------------

#ifndef __TRBPersAlgorithm_Inc__
#define __TRBPersAlgorithm_Inc__

// ГЕНЕРАЦИЯ GUID :: BuhXml_CreateGUID36
const
  // Декларация по НДС
  lc_TRBAlg_NDS_Grp_GUID      = '474B340B-27E1-4ADC-A92D-2ED1864A352A';
  lc_TRBAlg_NDS_Grp_v001_GUID = 'E330EF03-10CF-4C38-B748-0F7A10C22AD2';
  lc_TRBAlg_NDS_Alg_v001_GUID    = '23BEE6E3-AFBE-4F23-975F-122D6D6B6B77';
  lc_TRBAlg_NDS_AlgAdd_v001_GUID = 'F6DEF5D0-BE34-4CB6-82BB-D18E69FAC34C';
end; // const

#endif//__TRBPersAlgorithm_Inc__
