const

  // числа

  // Даты

  // ссылки

  // вставка и удаление записи
  reDeleteRecord = 2008;
  reInsertRecord = 2009;

  // наименования
  recOwner     = 3000;
  recObj       = 3001;
  reVidObj     = 3002;
  recUsl       = 3003;
  recOtpEd     = 3004;
  recInSpSopr  = 3005;
  recOutSpSopr = 3006;
  recFpCO      = 3007;
  redPay       = 3008;
  redFrom      = 3009;
  redTo        = 3010;
  rewYear      = 3011;
  rewMonth     = 3012;
  reKol        = 3013;
  reKolOpl     = 3014;
  rePrice      = 3015;
  rePriceOpl   = 3016;
  resNum       = 3017;

  // ограничения
  reByRooms    = 4001;

  // параметры
  repcOwner      = 5001;
  repcUsl        = 5002;
  repComPayOwner = 5003;
  repRoom        = 5004;
  repCO          = 5005;
  repdFrom       = 5006;
  repdTo         = 5007;
  repPrice       = 5008;
  repKol         = 5009;

end
