const

  // числа

  // Даты

  // ссылки

  // наименования
  recBuilding = 3000;
  recFloor    = 3001;
  recHouse    = 3002;
  recFpCO     = 3003;
  reNoFact    = 3004;
  reNoBTI     = 3005;
  rewPurposes = 3006;
  repPurposes = 3007;
  rewNazna    = 3008;

  // ограничения
  reByBuilding   = 4001;
  reByFloor      = 4002;

  // параметры
  repBuilding    = 5001;
  repFloor       = 5002;
  
end
