const

  // числа

  // Даты

  // ссылки

  // наименования
  reVidObj      = 3000;
  recObj        = 3001;
  renpp         = 3002;
  reOperation   = 3003;
  redFrom       = 3004;
  recFpCO       = 3005;
  recDogovor    = 3006;
  redDoc        = 3007;
  reNoDoc       = 3008;
  rewPurposes   = 3009;
  repPurposes   = 3010;
  reComments    = 3011;
  redTo         = 3012;
  recoValues_1  = 3013;
  recoValues_2  = 3014;
  recoValues_3  = 3015;
  recoValues_4  = 3016;
  recoValues_5  = 3017;
  recoValues_6  = 3018;
  recoValues_7  = 3019;
  recoValues_8  = 3020;
  recoValues_9  = 3021;
  recoValues_10 = 3022;
  rewValues_1   = 3023;
  rewValues_2   = 3024;
  rewValues_3   = 3025;
  rewValues_4   = 3026;
  rewValues_5   = 3027;
  rewValues_6   = 3028;
  rewValues_7   = 3029;
  rewValues_8   = 3030;
  rewValues_9   = 3031;
  rewValues_10  = 3032;

  // ограничения
  
  // параметры
  
end
