/*
 ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
 บ                   (c) 1994,2001 ชฎเฏฎเ ๆจ๏ €€’€                      บ
 บ เฎฅชโ        : €€’€                                                 บ
 บ ‘จแโฅฌ        : ฎญโใเ ฏซ ญจเฎข ญจ๏ ฏเฎจงขฎคแโข                           บ
 บ ฅเแจ๏        : 7.10                                                      บ
 บ  งญ ็ฅญจฅ    : ”ฎเฌจเฎข ญจฅ แฏจแช  จแฏฎซญ๏ฅฌ๋ๅ แข๏งฅฉ                    บ
 บ โขฅโแโขฅญญ๋ฉ : ‘ชฎเฎๅฎค ฌจโเจฉ ซ คจฌจเฎขจ็                             บ
 บ  เ ฌฅโเ๋     : ญฅโ                                                       บ
 ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/

const
  reOtpKoeff   = 0;
  reKolOtp     = 1;
  rePriceOtp   = 2;
  reSumma      = 3;
  reKolDoc     = 4;
  rePriceDoc   = 5;
  reInPlanRash = 10;
  reInPlanPrih = 11;
  rePlanRash   = 12;
  rePlanPrih   = 13;
  reDirectRa   = 20;
  reDirectPr   = 21;
  reNaklKolS   = 40;
  reNaklSumS   = 41;
  reNaklKolB   = 42;
  reNaklSumB   = 43;
	reNaklSumVS  = 44;
	reNaklSumVB  = 46;
  reFinSumPr   = 50;
  reFinSumRa   = 51;


  gcSpObjAcc   = 0;
  gcCgKau      = 1;
end
