//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 5.80 - модуль "Управление бюджетом"
// Базовый объект : "Построитель иерархических отчетов"
//------------------------------------------------------------------------------

#ifndef __aMakeFpDSKNames_Inc__
#define __aMakeFpDSKNames_Inc__

const
  MAKEFP_DSK_NAME_STBUD  = 'RepFpValues_Saved_cStBud';
  MAKEFP_DSK_NAME_PERIOD = 'RepFpValues_Saved_cPeriod';
  MAKEFP_DSK_NAME_BUDCO  = 'RepFpValues_Saved_cBudCO';
end;

#endif//__aMakeFpDSKNames_Inc__
