//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Управление бюджетом"
// Базовый объект : "Формирование EMail сообщений"
//------------------------------------------------------------------------------

#ifndef __FpObjEMailSender_Inc__
#define __FpObjEMailSender_Inc__

Const
  lcFpEMailSenderType_SMTPServer = 0;
  lcFpEMailSenderType_MSOutLook  = 1;

  lcFpEMailPublishType_Save = 0;
  lcFpEMailPublishType_Disp = 1;
  lcFpEMailPublishType_Send = 2;

end;

#endif//__FpObjEMailSender_Inc__
