//------------------------------------------------------------------------------
//                                                      (c) Корпорация Галактика
// Галактика ERP 9.1 - Заработная плата
// Константы кодов пометок (Formarks.Choice)
//------------------------------------------------------------------------------

#ifndef __FormarksChoice_inc__
#define __FormarksChoice_inc__

Const

#include FormarksChoice.const

End;

#end //  __FormarksChoice_inc__