const



  // числа

  // Даты

  // ссылки

  // наименования
  reName     = 3000;
  reKOD      = 3001;
  reNode     = 3002;
  reIsLeaf   = 3003;
  reShifr    = 3004;
  reUslNum   = 3005;
  reVnNum    = 3006;
  reActivity = 3007;
  reDirect   = 3008;
  reStatus   = 3009;
  reSumZatr  = 3010;
  redOpen    = 3011;
  redFrom    = 3012;
  redTo      = 3013;
  redFact    = 3014;
  rePrice    = 3015;
  reVal      = 3016;
  reUsl      = 3017;
  reVhodNal  = 3018;
  reNalogs   = 3019;
  reKredit   = 3020;
  redStart   = 3021;

  // параметры
  repTheme   = 4000;

  // ограничения
  reNoBound  = 5000;
  reByTheme  = 5001;
  reByStage  = 5002;

end
