const



  // числа

  // Даты

  // ссылки

  // наименования
  reSmetaName  = 3000;
  reSmetaKod   = 3001;
  reSmeta      = 3002;
  reStZatr     = 3003;
  reSumZatr    = 3004;
  reStZatrName = 3005;
  reStZatrKod  = 3006;
  reFixSum     = 3007;
  reStZatrLook = 3008;
  reStZatrPr   = 3009;
  reLook       = 3010;
  reNalogs     = 3011;

  // параметры
  repStage     = 4000;
  repExecutor  = 4001;
  repSmeta     = 4002;

  // ограничения
  reNoBound    = 5000;
  reByStage    = 5001;

end
