//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 7.12 - модуль "Управление бюджетом"
// Базовый объект : "Шаблон формирования Email-извещений"
//------------------------------------------------------------------------------

#ifndef __FpObjEMailPayTempl_Inc__
#define __FpObjEMailPayTempl_Inc__

Const  
  lc_RepXLSID = 'F_FPBUDGET\REPXLT\EMailPayTempl';
end;

#endif//__FpObjEMailPayTempl_Inc__
