const

  // числа

  // Даты

  // ссылки

  // наименования
  recZemCompl    = 3000;
  recFpCO        = 3001;
  reIsBuildings  = 3002;
  reInvNo        = 3003;
  redAkt         = 3004;
  reNoAkt        = 3005;
  reName         = 3006;
  reAddr         = 3007;
  recAddr        = 3008;
  reFlats        = 3009;
  reRooms        = 3010;
  reMaterial     = 3011;
  reBuildYear    = 3012;
  reFloors       = 3013;
  reGroundFloors = 3014;
  reIsMonument   = 3015;
  rewPurposes    = 3016;
  repPurposes    = 3017;
  recKatOS       = 3018;

  // ограничения
  
  // параметры
  
end
