const

  // числа

  // Даты

  // ссылки

  // наименования
  reVidObj      = 3000;
  recObj        = 3001;
  renpp         = 3002;
  redChange     = 3003;
  reComments    = 3004;
  recoValues_1  = 3005;
  recoValues_2  = 3006;
  recoValues_3  = 3007;
  recoValues_4  = 3008;
  recoValues_5  = 3009;
  recoValues_6  = 3010;
  recoValues_7  = 3011;
  recoValues_8  = 3012;
  recoValues_9  = 3013;
  recoValues_10 = 3014;
  rewValues_1   = 3015;
  rewValues_2   = 3016;
  rewValues_3   = 3017;
  rewValues_4   = 3018;
  rewValues_5   = 3019;
  rewValues_6   = 3020;
  rewValues_7   = 3021;
  rewValues_8   = 3022;
  rewValues_9   = 3023;
  rewValues_10  = 3024;
  redValues_1   = 3025;
  redValues_2   = 3026;
  redValues_3   = 3027;
  redValues_4   = 3028;
  redValues_5   = 3029;
  redValues_6   = 3030;
  redValues_7   = 3031;
  redValues_8   = 3032;
  redValues_9   = 3033;
  redValues_10  = 3034;
  resValues_1   = 3035;
  resValues_2   = 3036;
  resValues_3   = 3037;
  resValues_4   = 3038;
  resValues_5   = 3039;
  resValues_6   = 3040;
  resValues_7   = 3041;
  resValues_8   = 3042;
  resValues_9   = 3043;
  resValues_10  = 3044;
  redoValues_1  = 3045;
  redoValues_2  = 3046;
  redoValues_3  = 3047;
  redoValues_4  = 3048;
  redoValues_5  = 3049;
  redoValues_6  = 3050;
  redoValues_7  = 3051;
  redoValues_8  = 3052;
  redoValues_9  = 3053;
  redoValues_10 = 3054;
  redoValues_11 = 3055;
  redoValues_12 = 3056;
  redoValues_13 = 3057;
  redoValues_14 = 3058;
  redoValues_15 = 3059;
  redoValues_16 = 3060;
  redoValues_17 = 3061;
  redoValues_18 = 3062;
  redoValues_19 = 3063;
  redoValues_20 = 3064;

  // ограничения
  
  // параметры
  
end
