//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 8.1 - Управление капитальными вложениями и строительством
// Константы режимов настройки алгоритмов расчета сумм
//------------------------------------------------------------------------------

Const
  cgAlgForDef    : word = 0;
  cgAlgForSum    : word = 1;
  cgDefAlgForDef : word = 2;

  cgNZSKart      : word = 0;
  cgKVKart       : word = 1;
  cgNZSPlan      : word = 2;
  cgKVPlan       : word = 3;
  cgVvod         : word = 4;
  cgJobSp        : word = 5;
  cgJobFin       : word = 6;

  cgSumCMR       : word = 0;
  cgSumOborud    : word = 1;
  cgSumPIR       : word = 2;
  cgSumProch     : word = 3;
  cgSumOther     : word = 4;

  cgPlus         : word = 0;
  cgMinus        : word = 1;
end;
