const
  ExImExport  = 1;
  ExImImport  = 2;
  ExImFilter  = 3;

  constWarningCode   = 1;
  constSuccessCode   = 0;
  constErrorCode_3   = 3;
  constErrorCode_2   = 2;
  constErrorCode     = 5;

  constWarningCodeLog = 2;
  constErrorCodeLog   = 1;
  constSuccessCodeLog = 0;

  constDocErrorCode  = 1;
  constDocErrorCode2 = 2;
  constDocSuccessCode= 0;
  constDocWarningCode= 8;

  lHeaderValueColumn = 'Документ ';
  lSpecValueColumn   = 'Спецификация ';
  lMd5Summ           = 'Md5Summa';
  lUnKnow            = 100;
  lImpMemoAttr       = 'ImpMemoAttr';
  // принадлежность поля
  lHeader            = 0;//шапка
  lSpec              = 1;// спецификация
end;   
