const
  ExImExport  = 1;
  ExImImport  = 2;
  ExImFilter  = 3;

  constWarningCode   = 1;
  constSuccessCode   = 0;
  constErrorCode_3   = 3;
  constErrorCode_2   = 2;
  constErrorCode     = 5;
  constWarningCode_1 = 6;

  constWarningCodeLog = 2;
  constErrorCodeLog   = 1;
  constSuccessCodeLog = 0;

  constDocErrorCode  = 1;
  constDocErrorCode2 = 2;
  constDocSuccessCode= 0;
  constDocWarningCode= 8;

  lHeaderValueColumn = 'Документ ';
  lSpecValueColumn   = 'Спецификация ';
  lMd5Summ           = 'Md5Summa';
  lUnKnow            = 100;
  lImpMemoAttr       = 'ImpMemoAttr';
  // принадлежность поля
  lHeader            = 0;//шапка
  lSpec              = 1;// спецификация

  lDosKodirovka = 0;
  lWinKodirovka = 1;
  lUtfKodirovka = 2;

  //Константы системных каталогов
  constCatalogs_3 = -3;
  constCatalogs_4 = -4;
  constCatalogs_5 = -5;
  constCatalogs_7 = -7;
  constCatalogs_8 = -8;
  constCatalogs_9 = -9;
  constCatalogs_11 = -11;
  constCatalogs_12 = -12;
  constCatalogs_14 = -14;
  constCatalogs_15 = -15;
  constCatalogs_16 = -16;
  constCatalogs_20 = -20;
  constCatalogs_22 = -22;
  constCatalogs_23 = -23;
  constCatalogs_24 = -24;
  constCatalogs_26 = -26;
  constCatalogs_27 = -27;
  constCatalogs_28 = -28;
  constCatalogs_29 = -29;
  constCatalogs_31 = -31;
  constCatalogs_32 = -32;
  constCatalogs_33 = -33;
  constCatalogs_35 = -35;
  constCatalogs_39 = -39;
  constCatalogs_40 = -40;
  constCatalogs_41 = -41;
  constCatalogs_42 = -42;
  constCatalogs_43 = -43;
  constCatalogs_44 = -44;
  constCatalogs_48 = -48;
  constCatalogs_54 = -54;
  constCatalogs_55 = -55;
  constCatalogs_56 = -56;
  constCatalogs_58 = -58;
  constCatalogs_70 = -70;
  constCatalogs_76 = -76;
  constCatalogs_78 = -78;
  constCatalogs_120 = -120;
  constCatalogs_121 = -121;
  constCatalogs_122 = -122;
  constCatalogs_123 = -123;
  constCatalogs_133 = -133;
  constCatalogs_146 = -146;
  constCatalogs_175 = -175;
  constCatalogs_176 = -176;
  constCatalogs_197 = -197;
  constCatalogs_375 = -375;
  constCatalogs_704 = 704;
  constCatalogs_705 = 705;
  constCatalogs_706 = 706;
  constCatalogs_707 = 707;
  constCatalogs_712 = 712;
  constCatalogs_1340 = 1340;
  constCatalogs_1350 = 1350;
  constCatalogs_1360 = 1360;
  constCatalogs_1370 = 1370;
  constCatalogs_1380 = 1380;
  constCatalogs_1396 = 1396;
end;
