//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 8.10 - модуль "Платежный календарь"
// Таблица : "Константы меню БДДС"
//------------------------------------------------------------------------------

#ifndef __CashFlow_Menu_Constants_Inc__
#define __CashFlow_Menu_Constants_Inc__

const

  lc_CashFlow_Menu_ReportName   = 'F_OFP::ofp_rep';             // Меню отчеты
  lc_CashFlow_Menu_SettingsName = 'F_OFP::ofp_system_settings'; // Меню настройки

  lc_CashFlow_Menu_CashFlowReportName   = 'Исполнение бюджета денежных средств'; // Пункт меню отчета
  lc_CashFlow_Menu_CashFlowSettingsName = 'Настройка бюджета денежных средств';  // Пункт меню настроек

  lc_CashFlow_License_BudgetName = 'SFP'; // Наименование лицензии
end;

#endif // __CashFlow_Menu_Constants_Inc__
