//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика ERP 9.1 - Управление персоналом
// Константы статусов операций загрузки базы ФИАС
//------------------------------------------------------------------------------

  CHECK_OK                  = 0;
  CHECK_UPD_SOAP_HTTP_ER    = 1;
  CHECK_UPD_SOAP_UNKNOW_ER  = 2;
  CHECK_UPD_NONE            = 3;
  CHECK_DIRECTORY_FOUND_ER  = 4;
  CHECK_DIRECTORY_RIGHTS_ER = 5;
  CHECK_THREAD_EXISTS_ER    = 6;
  CHECK_HAVENT_OLD_VERSION  = 7;

  STATUS_STOP               = 0;
  STATUS_LOAD               = 1;
  STATUS_EXTRACT            = 2;
  STATUS_LOADANDEXTRACT     = 3;

  LOG_FILE                  = '\fias.log';
