//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 7.12 - модуль "Управление бюджетом"
// Константы: "Проверка аналитик бюджетирования"
//------------------------------------------------------------------------------


#ifndef __fpChkBudAn_Inc__
#define __fpChkBudAn_Inc__

Const
  lc_ChkBudAn_CheckDupes      = 1;
  lc_ChkBudAn_CheckVirtualAgr = 2;
  lc_ChkBudAn_CheckNode       = 4;
  lc_ChkBudAn_CheckLeafAttr   = 8;
  lc_ChkBudAn_CheckLevelInd   = 16;
end;

#endif//__fpChkBudAn_Inc__
