#ifndef __KBU_Inc__
#define __KBU_Inc__

const
  // Константы задач, префикс "tsk" обязателен.
  tskOborot    = 1;            
  tskSaldo     = 2;
  tskPlan      = 3;
  tskKAU       = 4;
  tskValuta    = 5;
  tskKatKau    = 6;
  tskUsersDoc  = 7;
  tskSaldoBL   = 8;
  tskUserKau   = 9;
  tskKauImpRel = 10;
  tskMCKau     = 11;

  TskName1  = 'Выгрузка проводок';
  TskName2  = 'Выгрузка сальдо';
  TskName3  = 'Выгрузка структуры плана счетов';
  TskName4  = 'Выгрузка кодов аналитического учета';
  TskName5  = 'Выгрузка каталога валют';
  TskName6  = 'Выгрузка каталога аналитик';
  TskName7  = 'Выгрузка типов документов';
  TskName8  = 'Выгрузка сальдо по просроченной задолженности';
  TskName9  = 'Выгрузка пользовательской аналитики';
  TskName10 = 'Выгрузка каталога соответствий КАУ';
  TskName11 = 'Выгрузка аналитики для каталога МЦ';

end;

#end  // __KBU_Inc__
