
        (scInterfac2..scInterfac2)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmedit,         kbAltC;
          '',                   cmPickAttr,     kbAltA;
          '',                   cmNal,          kbAltF;
          '',                   cmShiftF1,      kbAltE;
          '',                   cmPass,         kbF4;
          '',                   cmDoTable1,     kbAltF2;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmIEHist,       kbAltH;

        }
        (scInterfac1..scInterfac1)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Закрыть' ,     cmClose,        kbAltF3;
          ''                 ,  cmCtrlT,        kbCtrlT;
          ''                 ,  cmPass,         kbF4;
          '',                   cmshiftF1,       kbAltE;
          '',                   cmedit,         kbAltC;
          '',                   cmPickAttr,     kbAltA;
          '',                   cmNal,          kbAltF;
          ''                 ,  cmDoTable1,     kbAltF2;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmsearchsubstr, kbctrlS;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmDocBas,       kbShiftF3;
          '',                   cmIEHist,       kbAltH;
        }
        (scInterfac3..scInterfac3)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Закрыть' ,     cmClose,        kbAltF3;
          ''                 ,  cmCtrlT,        kbCtrlT;
          ''                 ,  cmPass,         kbF4;
          '',                   cmshiftF1,       kbAltE;
          '',                   cmedit,         kbAltC;
          '',                   cmPickAttr,     kbAltA;
          '',                   cmNal,          kbAltF;
          ''                 ,  cmDoTable1,     kbAltF2;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmsearchsubstr, kbctrlS;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          '',                   cmHotKeys,      kbAltF10;
        }
        (scPodotch..scPodotch)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmCtrlT,        kbCtrlT;
          '',                   cmPass,         kbF4;
          '',                   cmDoTable1,     kbAltF2;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }

        (sclschet1..sclschet1)
        {
          #F1
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Alt+C~ Смежные данные',  cmdotable, kbAltC;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmPickAttr,     kbAltA;
          '',                   cmCtrlT,        kbCtrlT;
          '',                   cmShiftF1,      kbAltE;
          '',                   cmPass,         kbF4;
          '',                   cmdotable1,     kbAltF2;
          '',                   cmprintbase,    kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmCtrlF2,       kbCtrlF2;
          '',                   cmCtrlF3,       kbCtrlF3;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          '',                   cmHotKeys,      kbAltf10;
          #Std_Stat
        }

        (sclschet..sclschet)
        {
          #F1
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Alt+C~ Смежные данные',  cmdotable, kbAltC;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmCtrlT,        kbCtrlT;
          '',                   cmShiftF1,      kbAltE;
          ''                ,   cmPass,         kbF4;
          '',                   cmPickAttr,     kbAltA;
          '',                   cmdotable1,     kbAltF2;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmCtrlF2,       kbCtrlF2;
          '',                   cmCtrlF3,       kbCtrlF3;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          '',                   cmHotKeys,      kbAltf10;
          #Std_Stat
        }
        // от scOtpusk отличается только наличием '~F3~ Выбор'
        // от scArOtp и scArOtp1 отличается наличием '~F7~ Добавить' и '~F8~ Удалить'
        (scOtpusk1..scOtpusk1)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Alt+F10~Локальное меню',cmHotKeys,  kbAltF10;
          '~Esc~ Закрыть',      cmclose,        kbesc;
          '~Ctrl+P~Печать',     cmPrint,        kbCtrlP;
          '',                   cmDoTable,      kbAltP;
          '',                   cmAddNewRec,    kbCtrlEnter;
          '',                   cmValue10,      kbshiftf6;
          '',                   cmpass,         kbF4;
          '',                   cmClose,        kbAltF3;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmshiftf5,      kbshiftf5;
          '',                 cmExtendedDelete, kbShiftF8;
          '',                   cmShiftF9,      kbShiftF9;
          '',                   cmshiftf7,      kbshiftf7;
          '',                   cmedit,         kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',              cmEvaluateAndModify, kbCtrlF4;
          '',                   cmAlt1,         kbAlt1;
          '',                   cmAlt5,         kbAlt5;
          '',                   cmSetupReport,  kbCtrlR;

        }

        (scOtpusk..scOtpusk)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Alt+F10~Локальное меню',cmHotKeys,  kbAltF10;
          '~Esc~ Закрыть',      cmclose,        kbesc;
          '~Ctrl+P~Печать',     cmPrint,        kbCtrlP;
          '',                   cmDoTable,      kbAltP;
          '',                   cmAddNewRec,    kbCtrlEnter;
          '',                   cmValue10,      kbshiftf6;
          '',                   cmpass,         kbF4;
          '',                   cmClose,        kbAltF3;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmshiftf5,      kbshiftf5;
          '',                   cmshiftf7,      kbshiftf7;
          '',                 cmExtendedDelete, kbShiftF8;
          '',                   cmShiftF9,      kbShiftF9;
          '',                   cmedit,         kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',              cmEvaluateAndModify, kbCtrlF4;
          '',                   cmAlt1,         kbAlt1;
          '',                   cmAlt5,         kbAlt5;
          '',                   cmSetupReport,  kbCtrlR;

        }

        (scOtpusk138..scOtpusk138)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Alt+F10~Локальное меню',cmHotKeys,  kbAltF10;
          '~Esc~ Закрыть',      cmclose,        kbesc;
          '~Ctrl+P~Печать',     cmPrint,        kbCtrlP;
          '',                   cmDoTable,      kbAltP;
          '',                   cmAddNewRec,    kbCtrlEnter;
          '',                   cmValue10,      kbshiftf6;
          '',                   cmpass,         kbF4;
          '',                   cmClose,        kbAltF3;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmshiftf5,      kbshiftf5;
          '',                   cmshiftf7,      kbshiftf7;
          '',                 cmExtendedDelete, kbShiftF8;
          '',                   cmShiftF9,      kbShiftF9;
          '',                   cmedit,         kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',              cmEvaluateAndModify, kbCtrlF4;
          '',                   cmAlt1,         kbAlt1;
          '',                   cmAlt5,         kbAlt5;
          '',                   cmSetupReport,  kbCtrlR;
        }

        (scOtpusk18..scOtpusk18)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Alt+F10~Локальное меню',cmHotKeys,  kbAltF10;
          '~Esc~ Закрыть',      cmclose,        kbesc;
          '~Ctrl+P~Печать',     cmPrint,        kbCtrlP;
          '',                   cmDoTable,      kbAltP;
          '',                   cmAddNewRec,    kbCtrlEnter;
          '',                   cmValue10,      kbshiftf6;
          '',                   cmpass,         kbF4;
          '',                   cmClose,        kbAltF3;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmshiftf5,      kbshiftf5;
          '',                   cmshiftf7,      kbshiftf7;
          '',                 cmExtendedDelete, kbShiftF8;
          '',                   cmShiftF9,      kbShiftF9;
          '',                   cmedit,         kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',              cmEvaluateAndModify, kbCtrlF4;
          '',                   cmAlt1,         kbAlt1;
          '',                   cmAlt5,         kbAlt5;
          '',                   cmSetupReport,  kbCtrlR;
        }

        (scVOtpuskP..scVOtpuskP)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Ins~ Пометить',     cmdoins,        kbINS;
          '~+~ Пометить всех',  cmAllIns,       kbGrayPlus;
          '~-~ Отменить всех',  cmAllUnIns,     kbGrayMinus;
          '~Esc~ Закрыть',      cmclose,        kbesc;
          '',                   cmpass,         kbF4;
          '',                   cmClose,        kbAltF3;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmCtrlC,        kbAltB;
          '',                   cmPickAttr,     kbAltA;
          '',                   cmPickClass,    kbAltC;
          '',                   cmDoTable,      kbAltP;
          '',                   cmshiftf5,      kbshiftf5;
          '',                   cmedit,         kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmshiftf7,      kbshiftf7;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scVOtpusk..scVOtpusk)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Ins~ Пометить',     cmdoins,        kbINS;
          '~+~ Пометить всех',  cmAllIns,       kbGrayPlus;
          '~-~ Отменить всех',  cmAllUnIns,     kbGrayMinus;
          '~Esc~ Закрыть',      cmclose,        kbesc;
          '',                   cmpass,         kbF4;
          '',                   cmClose,        kbAltF3;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmCtrlC,        kbAltB;
          '',                   cmPickAttr,     kbAltA;
          '',                   cmPickClass,    kbAltC;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmDoTable,      kbAltP;
          '',                   cmshiftf5,      kbshiftf5;
          '',                   cmshiftf7,      kbshiftf7;
          '',                   cmedit,         kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scblisnet1..scblisnet1)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Ctrl+P~Печать',     cmPrint,        kbCtrlP;
          '~Esc~ Закрыть',      cmclose,        kbesc;
          '',                   cmAddNewRec,    kbCtrlEnter;
          '',                   cmpass,         kbF4;
          '',                   cmClose,        kbAltF3;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmshiftf5,      kbshiftf5;
          '',                   cmValue6,       kbCtrlEnter;
          '',                   cmValue10,      kbshiftF6;
          '',                   cmshiftf9,      kbshiftf9;
          '',                   cmedit,         kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmshiftf7,      kbshiftf7;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmHotKeys,      kbAltF10;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }
        (scBlisnet..scBlisnet)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Ctrl+P~Печать',     cmPrint,        kbCtrlP;
          '~Esc~ Закрыть',      cmclose,        kbesc;
          '',                   cmAddNewRec,    kbCtrlEnter;
          ''                   ,cmpass,         kbF4;
          '',                   cmClose,        kbAltF3;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmValue6,       kbCtrlEnter;
          '',                   cmValue10,      kbshiftF6;
          '',                   cmshiftf9,      kbshiftf9;
          '',                   cmshiftf5,      kbshiftf5;
          '',                   cmshiftf7,      kbshiftf7;
          '',                   cmedit,         kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmHotKeys,      kbAltF10;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }
        (scChild..scChild)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Выход',        cmClose,        kbAltF3;
          '',                   cmINSKEY,       kbSHIFTINS;
          '',                   cmDELKEY,       kbSHIFTDEL;
          '',                   cmshiftf5,      kbshiftf5;
          '',                   cmCtrlC,        kbAltB;
          #Std_Stat
        }
        (scCHild1..scCHILD1)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmINSKEY,       kbSHIFTINS;
          '',                   cmDELKEY,       kbSHIFTDEL;
          '',                   cmshiftf7,      kbshiftf7;
          '',                   cmshiftf5,      kbshiftf5;
          '',                   cmCtrlC,        kbAltB;
          #Std_Stat
        }
        (scxarpred..scxarpred)//scsumudnap - тоже только с '<Alt+F10>-Локальное меню',cmHotKeys, kbAltF10;
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                 cmSHIFTF5,      kbShiftF5;
          '',                   cmPass,         kbF4;
          '',                   cmDelete,       kbF8;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          ''              ,   cmDoTable,     kbALTC;
          ''              ,   cmDoTable2,    kbALTR;
          ''              ,   cmDoTable,     kbAltE;

        }
        (scxarpred1..scxarpred1)//scsumudnap1 - тоже только с '<Alt+F10>-Локальное меню',cmHotKeys, kbAltF10;
        {
          '~F1~ Помощь',        cmHelp,kbF1;
          '~F3~ Выбор',         cmPick,kbF3;
          '~Esc~ Закрыть',      cmClose,kbAltF3;
          '',                   cmSHIFTF5,      kbShiftF5;
          '',                   cmPass,         kbF4;
          '',                   cmDelete,       kbF8;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          ''              ,   cmDoTable,     kbALTC;
          ''              ,   cmDoTable2,    kbALTR;
          ''              ,   cmDoTable,     kbAltE;

        }

        (scpickan..scpickan)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F4~ Изменить',      cmEdit,         kbF4;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~Enter~ Выбор',      cmDefault,      kbF2;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          #Std_Stat
        }

        (scpickan1..scpickan1)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F4~ Изменить',      cmEdit,         kbF4;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~Enter~ Выбор',      cmDefault,      kbF2;
          '~Esc~ Закрыть',      cmClose,        kbEsc;
          '~Ins~ Пометить',     cmMarkUnMark,   kbIns;
          '~+~ Пометить все',   cmSelectAll,    kbGrayPlus;
          '~-~ Отменить все',   cmUnSelectAll,  kbGrayMinus;
          '~Ctrl+Enter~ Открыть узел',       cmTreeOpenNode,         kbCtrlEnter;
          '~Ctrl+Backspace~ Закрыть узел',   cmTreeCloseNode,        kbCtrlBack;
          #Std_Stat
        }

        (scint..scint)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F4~ Изменить',      cmEdit,         kbF4;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          ''             ,      cmDefault,      kbENTER;
          '',                   cmprintbase,    kbctrlr;
          '',                   cmPrint,        kbCtrlP;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmPrint,        kbCtrlP;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scintPreparePrint..scintPreparePrint)
        {
          '~F1~ Помощь',               cmHelp,         kbF1;
          '~F4~ Изменить',             cmEdit,         kbF4;
          '~F7~ Добавить',             cmAddNewRec,    kbF7;
          '~F8~ Удалить',              cmDelete,       kbF8;
          '~Esc~ Закрыть',             cmClose,        kbAltF3;
          '',                          cmDefault,      kbENTER;
          '~Ctrl+R~ Настройка отчета', cmprintbase,    kbctrlr;
          '~Ctrl+P~ Печать отчета',    cmPrint,        kbCtrlP;
          '',                          cmCalculator,   kbShiftF2;
          '',                          cmLastHelp,     kbAltF1;
          '',                          cmZoom,         kbF5;
          '',                          cmResize,       kbCtrlF5;
          '',                          cmQuit,         kbAltX;
          '',                          cmMenu,         kbF10;
          '',                          cmHotKeys,      kbAltF10;
          '',                          cmPrint,        kbCtrlP;
          '',                          cmEvaluateAndModify, kbCtrlF4;
        }
        (scintI..scintI) //scintl - тоже только с '<Alt+F10>-Локальное меню',cmHotKeys, kbAltF10;
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~F4~ Изменить',      cmEdit,         kbF4;
          '~Alt+B~ Фильтр',     cmCtrlC,        kbAltB;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          ''             ,      cmDefault,      kbENTER;
          '',                   cmprintbase,    kbctrlr;
          '',                   cmDoTable1,     kbAltF2;
          '',                   cmPrint,        kbCtrlP;
          '',                   cmdotable,      kbAltC;
          '',                   cmPickAttr,     kbAltA;
          '',                   cmNal,          kbAltF;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmShiftF1,      kbAltE;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }
        (scintiV..scintiV)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Ins~ Пометить',     cmdoins,        kbINS;
          '~+~ Помет.всех',     cmAllIns,       kbGrayPlus;
          '~-~ Снять',          cmAllUnIns,     kbGrayMinus;
          '~Alt+B~ Фильтр',     cmCtrlC,        kbAltB;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmAccording,    kbAltS;
          '',                   cmShiftF1,      kbAltE;
          '',                   cmShiftF5,      kbShiftF5;
          '',                 cmExtendedDelete, kbShiftF8;
          '',                   cmShiftF9,      kbShiftF9;
          ''             ,      cmEdit,         kbF4;
          ''             ,      cmDefault,      kbENTER;
          '',                   cmPrint,        kbCtrlP;
          '',                   cmSetupReport,  kbCtrlR;
          '',                   cmPickClass,    kbAltC;
          '',                   cmPickAttr,     kbAltA;
          '',                   cmNal,          kbAltF;
          '',                   cmDoTable,      kbAltP;
          '',                   cmSortMC,       kbAltR;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmHotKeys,      kbAltF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          '',                   cmAlt1,         kbAlt1;
          '',                   cmAlt5,         kbAlt5;
          '',                   cmImp,          kbAltI;
        }
        (scintB..scintB)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~Ins~ Пометить',     cmdoins,        kbINS;
          '~+~ Пометить всех',  cmAllIns,       kbGrayPlus;
          '~-~ Отменить всех',  cmAllUnIns,     kbGrayMinus;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '~Ctrl+P~',           cmPrint,        kbCtrlP;
          '~Alt+E~',            cmShiftF1,      kbAltE;
          ''             ,      cmEdit,         kbF4;
          ''             ,      cmDefault,      kbENTER;
          '',                   cmdotable,      kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmHotKeys,      kbAltF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }
        (scintD..scintD)
        {
          '~F7~ Добавить Сортировать'     , cmAddNewRec,    kbF7;
          '~F2~ По таб.№'      , cmF2KEY,        kbF2;
          '~F6~ По шифрам'    , cmF6KEY,        kbF6;
          '',       cmHelp,         kbF1;
          ''                  , cmEdit,         kbF4;
          ''                  , cmClose,        kbAltF3;
          ''                  , cmDefault,      kbENTER;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }
        (scpickt..scpickt)
        {
          '~F1~ Помощь',        cmHelp,           kbF1;
          '~Esc~ Закрыть',      cmClose,          kbAltF3;
          '~Enter~ Выбор',      cmDefault,        kbF2;
          '~Ctrl+Enter~ Печать',  cmOt,         kbCTRLEnter;
          '',                   cmCalculator,     kbShiftF2;
          '',                   cmPrintBaseGround,kbCtrlP;
          '',                   cmLastHelp,       kbAltF1;
          '',                   cmZoom,           kbF5;
          '',                   cmResize,         kbCtrlF5;
          '',                   cmQuit,           kbAltX;
          '',                   cmMenu,           kbF10;
          '',              cmEvaluateAndModify,   kbCtrlF4;
        }
        (scpickp..scpickp)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F4~ Изменить',      cmEdit,         kbF4;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~Enter~ Выбор',      cmDefault,      kbF2;
          '~Ctrl+Enter~' ,      cmOt,           kbCTRLEnter;
          '',                   cmClose,        kbAltF3;
          '',                   cmclose,        kbesc;
          '',                   cmQuit,           kbAltX;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }
        (scpASS..scpASS)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '~Enter~ Выбор',      cmDefault,      kbF2;
          '~Alt+~ Редактирование', cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scbut..scbut)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
//          '',                   cmDefault,      kbF2;
//          '',                   cmShiftF1,      kbAltE;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }
        (scbutK..scbutK)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Enter~ Выбор',      cmDefault,      kbENTER;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmDefault,      kbF2;
           '',                   cmShiftF1,      kbAltE;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }
        (scenteran..scenteran)

        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Enter~ Выбор',      cmdoins,        kbINS;
          '~Esc~ Отказ',        cmclose,        kbesc;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmF2KEY,        kbF2;
          '',                   cmf3keY,        kbF3;
          '',                   cmF4KEY,        kbF4;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }
        (scenter1..scenter1)

        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Enter~ Выбор',      cmdoins,        kbINS;
          '~Esc~ Отказ',        cmclose,        kbesc;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',              cmyes,        kbF3;
          '',              cmno,        kbF4;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scvvodud..scvvodud)

        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Enter~ Выбор',      cmdoins,        kbINS;
          '~Esc~ Отказ',        cmclose,        kbesc;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',              cmyes,        kbF3;
          '',              cmno,        kbF4;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }
        (scklndr..scklndr)

        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scsysmbf..scsysmbf)

        {
          '~F1~ Помощь',          cmHelp,         kbF1;
          '~Enter~ Изменить',     cmdefault,      kbf4;
          '~F7~ Добавить' ,       cmInsert,       kbF7;
          '~F8~ Удалить',         cmDelete,       kbF8;
          '~Esc~ Закрыть',        cmClose,        kbAltF3;
          '~Alt+B~ Фильтр',       cmCtrlC,        kbAltB;
          '',                     cmdoins,        kbINS;
          '',                     cmCalculator,   kbShiftF2;
          '',                     cmQuit,         kbAltX;
          '',                     cmPickAttr,     kbAltA;
          '',                     cmclose,        kbesc;
          '',                     cmMenu,         kbF10;
          '',                     cmZoom,         kbF5;
          '',                     cmResize,       kbCtrlF5;
          '',                     cmNext,         kbF6;
          '',                     cmPrev,         kbShiftF6;
          '',                     cmSysMenu,      kbCtrlF10;
          '',                     cmSHIFTF5,      kbShiftF5;
          '',                     cmAllNar,       kbCtrlF2;
          '',                     cmEvaluateAndModify, kbCtrlF4;
        }

        (scsysmbf1..scsysmbf1)

        {
          '~F1~ Помощь',          cmHelp,         kbF1;
          '~F3~ Выбор',           cmPick,         kbF3;
          '~F7~ Создать выплату', cmInsert,       kbF7;
          '~F8~ Удалить',         cmDelete,       kbF8;
          '~Esc~ Закрыть',        cmClose,        kbAltF3;
          '~Alt+B~ Фильтр',       cmCtrlC,        kbAltB;
          '',                     cmCalculator,   kbShiftF2;
          '',                     cmQuit,         kbAltX;
          '',                     cmclose,        kbesc;
          '',                     cmMenu,         kbF10;
          '',                     cmZoom,         kbF5;
          '',                     cmResize,       kbCtrlF5;
          '',                     cmNext,         kbF6;
          '',                     cmPrev,         kbShiftF6;
          '',                     cmSysMenu,      kbCtrlF10;
          '',                     cmEvaluateAndModify, kbCtrlF4;
        }

        (scfam1..scfam1)

        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Ins~ Пометка к выбору',cmdoins,     kbINS;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }
        (scvidop..scvidop)

        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Enter~ Выбор',      cmDefault,      kbENTER;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmdoins,        kbINS;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }

        (scprvidopl..scprvidopl)
        {
          #F1
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          #Ins
          #PlusMinus
          '',                   cmSHIFTF5,      kbShiftF5;
          '',                   cmF2KEY,        kbSHIFTF3;
          '',                   cmF9KEY,        kbSHIFTF9;
          '',                   cmDELKEY,       kbSHIFTDEL;
          '',                   cmF7KEY,        kbSHIFTF7;
          '',                   cmF6KEY,        kbSHIFTF6;
          '',                   cmALTF9,        kbaltF9;
          '',                   cmINar,         kbCtrlF9;
          '',                   cmprintbase,    kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmINSKEY,       kbINS;
          '',                   cmEdit,         kbAltC;
          #Std_Stat
        }
        (scprvid2..scprvid2)

        {
          #F1
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmF2KEY,        kbSHIFTF3;
          '',                   cmF9KEY,        kbSHIFTF9;
          '',                   cmDELKEY,       kbSHIFTDEL;
          '',                   cmF7KEY,        kbSHIFTF7;
          '',                   cmF6KEY,        kbSHIFTF6;
          '',                   cmEdit,        kbAltC;
          '',                   cmINSKEY,       kbINS;
          '',                   cmALTF9,        kbaltF9;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          #Std_Stat

        }
        (scpruder..scpruder)

        {
          #F1
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmF2KEY,        kbSHIFTF3;
          '',                   cmSHIFTF5,      kbShiftF5;
          '',                   cmF9KEY,        kbSHIFTF9;
          '',                   cmALTF9,        kbaltF9;
          '',                   cmF7KEY,        kbSHIFTF7;
          '',                   cmF6KEY,        kbSHIFTF6;
          '',                   cmEdit,         kbAltC;
          '',                   cmINSKEY,       kbINS;
          '',                   cmprintbase,    kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          #Std_Stat
          /*'',                 cmCalculator,   kbShiftF2;
          '',                 cmclose,        kbesc;
          '',                 cmZoom,         kbF5;
          '',                 cmResize,       kbCtrlF5;
          '',                 cmNext,         kbF6;
          '',                 cmPrev,         kbShiftF6;
          '',                 cmSysMenu,      kbCtrlF10;
          '',                 cmEvaluateAndModify, kbCtrlF4;
          '',                 cmQuit,         kbAltX;
          */

        }

        (scprnaryad..scprnaryad)

        {
          '~F7~ Добавить', cmInsert,       kbF7;
          '~F8~ Удалить',    cmDelete,       kbF8;
          '~F3~ Выбор',    cmPick,         kbF3;
          '~Esc~ Выход',   cmClose,        kbAltF3;
          '~Shift+F3~ ',cmF2KEY,  kbShiftF3;
          '~Shift+F5~',    cmSHIFTF5,      kbShiftF5;
          '~Shift+F7~',    cmF7KEY,        kbShiftF7;
          '~Ctrl+F3~',     cmCtrlF3,       kbCtrlF3;
          '~Alt+F2~ Формат',    cmDoTable1,     kbAltF2;
          '~F1~ Помощь',   cmHelp,         kbF1;
          ''              , cmEdit,        kbAltC;
          '',              cmChWin,        kbCtrlEnter;
          '',              cmDELKEY,       kbSHIFTDEL;
          '',              cmF7KEY,        kbShiftF7;
          '',              cmCtrlF3,       kbCtrlF3;
          '',              cmprintbase,    kbctrlr;
          '',              cmPrintBaseGround, kbCtrlP;
          '',              cmCalculator,   kbShiftF2;
          '',              cmclose,        kbesc;
          '',              cmQuit,         kbAltX;
          '',              cmMenu,         kbF10;
          '',              cmZoom,         kbF5;
          '',              cmResize,       kbCtrlF5;
          '',              cmHotKeys,      kbAltF10;
          '',              cmNext,         kbF6;
          '',              cmPrev,         kbShiftF6;
          '',              cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }

        (sci1378prnaryad..sci1378prnaryad)
        {
          '~F1~ Помощь',      cmHelp,         kbF1;
          '~F3~ Выбор',       cmPick,         kbF3;
          '~F7~ Добавить',    cmInsert,       kbF7;
          '~F8~ Удалить',     cmDelete,       kbF8;
          '~Esc~ Выход',      cmClose,        kbAltF3;
          #Ins
          #PlusMinus
          '',                 cmDoTable1,     kbAltF2;
          '',                 cmF2KEY,        kbShiftF3;
          '',                 cmSHIFTF5,      kbShiftF5;
          '',                 cmF7KEY,        kbShiftF7;
          '',                 cmCtrlF3,       kbCtrlF3;
          '',                 cmEdit,         kbAltC;
          '',                 cmChWin,        kbCtrlEnter;
          '',                 cmDELKEY,       kbSHIFTDEL;
          '',                 cmF7KEY,        kbShiftF7;
          '',                 cmCtrlF3,       kbCtrlF3;
          '',                 cmprintbase,    kbctrlr;
          '',                 cmPrintBaseGround, kbCtrlP;
          #Std_Stat
        }


        (sci178prnaryad..sci178prnaryad)
        {
          '~F1~ Помощь',      cmHelp,         kbF1;
          '~F7~ Добавить',    cmInsert,       kbF7;
          '~F8~ Удалить',     cmDelete,       kbF8;
          '~Esc~ Выход',      cmClose,        kbAltF3;
          #Ins
          #PlusMinus
          '',                 cmDoTable1,     kbAltF2;
          '',                 cmF2KEY,        kbShiftF3;
          '',                 cmSHIFTF5,      kbShiftF5;
          '',                 cmF7KEY,        kbShiftF7;
          '',                 cmCtrlF3,       kbCtrlF3;
          '',                 cmEdit,         kbAltC;
          '',                 cmChWin,        kbCtrlEnter;
          '',                 cmDELKEY,       kbSHIFTDEL;
          '',                 cmF7KEY,        kbShiftF7;
          '',                 cmCtrlF3,       kbCtrlF3;
          '',                 cmprintbase,    kbctrlr;
          '',                 cmPrintBaseGround, kbCtrlP;
          #Std_Stat
        }

        (scavans..scavans)
        {
          '',                        cmHelp,         kbF1;
          '~Shift+Del~ Не выпл.всем',cmdelkey,       kbShiftDel;
          '~Shift+F9~удер.'  ,       cmF9KEY,        kbShiftF9;
          '~Shift+F5~',              cmRas,          kbShiftF5;
          '~F4~ Изменить',           cmEdit,         kbF4;
          '~Alt+B~ Фильтр',          cmCtrlC,        kbAltB;
          '~Esc~ Закрыть',           cmClose,        kbEsc;
          '',                        cmCalculator,   kbShiftF2;
          '',                        cmQuit,         kbAltX;
          '',                        cmMenu,         kbF10;
          '',                        cmZoom,         kbF5;
          '',                        cmResize,       kbCtrlF5;
          '',                        cmNext,         kbF6;
          '',                        cmPrev,         kbShiftF6;
          '',                        cmSysMenu,      kbCtrlF10;
          '',                        cmEvaluateAndModify, kbCtrlF4;
          '',                        cmHotKeys,      kbAltF10;
          '',                        cmRas,          kbShiftF5;
          '',                        cmPrintBase,    kbCtrlR;
          '',                        cmPrintBaseGround, kbCtrlP;
          #Ins
          #PlusMinus
        }

        (scavans1..scavans1)
        {
          '',                        cmHelp,         kbF1;
          '~Shift+Ins~ Аванс не получен',  cmdoins,  kbSHIFTINS;
          '~F3~ Выбор',              cmPick,         kbF3;
          '~F4~ Изменить',           cmEdit,         kbF4;
          '~Esc~ Зак.',              cmClose,        kbEsc;
          '',                        cmCalculator,   kbShiftF2;
          '',                        cmQuit,         kbAltX;
          '',                        cmclose,        kbesc;
          '',                        cmMenu,         kbF10;
          '',                        cmZoom,         kbF5;
          '',                        cmResize,       kbCtrlF5;
          '',                        cmNext,         kbF6;
          '',                        cmPrev,         kbShiftF6;
          '',                        cmSysMenu,      kbCtrlF10;
          '',                        cmEvaluateAndModify, kbCtrlF4;
          '',                        cmHotKeys,      kbAltF10;
          '',                        cmRas,          kbShiftF5;
          '',                        cmF9KEY,        kbShiftF9;
          '',                        cmdelkey,       kbShiftDel;
          '',                        cmPrintBase,    kbCtrlR;
          '',                        cmPrintBaseGround, kbCtrlP;
          #Ins
          #PlusMinus
        }


        (scEufam..scEufam)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Ins~ Пометить',     cmdoins,        kbINS;
          '~+~ Пометить всех',  cmAllIns,       kbGrayPlus;
          '~-~ Отменить всех',  cmAllUnIns,     kbGrayMinus;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmEdit,         kbF4;
          '',                   cmAddNewRec,    kbF7;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }

        (scEufam1..scEufam1)
        {
          '~Ins~ Пометить',cmdoins,     kbINS;
          '~+~ Помет.всех',cmAllIns, kbGrayPlus;
          '~-~ Отмен.всех',cmAllUnIns, kbGrayMinus;
          '~Shift+F5~ Сумма',   cmAllSum,       kbSHIFTF5;
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F4~ Изменить',      cmEdit,         kbF4;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '',                   cmClose,        kbAltF3;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }

        (scfunc..scfunc)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmPass,         kbF4;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmsearchsubstr, kbctrlS;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scuchrab..scuchrab)
        {
          '~F1~ Помощь',        cmHelp,           kbF1;
          '~F7~ Добавить',      cmInsert,         kbF7;
          '~F8~ Удалить',       cmDelete,         kbF8;
          '~Esc~ Закрыть',      cmClose,          kbAltF3;
          '',                   cmPass,           kbF4;
          '',                   cmDoTable1,       kbAltF2;
          '',                   cmCtrlF2,         kbCtrlF2;
          '',                   cmCtrlF3,         kbCtrlF3;
          '',                   cmprintbase,      kbctrlr;
          '',                   cmCalculator,     kbShiftF2;
          '',                   cmDoTable2,       kbAltE;
          '',                   cmPrintBaseGround,kbCtrlP;
          '',                   cmQuit,           kbAltX;
          '',                   cmMenu,           kbF10;
          '',                   cmZoom,           kbF5;
          '',                   cmResize,         kbCtrlF5;
          '',                   cmNext,           kbF6;
          '',                   cmPrev,           kbShiftF6;
          '',                   cmSysMenu,        kbCtrlF10;
          '',                   cmPickClass,      kbAltC;
          '',                 cmEvaluateAndModify, kbCtrlF4;

        }

        (scUchrab1..scUchrab1)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmPass,         kbF4;
          '',                   cmDoTable1,     kbAltF2;
          '',                   cmDoTable2,     kbAltE;
          '',                   cmCtrlF2,       kbCtrlF2;
          '',                   cmCtrlF3,       kbCtrlF3;
          '',                   cmprintbase,    kbctrlr;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmQuit,         kbAltX;
          '',                   cmsearchsubstr, kbctrlS;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',                   cmPickClass,    kbAltC;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scintSpr..scintSpr)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmCtrlT,        kbCtrlT;
          ''            ,       cmEdit,         kbF4;
          ''             ,      cmEdit,         kbENTER;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scintlsc..scintlsc)
        {
          '~F1~ Помощь' ,               cmHelp,      kbF1;
          '~F7~ Добавить',              cmAddNewRec, kbF7;
          '~F8~ Удалить',               cmDelete,    kbF8;
          '~Alt+F10~Локальное меню',    cmHotKeys,   kbAltF10;
          '~Esc~ Закрыть',              cmClose,     kbAltF3;
          '',                           cmdotable,   kbAltC;
          '',                           cmCtrlC,     kbAltB;
          '',                           cmShiftF1,   kbAltE;
          '',                           cmValue3,    kbAltR;
          '',                           cmAccording, kbAltS;
          ''             ,      cmEdit,         kbF4;
          '',                   cmCtrlT,        kbCtrlT;
          ''             ,      cmEdit,         kbENTER;
          ''             ,      cmDefault,      kbENTER;
          '',                   cmprintbase,    kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          #Std_Stat
        }

        (scprnarmy..scprnarmy)

        {
          '~F1~ Помощь',   cmHelp,         kbF1;
          '~F7~ Добавить', cmInsert,       kbF7;
          '~F8~ Удалить',  cmDelete,       kbF8;
          '~F3~ Выбор',    cmPick,         kbF3;
          '~Esc~ Выход',   cmClose,        kbAltF3;
          '',               cmSaveDoc,           kbCtrlF2;
          '',               cmRestoreDoc,        kbCtrlF3;
          '',              cmRas,          kbCtrlEnter;
          '',              cmAllNar,       kbCtrlF2;
          '',              cmDELKEY,       kbSHIFTDEL;
          '',              cmSHIFTF5,      kbShiftF5;
          '',              cmPass,        kbF4;
          '',              cmF2KEY,        kbShiftF3;
          '',              cmprintbase,   kbctrlr;
          '',              cmPrintBaseGround, kbCtrlP;
          '',              cmCalculator,   kbShiftF2;
          '',              cmclose,        kbesc;
          '',              cmQuit,         kbAltX;
          '',              cmMenu,         kbF10;
          '',              cmZoom,         kbF5;
          '',              cmResize,       kbCtrlF5;
          '',              cmNext,         kbF6;
          '',              cmPrev,         kbShiftF6;
          '',              cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (sci178prnarmy..sci178prnarmy)

        {
          '~F1~ Помощь',   cmHelp,         kbF1;
          '~F7~ Добавить', cmInsert,       kbF7;
          '~F8~ Удалить',  cmDelete,       kbF8;
          '~Esc~ Выход',   cmClose,        kbAltF3;
          '',              cmSaveDoc,      kbCtrlF2;
          '',              cmRestoreDoc,   kbCtrlF3;
          '',              cmRas,          kbCtrlEnter;
          '',              cmAllNar,       kbCtrlF2;
          '',              cmDELKEY,       kbSHIFTDEL;
          '',              cmSHIFTF5,      kbShiftF5;
          '',              cmPass,         kbF4;
          '',              cmF2KEY,        kbShiftF3;
          '',              cmprintbase,    kbctrlr;
          '',              cmPrintBaseGround, kbCtrlP;
          '',              cmCalculator,   kbShiftF2;
          '',              cmclose,        kbesc;
          '',              cmQuit,         kbAltX;
          '',              cmMenu,         kbF10;
          '',              cmZoom,         kbF5;
          '',              cmResize,       kbCtrlF5;
          '',              cmNext,         kbF6;
          '',              cmPrev,         kbShiftF6;
          '',              cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scpickbr..scpickbr)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmInsert,       kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          ''             ,      cmDefault,      kbF2;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scKty1..scKty1)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          ''                ,   cmPass,         kbF4;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmshiftf5,      kbshiftf5;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmclose,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }

        (scpBon..scpBon)
        {
          '~Ins~ Пометить',cmdoins,     kbINS;
          '~+~ Помет.всех',cmAllIns, kbGrayPlus;
          '~-~ Отмен.всех',cmAllUnIns, kbGrayMinus;
          '~F1~ Помощь',        cmHelp,         kbF1;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmshiftf5,      kbshiftf5;
          '',                   cmClose,        kbAltF3;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }

        (scprbonus..scprbonus)
        {
          '~F3~ Выб',     cmPick,         kbF3;
          '~F7~ Доб',     cmInsert,       kbF7;
          '~F8~ Удл',     cmDelete,       kbF8;
          '~Esc~ Вых',    cmClose,        kbAltF3;
          'Параметры',    cmF2KEY,        kbShiftF3;
          'Удержания',    cmF9KEY,        kbSHIFTF9;
          'Очистить',     cmDELKEY,       kbSHIFTDEL;
          '~F1~ Помощь',  cmHelp,         kbF1;
          '',              cmINSKEY,      kbINS;
          '',              cmF7KEY,       kbShiftF7;
          '',              cmF6KEY,       kbShiftF6;
          '',              cmALTF9,       kbaltF9;
          '',              cmprintbase,   kbctrlr;
          '',              cmPrintBaseGround, kbCtrlP;
          '',              cmCalculator,   kbShiftF2;
          '',              cmQuit,         kbAltX;
          '',              cmMenu,         kbF10;
          '',              cmZoom,         kbF5;
          '',              cmResize,       kbCtrlF5;
          '',              cmNext,         kbF6;
          '',              cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }
        (scintv..scintv)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '',                   cmEdit,         kbF4;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Alt+B~ Фильтр',     cmAltB,         kbAltB;
          '~Ctrl+T~ Cформировать',   cmCtrlT,   kbCtrlT;
          '~Ctrl+C~ Переформировать',cmCtrlC,   kbCtrlC;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmprintbase,    kbctrlr;
          #Std_Stat
        }
        (scintvre..scintvre)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F4~ Переформировать', cmEdit,       kbF4;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmDefault,      kbCtrlP;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }
        (scinto..scinto)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Ins~ Пометить',     cmdoins,        kbINS;
          '~+~ Пометить все',   cmAllIns,       kbGrayPlus;
          '~-~ Отменить все',   cmAllUnIns,     kbGrayMinus;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmCtrlP,        kbCtrlP;
          '',                   cmCtrlP,        kbEnter;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scbutf..scbutf)
        {
          '~F1~ Помощь',         cmHelp,         kbF1;
          '~Enter~ Формирование',cmDefault,      kbF2;
          '~Esc~ Выход',         cmClose,        kbAltF3;
          '',                    cmshiftf1,      kbAltE;
          '',                    cmLastHelp,     kbAltF1;
          '',                    cmCalculator,   kbShiftF2;
          '',                    cmZoom,         kbF5;
          '',                    cmResize,       kbCtrlF5;
          '',                    cmQuit,         kbAltX;
          '',                    cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scKlndbut..scKlndbut)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmDefault,      kbF2;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scbansel..scbansel)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F4~ Изменить',      cmEdit,         kbF4;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~Ins~',              cmdoins,        kbINS;
          '~+~',                cmAllIns,       kbGrayPlus;
          '~-~',                cmAllUnIns,     kbGrayMinus;
          '~Ctrl+Enter~ Печать',cmOt,           kbCTRLEnter;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          ''             ,      cmDefault,      kbENTER;
          '',                   cmPrint,        kbCtrlP;
          '',                   cmdotable,      kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }
        (scenter3z..scenter3z)

        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F3~ Выбор',         cmPick,         kbF3;
          '~Enter~ Ввод',       cmValue2,       kbEnter;
          '~Esc~ Отказ',        cmclose,        kbesc;
          ''           ,        cmClose,        kbAltF3;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }
        (scenter2z..scenter2z)

        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Enter~ Ввод',       cmValue2,       kbEnter;
          '~Esc~ Отказ',        cmclose,        kbesc;
          ''           ,        cmClose,        kbAltF3;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }
        (scenterz..scenterz)

        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Enter~ Ввод',       cmDefault,      kbEnter;
          '~Esc~ Отказ',        cmclose,        kbesc;
          ''           ,        cmClose,        kbAltF3;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scF_1_12..scF_1_12)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Shift+Ins~ Перенести текущее значение премии в предыдущее',   cmINSKEY,  kbSHIFTINS;
          '~Shift+Del~ Обнулить вознаграждение по помеченным',  cmDELKEY,  kbSHIFTDEL;
          '~Shift+F5~ Переформировать поля вознаграждений',     cmshiftf5, kbshiftf5;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }
        (scxarpredz..scxarpredz)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Ctrl+F2~ Запомнить',cmCtrlF2,       kbCtrlF2;
          '~Ctrl+F3~ Установить',cmCtrlF3,      kbCtrlF3;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                 cmSHIFTF5,      kbShiftF5;
          '',                   cmPass,         kbF4;
          '',                   cmDelete,       kbF8;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          ''              ,   cmDoTable,     kbALTC;
          ''              ,   cmDoTable2,    kbALTR;
          ''              ,   cmDoTable,     kbALTP;

        }
        (scxarpredz1..scxarpredz1)
        {
          '~F1~ Помощь',        cmHelp,kbF1;
          '~F3~ Выбор',         cmPick,kbF3;
          '~Ctrl+F2~ Запомнить',cmCtrlF2,       kbCtrlF2;
          '~Ctrl+F3~ Установить',cmCtrlF3,      kbCtrlF3;
          '~Esc~ Закрыть',      cmClose,kbAltF3;
          '',                   cmSHIFTF5,      kbShiftF5;
          '',                   cmPass,         kbF4;
          '',                   cmDelete,       kbF8;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          ''              ,   cmDoTable,     kbALTC;
          ''              ,   cmDoTable2,    kbALTR;
          ''              ,   cmDoTable,     kbALTP;

        }

        (scVOView..scVOView)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '~Alt+B~ Фильтр',     cmCtrlC,        kbAltB;
          '',                   cmShiftF1,      kbAltE;
          '',                   cmShiftF5,      kbShiftF5;
          '',                   cmShiftF9,      kbShiftF9;
          '',                   cmCtrlT,        kbCtrlT;
          '',                   cmHotKeys,      kbAltF10;
          ''            ,       cmEdit,         kbF4;
          ''             ,      cmEdit,         kbENTER;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (sci1InCtrlC..sci1InCtrlC)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Ins~ Пометить',     cmdoins,        kbINS;
          '~+~ Пометить всех',  cmAllIns,       kbGrayPlus;
          '~-~ Отменить всех',  cmAllUnIns,     kbGrayMinus;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '~Alt+B~ Фильтр',     cmCtrlC,        kbAltB;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '',                   cmprintbase,    kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          ''             ,      cmEdit,         kbF4;
          ''             ,      cmDefault,      kbENTER;
          '',                   cmPrint,        kbCtrlP;
          '',                   cmdotable,      kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmShiftF1,      kbAltE;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scsysmbf2..scsysmbf2)

        {
          '~F1~ Помощь',         cmHelp,         kbF1;
          '~Enter~ Изменить',      cmdefault,      kbf4;
          '~F7~ Добавить ' ,      cmInsert,       kbF7;
          '~F8~ Удалить',        cmDelete,       kbF8;
          '~Esc~ Закрыть',       cmClose,        kbAltF3;
          '~Alt+B~ Фильтр',      cmCtrlC,        kbAltB;
          '',                    cmdoins,        kbINS;
          '',                    cmCalculator,   kbShiftF2;
          '',                    cmQuit,         kbAltX;
          '',                    cmclose,        kbesc;
          '',                    cmMenu,         kbF10;
          '',                    cmZoom,         kbF5;
          '',                    cmResize,       kbCtrlF5;
          '',                    cmNext,         kbF6;
          '',                    cmPrev,         kbShiftF6;
          '',                    cmSysMenu,      kbCtrlF10;
          '',                    cmSHIFTF5,      kbShiftF5;
          '',                    cmAllNar,       kbCtrlF2;
          '',                    cmPickClass,    kbAltC;
          '',                    cmNal,          kbAltF;
          '',                    cmHotKeys,      kbAltF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          '',                   cmprintbase,    kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;

        }

        (scavred..scavred)

        {
          '~F1~ Помощь',             cmHelp,         kbF1;
          '~Shift+Ins~ Аванс не получен',  cmdoins,  kbSHIFTINS;
          '~F4~ Изменить',           cmEdit,         kbF4;
          '~Esc~ Зак.',              cmCancel,       kbEsc;
          '',                        cmdelkey,       kbShiftDel;
          '',                        cmF9KEY,        kbSHIFTF9;
          '',                        cmCtrlC,        kbAltB;
          '',                        cmCalculator,   kbShiftF2;
          '',                        cmQuit,         kbAltX;
          '',                        cmclose,        kbesc;
          '',                        cmMenu,         kbF10;
          '',                        cmZoom,         kbF5;
          '',                        cmResize,       kbCtrlF5;
          '',                        cmNext,         kbF6;
          '',                        cmPrev,         kbShiftF6;
          '',                        cmSysMenu,      kbCtrlF10;
          '',                        cmEvaluateAndModify, kbCtrlF4;
          '',                        cmPrintBase,    kbCtrlR;
          '',                        cmPrintBaseGround, kbCtrlP;
          '',                        cmHotKeys,      kbAltF10;
          '',                        cmFormAdvance,  kbF7;
          '',                        cmRas,          kbShiftF5;
          '',                        cmF9KEY,        kbShiftF9;
          '',                        cmdelkey,       kbShiftDel;
          #Ins
          #PlusMinus
        }

        (scEufam2..scEufam2)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Ins~ Пометить',     cmdoins,        kbINS;
          '~+~ Пометить всех',  cmAllIns,       kbGrayPlus;
          '~-~ Отменить всех',  cmAllUnIns,     kbGrayMinus;
          '~Alt+S~ Сортировка ',cmAccording,    kbAltS;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmEdit,         kbF4;
          '',                   cmAddNewRec,    kbF7;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;

        }

        (scEufam3..scEufam3)
        {
          '~Ins~ Пометить',cmdoins,     kbINS;
          '~+~ Помет.всех',cmAllIns, kbGrayPlus;
          '~-~ Отмен.всех',cmAllUnIns, kbGrayMinus;
          #Std_Stat
          '~Shift+F5~ Сумма',   cmAllSum,       kbSHIFTF5;
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F4~ Изменить',      cmEdit,         kbF4;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~Alt+S~ Сортировка ',cmAccording,    kbAltS;
        }

        (scEufam4..scEufam4)
        {
          '~Ins~ Пометить',cmdoins,     kbINS;
          '~+~ Помет.всех',cmAllIns, kbGrayPlus;
          '~-~ Отмен.всех',cmAllUnIns, kbGrayMinus;
          #Std_Stat
          '~Shift+F5~ Сумма',   cmAllSum,       kbSHIFTF5;
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F3~ Выбор',         cmPick,         kbF3;
          '~F4~ Изменить',      cmEdit,         kbF4;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~Alt+S~ Сортировка ',cmAccording,    kbAltS;
        }
        (scpickans..scpickans)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F4~ Изменить',      cmEdit,         kbF4;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~Alt+S~ Сортировка ',cmAccording,    kbAltS;
          '~Enter~ Выбор',      cmDefault,      kbF2;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                   cmclose,        kbesc;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scxarpreds..scxarpreds)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Alt+S~ Сортировка ',cmAccording,    kbAltS;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '',                 cmSHIFTF5,      kbShiftF5;
          '',                   cmPass,         kbF4;
          '',                   cmDelete,       kbF8;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          ''              ,   cmDoTable,     kbALTC;
          ''              ,   cmDoTable2,    kbALTR;
          ''              ,   cmDoTable,     kbAltE;
        }
        (scArOtp..scArOtp)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Alt+F10~Локальное меню',cmHotKeys,  kbAltF10;
          '~Esc~ Закрыть',      cmclose,        kbesc;
          '~Ctrl+P~Печать',     cmPrint,        kbCtrlP;
          '',                   cmDoTable,      kbAltP;
          '',                   cmAddNewRec,    kbCtrlEnter;
          '',                   cmValue10,      kbshiftf6;
          '',                   cmpass,         kbF4;
          '',                   cmClose,        kbAltF3;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmshiftf5,      kbshiftf5;
          '',                   cmshiftf7,      kbshiftf7;
          '',                 cmExtendedDelete, kbShiftF8;
          '',                   cmShiftF9,      kbShiftF9;
          '',                   cmedit,         kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',              cmEvaluateAndModify, kbCtrlF4;
          '',                   cmAlt1,         kbAlt1;
          '',                   cmAlt5,         kbAlt5;
          '',                   cmSetupReport,  kbCtrlR;
        }

        (scArOtp1..scArOtp1)  // от scArOtp отличается только наличием '~F3~ Выбор'
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F3~ Выбор',         cmPick,         kbF3;
          '~Alt+F10~Локальное меню',cmHotKeys,  kbAltF10;
          '~Esc~ Закрыть',      cmclose,        kbesc;
          '~Ctrl+P~Печать',     cmPrint,        kbCtrlP;
          '',                   cmDoTable,      kbAltP;
          '',                   cmAddNewRec,    kbCtrlEnter;
          '',                   cmValue10,      kbshiftf6;
          '',                   cmpass,         kbF4;
          '',                   cmClose,        kbAltF3;
          '',                   cmshiftf1,      kbAltE;
          '',                   cmshiftf5,      kbshiftf5;
          '',                   cmshiftf7,      kbshiftf7;
          '',                 cmExtendedDelete, kbShiftF8;
          '',                   cmShiftF9,      kbShiftF9;
          '',                   cmedit,         kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',              cmEvaluateAndModify, kbCtrlF4;
          '',                   cmAlt1,         kbAlt1;
          '',                   cmAlt5,         kbAlt5;
          '',                   cmSetupReport,  kbCtrlR;
        }

(sci147CEEnEsc..sci147CEEnEsc)
{
  #F1
  '~F4~ Изменить',              cmEdit,                 kbF4;
  '~F7~ Добавить',              cmAddNewRec,            kbF7;
  '~Ctrl+Enter~ Формат',        cmValue1,               kbCtrlEnter;
  '~Enter~ Выбор',              cmDefault,              kbEnter;
  '~Esc~ Выход',                cmClose,                kbAltF3;
  #Std_Stat
}

(sci178C2C3Esc..sci178C2C3Esc)
{
  #F1
  '~F7~ Добавить',        cmInsert,               kbF7;
  '~F8~ Удалить',         cmDelete,               kbF8;
  '~Ctrl+F2~ Запомнить',  cmCtrlF2,               kbCtrlF2;
  '~Ctrl+F3~ Установить', cmCtrlF3,               kbCtrlF3;
  '~Esc~ Выход',          cmClose,                kbAltF3;
  #Std_Stat
}

(sci1378EscBrigadeDuty..sci1378EscBrigadeDuty)
{
  #F1
  '~F3~ Выбор',                 cmPick,                 kbF3;
  '~F7~ Добавить',              cmInsert,               kbF7;
  '~F8~ Удалить',               cmDelete,               kbF8;
  '~Esc~ Выход',                cmClose,                kbAltF3;
  '~Alt+B~ Фильтр',             cmFilterSave,           kbAltB;
  '',                           cmDutyInformation,      kbAltL;
  '',                           cmWorkAddPayments,      kbAltH;
  '',                           cmDutyAddPayments,      kbAltY;
  '',                           cmControlForm,          kbAltR;
  '',                           cmBrigadeDutyImport,    kbAltV;
  '',                           cmBrigadeDutyCalc,      kbAltC;
  '',                           cmFinalForm,            kbAltN;
  '',                           cmKillDistributed,      kbAltD;
  '',                           cmGroupingCard,         kbAltU;
  #Std_Stat
}

(sci178EscBrigadeDuty..sci178EscBrigadeDuty)
{
  #F1
  '~F7~ Добавить',              cmInsert,               kbF7;
  '~F8~ Удалить',               cmDelete,               kbF8;
  '~Esc~ Выход',                cmClose,                kbAltF3;
  '~Alt+B~ Фильтр',             cmFilterSave,           kbAltB;
  '',                           cmDutyInformation,      kbAltL;
  '',                           cmWorkAddPayments,      kbAltH;
  '',                           cmDutyAddPayments,      kbAltY;
  '',                           cmControlForm,          kbAltR;
  '',                           cmBrigadeDutyImport,    kbAltV;
  '',                           cmBrigadeDutyCalc,      kbAltC;
  '',                           cmFinalForm,            kbAltN;
  '',                           cmKillDistributed,      kbAltD;
  '',                           cmGroupingCard,         kbAltU;
  #Std_Stat
}

(sci178S5EnEsc..sci178S5EnEsc)
{
  #F1
  '~F7~ Добавить',            cmInsert,               kbF7;
  '~F8~ Удалить',             cmDelete,               kbF8;
  '~Enter~ Ввод',             cmDefault,              kbEnter;
  '~Esc~ Выход',              cmClose,                kbAltF3;
  '',                         cmShiftF5,              kbShiftF5;
  #Std_Stat
}

(sci1378S5EnEsc..sci1378S5EnEsc)
{
  #F1
  '~F3~ Выбор',               cmPick,                 kbF3;
  '~F7~ Добавить',            cmInsert,               kbF7;
  '~F8~ Удалить',             cmDelete,               kbF8;
  '~Esc~ Выход',              cmClose,                kbAltF3;
  '~Enter~ Ввод',             cmDefault,              kbEnter;
  '',                         cmShiftF5,              kbShiftF5;
  #Std_Stat
}


(sci1378EscRouting..sci1378EscRouting)
{
  #F1
  '~F3~ Выбор',                 cmPick,                 kbF3;
  '~F7~ Добавить',              cmInsert,               kbF7;
  '~F8~ Удалить',               cmDelete,               kbF8;
  '~Esc~ Выход',                cmClose,                kbAltF3;
  '~Alt+B~ Фильтр',             cmFilterSave,           kbAltB;
  '',                           cmDutyInformation,      kbAltL;
  '',                           cmWorkAddPayments,      kbAltH;
  '',                           cmDutyAddPayments,      kbAltY;
  '',                           cmRoutingControlForm,   kbAltR;
  '',                           cmRoutingCalc,          kbAltC;
  '',                           cmRoutingFinalForm,     kbAltN;
  '',                           cmKillDistributed,      kbAltD;
  '',                           cmGroupingCard,         kbAltU;
  #Std_Stat
}

(sci178EscRouting..sci178EscRouting)
{
  #F1
  '~F7~ Добавить',              cmInsert,               kbF7;
  '~F8~ Удалить',               cmDelete,               kbF8;
  '~Esc~ Выход',                cmClose,                kbAltF3;
  '~Alt+B~ Фильтр',             cmFilterSave,           kbAltB;
  '',                           cmDutyInformation,      kbAltL;
  '',                           cmWorkAddPayments,      kbAltH;
  '',                           cmDutyAddPayments,      kbAltY;
  '',                           cmRoutingControlForm,   kbAltR;
  '',                           cmRoutingCalc,          kbAltC;
  '',                           cmRoutingFinalForm,     kbAltN;
  '',                           cmKillDistributed,      kbAltD;
  '',                           cmGroupingCard,         kbAltU;
  #Std_Stat
}

(sci178EscRates..sci178EscRates)
{
  '~F1~ Помощь',     cmHelp,         kbF1;
  '~F7~ Добавить',   cmInsert,       kbF7;
  '~F8~ Удалить',    cmDelete,       kbF8;
  '~Alt+F2~ Формат', cmDoTable1,     kbAltF2;
  '~Esc~ Выход',     cmClose,        kbAltF3;
  #Std_Stat
}

(sci1378EscRates..sci1378EscRates)
{
  '~F1~ Помощь',   cmHelp,         kbF1;
  '~F3~ Выбор',    cmPick,         kbF3;
  '~F7~ Добавить', cmInsert,       kbF7;
  '~F8~ Удалить',  cmDelete,       kbF8;
  '~Alt+F2~ Формат', cmDoTable1,   kbAltF2;
  '~Esc~ Выход',   cmClose,        kbAltF3;
  #Std_Stat
}

(sci147EnEscRates..sci147EnEscRates)
{
  '~F1~ Помощь',        cmHelp,         kbF1;
  '~F4~ Изменить',      cmEdit,         kbF4;
  '~F7~ Добавить',      cmAddNewRec,    kbF7;
  '~Alt+F2~ Формат',    cmDoTable1,     kbAltF2;
  '~Enter~ Выбор',      cmDefault,      kbF2;
  '~Esc~ Закрыть',      cmClose,        kbAltF3;
  #Std_Stat
}

(sci147EnEscInsPMRates..sci147EnEscInsPMRates)
{
#F1
  '~F4~ Изменить',      cmEdit,         kbF4;
  '~F7~ Добавить',      cmAddNewRec,    kbF7;
  '~Alt+F2~ Формат',    cmDoTable1,     kbAltF2;
  '~Enter~ Выбор',      cmDefault,      kbEnter;
#Ins
#PlusMinus
#Std_Stat
}

(sci178EscDutyFace..sci178EscDutyFace)
{
#F1
  '~F7~ Добавить',              cmInsert,               kbF7;
  '~F8~ Удалить',               cmDelete,               kbF8;
  '~Alt+F2~ Формат',            cmDoTable1,             kbAltF2;
  '~Esc~ Выход',                cmClose,                kbAltF3;
#Std_Stat
}

(sci1378EscDutyFace..sci1378EscDutyFace)
{
#F1
  '~F3~ Выбор',                 cmPick,                 kbF3;
  '~F7~ Добавить',              cmInsert,               kbF7;
  '~F8~ Удалить',               cmDelete,               kbF8;
  '~Alt+F2~ Формат',            cmDoTable1,             kbAltF2;
  '~Esc~ Выход',                cmClose,                kbAltF3;
#Std_Stat
}

(sci1478EnEsAlt..sci1478EnEsAlt)
{
        '~F1~ Помощь',          cmHelp,         kbF1;
        '~Enter~ Выбор',        cmDefault,      kbENTER;
        '~F4~ Изменить',        cmEdit,         kbf4;
        '~F7~ Добавить' ,       cmInsert,       kbF7;
        '~F8~ Удалить',         cmDelete,       kbF8;
        '~Esc~ Закрыть',        cmClose,        kbAltF3;
        '~Alt+B~ Фильтр',       cmCtrlC,        kbAltB;
        '',                     cmdoins,        kbINS;
        '',                     cmCalculator,   kbShiftF2;
        '',                     cmQuit,         kbAltX;
        '',                     cmclose,        kbesc;
        '',                     cmMenu,         kbF10;
        '',                     cmZoom,         kbF5;
        '',                     cmResize,       kbCtrlF5;
        '',                     cmNext,         kbF6;
        '',                     cmPrev,         kbShiftF6;
        '',                     cmSysMenu,      kbCtrlF10;
        '',                     cmSHIFTF5,      kbShiftF5;
        '',                     cmAllNar,       kbCtrlF2;
        '',                     cmEvaluateAndModify, kbCtrlF4;
}

(sci1378EscInsPMBrigadeDuty..sci1378EscInsPMBrigadeDuty)
{
  #F1
  #Ins
  #PlusMinus
  '~F3~ Выбор',                 cmPick,                 kbF3;
  '~F7~ Добавить',              cmInsert,               kbF7;
  '~F8~ Удалить',               cmDelete,               kbF8;
  '~Esc~ Выход',                cmClose,                kbAltF3;
  '~Alt+B~ Фильтр',             cmFilterSave,           kbAltB;
  '',                           cmDutyInformation,      kbAltL;
  '',                           cmWorkAddPayments,      kbAltH;
  '',                           cmDutyAddPayments,      kbAltY;
  '',                           cmControlForm,          kbAltR;
  '',                           cmBrigadeDutyImport,    kbAltV;
  '',                           cmBrigadeDutyCalc,      kbAltC;
  '',                           cmFinalForm,            kbAltN;
  '',                           cmKillDistributed,      kbAltD;
  '',                           cmGroupingCard,         kbAltU;
  #Std_Stat
}

(sci178EscInsPMBrigadeDuty..sci178EscInsPMBrigadeDuty)
{
  #F1
  #Ins
  #PlusMinus
  '~F7~ Добавить',              cmInsert,               kbF7;
  '~F8~ Удалить',               cmDelete,               kbF8;
  '~Esc~ Выход',                cmClose,                kbAltF3;
  '~Alt+B~ Фильтр',             cmFilterSave,           kbAltB;
  '',                           cmDutyInformation,      kbAltL;
  '',                           cmWorkAddPayments,      kbAltH;
  '',                           cmDutyAddPayments,      kbAltY;
  '',                           cmControlForm,          kbAltR;
  '',                           cmBrigadeDutyImport,    kbAltV;
  '',                           cmBrigadeDutyCalc,      kbAltC;
  '',                           cmFinalForm,            kbAltN;
  '',                           cmKillDistributed,      kbAltD;
  '',                           cmGroupingCard,         kbAltU;
  #Std_Stat
}
        (scsumudnap..scsumudnap)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          '~Alt+F10~Локальное меню',cmHotKeys, kbAltF10;
          '',                 cmSHIFTF5,      kbShiftF5;
          '',                   cmPass,         kbF4;
          '',                   cmDelete,       kbF8;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          ''              ,   cmDoTable,     kbALTC;
          ''              ,   cmDoTable2,    kbALTR;
          ''              ,   cmDoTable,     kbAltE;

        }
        (scsumudnap1..scsumudnap1)
        {
          '~F1~ Помощь',        cmHelp,kbF1;
          '~F3~ Выбор',         cmPick,kbF3;
          '~Esc~ Закрыть',      cmClose,kbAltF3;
          '~Alt+F10~Локальное меню',cmHotKeys, kbAltF10;
          '',                   cmSHIFTF5,      kbShiftF5;
          '',                   cmPass,         kbF4;
          '',                   cmDelete,       kbF8;
          '',                   cmprintbase,   kbctrlr;
          '',                   cmPrintBaseGround, kbCtrlP;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmQuit,         kbAltX;
          '',                   cmclose,        kbesc;
          '',                   cmMenu,         kbF10;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmNext,         kbF6;
          '',                   cmPrev,         kbShiftF6;
          '',                   cmSysMenu,      kbCtrlF10;
          '',              cmEvaluateAndModify, kbCtrlF4;
          ''              ,   cmDoTable,     kbALTC;
          ''              ,   cmDoTable2,    kbALTR;
          ''              ,   cmDoTable,     kbAltE;

        }
        (scintL..scintL)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~F4~ Изменить',      cmEdit,         kbF4;
          '~Alt+F10~Локальное меню',cmHotKeys, kbAltF10;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          ''             ,      cmDefault,      kbENTER;
          '',                   cmprintbase,    kbctrlr;
          '',                   cmPrint,        kbCtrlP;
          '',                   cmdotable,      kbAltC;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          ''              ,     cmCtrlC,        kbAltB;
          '',                   cmShiftF1,      kbAltE;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

        (scKlVO..scKlVO)
        {
          '~F1~ Помощь',        cmHelp,         kbF1;
          '~F4~ Изменить',      cmEdit,         kbF4;
          '~F7~ Добавить',      cmAddNewRec,    kbF7;
          '~F8~ Удалить',       cmDelete,       kbF8;
          '~Alt+B~ Фильтр',     cmFilterSave,   kbAltB;
          '~Esc~ Закрыть',      cmClose,        kbAltF3;
          ''             ,      cmDefault,      kbENTER;
          '',                   cmPickClass,    kbAltC;
          '',                   cmPickAttr,     kbAltA;
          '',                   cmprintbase,    kbctrlr;
          '',                   cmPrint,        kbCtrlP;
          '',                   cmCalculator,   kbShiftF2;
          '',                   cmLastHelp,     kbAltF1;
          '',                   cmZoom,         kbF5;
          '',                   cmResize,       kbCtrlF5;
          '',                   cmQuit,         kbAltX;
          '',                   cmMenu,         kbF10;
          '',                   cmHotKeys,      kbAltF10;
          '',                   cmPrint,        kbCtrlP;
          '',              cmEvaluateAndModify, kbCtrlF4;
        }

(sci178EscDuty..sci178EscDuty)
{
  #F1

  '~F7~ Добавить',              cmInsert,               kbF7;
  '~F8~ Удалить',               cmDelete,               kbF8;
  '~Esc~ Выход',                cmClose,                kbAltF3;

  '',                           cmMarkUnMark,           kbIns;
  '',                           cmSelectAll,            kbGrayPlus;
  '',                           cmUnSelectAll,          kbGrayMinus;
  '',                           cmInvertAll,            kbGrayMul;

  '',                           cmProcessAddPayments,   kbCtrlG;
  '',                           cmWorkAddPayments,      kbAltH;
  '',                           cmDutyAddPayments,      kbAltY;
  '',                           cmBrigadeDutyCalc,      kbCtrlC;
  '',                           cmFinalForm,            kbAltN;
  '',                           cmControlForm,          kbAltR;
  '',                           cmKillDistributed,      kbCtrlD;
  #Std_Stat
}

(sci1378EscDuty..sci1378EscDuty)
{
  #F1

  '~F3~ Выбор',                 cmPick,                 kbF3;
  '~F7~ Добавить',              cmInsert,               kbF7;
  '~F8~ Удалить',               cmDelete,               kbF8;
  '~Esc~ Выход',                cmClose,                kbAltF3;

  '',                           cmMarkUnMark,           kbIns;
  '',                           cmSelectAll,            kbGrayPlus;
  '',                           cmUnSelectAll,          kbGrayMinus;
  '',                           cmInvertAll,            kbGrayMul;

  '',                           cmProcessAddPayments,   kbCtrlG;
  '',                           cmWorkAddPayments,      kbAltH;
  '',                           cmDutyAddPayments,      kbAltY;
  '',                           cmBrigadeDutyCalc,      kbCtrlC;
  '',                           cmFinalForm,            kbAltN;
  '',                           cmControlForm,          kbAltR;
  '',                           cmKillDistributed,      kbCtrlD;
  #Std_Stat
}

(sci178EscFace..sci178EscFace)
{
  #F1

  '~F7~ Добавить',              cmInsert,               kbF7;
  '~F8~ Удалить',               cmDelete,               kbF8;
  '~Esc~ Выход',                cmClose,                kbAltF3;

  '',                           cmProcessAddPayments,   kbCtrlG;
  '',                           cmWorkAddPayments,      kbAltH;
  '',                           cmDutyAddPayments,      kbAltY;
  '',                           cmBrigadeDutyCalc,      kbCtrlC;
  '',                           cmFinalForm,            kbAltN;
  '',                           cmControlForm,          kbAltR;
  '',                           cmKillDistributed,      kbCtrlD;
  #Std_Stat
}

(sci1378EscFace..sci1378EscFace)
{
  #F1

  '~F3~ Выбор',                 cmPick,                 kbF3;
  '~F7~ Добавить',              cmInsert,               kbF7;
  '~F8~ Удалить',               cmDelete,               kbF8;
  '~Esc~ Выход',                cmClose,                kbAltF3;

  '',                           cmProcessAddPayments,   kbCtrlG;
  '',                           cmWorkAddPayments,      kbAltH;
  '',                           cmDutyAddPayments,      kbAltY;
  '',                           cmBrigadeDutyCalc,      kbCtrlC;
  '',                           cmFinalForm,            kbAltN;
  '',                           cmControlForm,          kbAltR;
  '',                           cmKillDistributed,      kbCtrlD;
  #Std_Stat
}
(sci14AltBEsc..sci14AltBEsc)
{
#F1
  '~F4~ Изменить',          cmEdit,         kbF4;
  '~Alt+B~ Фильтр',         cmFilterSave,   kbAltB;
  '~Esc~ Выход',            cmClose,        kbAltF3;
  '',                       cmCalculator,   kbShiftF2;
  '',                       cmQuit,         kbAltX;
  '',                       cmMenu,         kbF10;
  '',                       cmZoom,         kbF5;
  '',                       cmResize,       kbCtrlF5;
  '',                       cmNext,         kbF6;
  '',                       cmPrev,         kbShiftF6;
  '',                       cmSysMenu,      kbCtrlF10;
  '',                  cmEvaluateAndModify, kbCtrlF4;
}

(scLschetKadr..scLschetKadr)
  {
  #F1
  '~F3~ Выбор',         cmPick,         kbF3;
  '~Alt+C~ Смежные данные',  cmdotable, kbAltC;
  '~Esc~ Закрыть',      cmClose,        kbAltF3;
  #Std_Stat
  }

(scLschetKadr1..scLschetKadr1)
  {
  #F1
  '~Alt+C~ Смежные данные',  cmdotable, kbAltC;
  '~Esc~ Закрыть',      cmClose,        kbAltF3;
  #Std_Stat
  }

(scLschetKadr2..scLschetKadr2)
  {
  #F1
  '~F3~ Выбор',         cmPick,         kbF3;
  '~Esc~ Закрыть',      cmClose,        kbAltF3;
  #Std_Stat
  }

(sci178InsPMEsc..sci178InsPMEsc)
  {
    '~F1~ Помощь',        cmHelp,         kbF1;
    '~F7~ Добавить',      cmInsert,       kbF7;
    '~F8~ Удалить',       cmDelete,       kbF8;
    #Ins
    #PlusMinus
    '~Esc~ Выход',        cmClose,        kbAltF3;
    '',                   cmInsKey,       kbShiftIns;
    '',                   cmDelKey,       kbShiftDel;
    '',                   cmShiftF5,      kbShiftF5;
    '',                   cmShiftF7,      kbShiftF7;
    '',                   cmCtrlC,        kbAltB;
    #Std_Stat
  }
 (sci1478InsMPEsc..sci1478InsMPEsc)
  {
  #F1
    '~F4~ Изменить',              cmEdit,                 kbF4;
    '~F7~ Добавить',              cmInsert,               kbF7;
    '~F8~ Удалить',               cmDelete,               kbF8;
    #Ins
    #PlusMinus
    '~Esc~ Выход',                cmClose,                kbAltF3;
    '',                           cmDefault,              kbF2;
    #Std_Stat
  }

  (sci1478EscInsC8CC..sci1478EscInsC8CC)
   {
   #F1
     '~F4~ Изменить',              cmEdit,                 kbF4;
     '~F7~ Добавить',              cmInsert,               kbF7;
     '~F8~ Удалить',               cmDelete,               kbF8;
     '~Esc~ Выход',                cmClose,                kbAltF3;
     #Ins
     #PlusMinus
     '',                           cmDeleteFiltered,       kbCtrlF8;
     '',                           cmCalc,                 kbCtrlC;
     #Std_Stat
   }

  (sci1378InsMPEsc..sci1378InsMPEsc)
  {
    '~F1~ Помощь',        cmHelp,         kbF1;
    '~F3~ Выбор',         cmPick,         kbF3;
    '~F7~ Добавить',      cmInsert,       kbF7;
    '~F8~ Удалить',       cmDelete,       kbF8;
    #Ins
    #PlusMinus
    '~Esc~ Закрыть',      cmClose,        kbAltF3;
    '',                   cmInsKey,       kbShiftIns;
    '',                   cmDelKey,       kbShiftDel;
    '',                   cmShiftF5,      kbShiftF5;
    '',                   cmShiftF7,      kbShiftF7;
    '',                   cmCtrlC,        kbAltB;
    #Std_Stat
 }
