//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Электронная отчетность РБ"
// Табличный объект : "Каталог отчетов"
//------------------------------------------------------------------------------

#ifndef __TRBTablRepCatalog_Inc__
#define __TRBTablRepCatalog_Inc__

const
  // Тип узла иерархии
  lc_RepCatalogNode_Period  : word = 1;  // период отчетов
  lc_RepCatalogNode_RepType : word = 2;  // тип отчетов
  lc_RepCatalogNode_Report  : word = 3;  // отчет
end; // const

#endif//__TRBTablRepCatalog_Inc__
