//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - "XLT отчеты"
// Константы для формирования Excel-отчетов
//------------------------------------------------------------------------------

#ifndef __xlRep_Inc__
#define __xlRep_Inc__

Const
  cgxlGal_VarSheet    = 'Gal_VarSheet';
  cgxlGal_TblSheet    = 'Gal_TblSheet';

  cgxlGalVarPrefix    = 'GalDBVar_';
  cgxlGalTblPrefix    = 'GalDBTbl_';
  cgxlGalTblFldPrefix = 'GalDBTblFld_';
  cgxlGalArrFldPostfix= '_Arr1N';
end;

#endif//__xlRep_Inc__
