// для подключения картинок к тулбарам, колонкам интерфейсов нужно задавать компонентную принадлежность

//#component "C_Denominator"
#component ""

bmDenominatorOk    bitmap "ImageDenominatorOk.bmp"
bmDenominatorError bitmap "ImageDenominatorError.bmp"
bmDenominatorLeave bitmap "ImageDenominatorLeave.bmp"
bmDenominatorClose bitmap "ImageDenominatorClose.bmp"
bmDenominatorLeaf  bitmap "ImageDenominatorLeaf.bmp"
bmDenominatorOpen  bitmap "ImageDenominatorOpen.bmp"


// для подключения картинок к локальным меню нужно задавать имена картинок без компонентной принадлежности
//#component ""
