//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Электронная отчетность РБ"
// Библиотека функций : "Проверка XML по XSD"
//------------------------------------------------------------------------------

#ifndef __TRBFuncXSDCheck_Inc__
#define __TRBFuncXSDCheck_Inc__

const
  // targetNamespace
  lc_TargetNameSpace = 'http://mns/edeclaration/xml/nds/ver3';
end; // const

#endif//__TRBFuncXSDCheck_Inc__
