//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 5.80 - модуль "Платежный календарь"
// Фильтры для интерфейса выбора
//------------------------------------------------------------------------------

Const
  cgFlViewPos_Descr     =  0; // дескриптор
  cgFlViewPos_DesGr     =  1; // группа
  cgFlViewPos_Date      =  2; // дата создания
  cgFlViewPos_DatePay   =  3; // планируемая дата погашения
  cgFlViewPos_Summa     =  4; // сумма по финобязательству
  cgFlViewPos_Direct    =  5; // направление
  cgFlViewPos_Prior     =  6; // приоритет
  cgFlViewPos_KatOrg    =  7; // контрагент
  cgFlViewPos_FpCO      =  8; // центр ответственности
  cgFlViewPos_Dogovor   =  9; // договор
  cgFlViewPos_BaseDoc   = 10; // документ-основание
  cgFlViewPos_Persons   = 11; // куратор
  cgFlViewPos_GroupOfp  = 12; // группа  ФОБ
  cgFlViewPos_AktSum    = 13; // сводное ФОБ
  cgFlViewPos_FactSym   = 14; // признак исполнения
  cgFlViewPos_FpStBud   = 15; // статья бюджета
  cgFlViewPos_Valuta    = 16; // валюта операции
  cgFlViewPos_MeanType  = 17; // тип платежного средства
End;
