//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Электронная отчетность ГОЗ"
// Библиотека функций : "Экспорт структуры отчета - МО XML"
//------------------------------------------------------------------------------

#ifndef __gzrEXMLRepStruct_Inc__
#define __gzrEXMLRepStruct_Inc__

const
  lc_XMLDateFormat = 'YYYY-MM-DD';
  lc_XMLTimeFormat = 'HH:MM:SS';
//в доке так:
//lc_XMLDateFormat = 'CCYY-MM-DD';
//lc_XMLTimeFormat = 'HH:ММ:SS';
end; // const

#endif//__gzrEXMLRepStruct_Inc__
