//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 8.10 - модуль "Платежный календарь"
// Константы ОФП ( реестр заявок )
//------------------------------------------------------------------------------

Const

  // позиции в фильтре RESWORD[1]
  cgFlViewPos_PlanDate =  0; // планируемый период оплаты
  cgFlViewPos_KatDoc   =  1; // тип заявки
  cgFlViewPos_Status   =  2; // статус
  cgFlViewPos_Prior    =  3; // приоритет
  cgFlViewPos_KatOrg   =  4; // контрагент
  cgFlViewPos_FpStBud  =  5; // статья бюджета
  cgFlViewPos_FpCO     =  6; // ЦО
  cgFlViewPos_Persons  =  7; // куратор
  cgFlViewPos_Modul    =  8; // модуль
  cgFlViewPos_FpBudAn  =  9; // Аналитика
  cgFlViewPos_FobDate  = 10; // Планируемая дата погашения
  cgFlViewPos_DateForm = 11; // Дата формирования
  cgFlViewPos_Dogovor  = 12; // Договор
  cgFlViewPos_BaseDoc  = 13; // ДО
  cgFlViewPos_KatStroy = 14; // Объект строительства
  // Отображение
  cgFlPos_DateForm     =  0; // Дата формирования
  cgFlPos_PlanDate     =  1; // планируемый период оплаты
  cgFlPos_FobDate      =  2; // Планируемая дата погашения
  cgFlPos_KatDoc       =  3; // тип заявки
  cgFlPos_Status       =  4; // статус
  cgFlPos_Prior        =  5; // приоритет
  cgFlPos_Modul        =  6; // модуль
  cgFlPos_Persons      =  7; // куратор
  cgFlPos_KatOrg       =  8; // контрагент
  cgFlPos_BaseDoc      =  9; // ДО
  cgFlPos_Dogovor      = 10; // Договор
  cgFlPos_KatStroy     = 11; // Объект строительства
  cgFlPos_FpCO         = 12; // ЦО
  cgFlPos_FpStBud      = 13; // статья бюджета
  cgFlPos_FpBudAn      = 14; // Аналитика
End;
