//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Электронная отчетность ГОЗ"
// Интерфейс редактирования : "Алгоритм расчета"
//------------------------------------------------------------------------------

#ifndef __gzrEditAlgorithmRec_Inc__
#define __gzrEditAlgorithmRec_Inc__

const
  lc_PATMemoEditorID = 'PATMemoEditorID';

  cmJumpToPosAlgCode : word = 6001;
end; // const

#endif//__gzrEditAlgorithmRec_Inc__
