//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Электронная отчетность ГОЗ"
// Persistent Object Manager : "Алгоритмы расчета"
//------------------------------------------------------------------------------

#ifndef __gzrPersAlgorithm_Inc__
#define __gzrPersAlgorithm_Inc__

// ГЕНЕРАЦИЯ GUID :: BuhXml_CreateGUID36
const
  // Отчет об исполнении ГК организацией, выполняющей ГОЗ
  lc_gzrAlg_F47_Grp_GUID      = 'DA1BAC99-EE94-41A7-AB34-295469C8E7F7';
  lc_gzrAlg_F47_Grp_v001_GUID = 'F015DE4E-271E-4742-9B87-5086ED47DDBB';
  lc_gzrAlg_F47_Alg_v001_GUID    = '8FD4BD92-0509-43AD-A21C-49EBCFB29505';
  lc_gzrAlg_F47_AlgAdd_v001_GUID = '11A136AE-71FA-4B04-AF18-59126F58A643';
end; // const

#endif//__gzrPersAlgorithm_Inc__
