#ifndef _HistoryTuneKVO_inc_INCLUDED_
#define _HistoryTuneKVO_inc_INCLUDED_

const

  cn_IncomeAcc_byMonth    = 1; //"Учет дохода в налоговой отчетности"
  cn_Acc_forRefund        = 2; //"Учет сумм возврата"

  cn_Tune_System          = 'По настройке системы';
  cn_Tune_MonthZaNach     = 'По месяцу, за который начислен';
  cn_Tune_MonthVNach      = 'По месяцу, в котором начислен';
  cn_Tune_MonthVPay       = 'По месяцу, в котором выплачен';
  cn_Tune_EquallyNach     = 'Аналогично доходу';
  cn_Tune_UchNach         = 'По месяцу учета дохода';
  cn_Tune_MonthRefund     = 'По месяцу возврата';

end;
#endif
