//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Управление бюджетом"
// Библиотека функций : "Пересчет данных по слоям аналитик"
//------------------------------------------------------------------------------

#ifndef __FpRecSlojVal_Inc__
#define __FpRecSlojVal_Inc__

Const
  lcg_RSV_IsSingleSloj =  1;

  lcg_RSV_Flt_BudVar   =  1;
  lcg_RSV_Flt_KodReg   =  2;
  lcg_RSV_Flt_StBud    =  4;
  lcg_RSV_Flt_Period   =  8;
  lcg_RSV_Flt_Date     = 16;
end;

#endif//__FpRecSlojVal_Inc__
