//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 5.80 - модуль "Платежный календарь"
// Константы ОФП ( реестр ФОб )                                       умолч
//------------------------------------------------------------------------------

Const
  cgFlViewPos_Descr     =  0; // дескриптор
  cgFlViewPos_DesGr     =  1; // группа
  cgFlViewPos_Date      =  2; // дата создания
  cgFlViewPos_DatePay   =  3; // планируемая дата погашения
  cgFlViewPos_Summa     =  4; // сумма по финобязательству
  cgFlViewPos_Direct    =  5; // направление движения средств
  cgFlViewPos_KatDoc    =  6; // тип финансовых обязательств
  cgFlViewPos_FObStatus =  7; // статус финобязательства
  cgFlViewPos_Prior     =  8; // приоритет
  cgFlViewPos_KatOrg    =  9; // контрагент
  cgFlViewPos_FpCO      = 10; // центр ответственности
  cgFlViewPos_Dogovor   = 11; // договор
  cgFlViewPos_BaseDoc   = 12; // документ-основание
  cgFlViewPos_Persons   = 13; // куратор
  cgFlViewPos_FpStBud   = 14; // статья бюджета
  cgFlViewPos_GroupOfp  = 15; // группа
  cgFlViewPos_AktSum    = 16; // сводное ФОб
  cgFlViewPos_VidPlat   = 17; // вид платежа
End;
